import type { DRIVERS as EN } from '../en/drivers';
import { noun, type Gender, type Noun, type Translation } from '../msg';

const male = (name: string): Noun => {
  const ins = /[жшчщц]$/.test(name) ? 'ем' : 'ом';
  return noun('m', name, `${name}а`, `${name}у`, `${name}а`, `${name}${ins}`, `${name}е`);
};
const fixed = (gender: Gender, name: string): Noun => noun(gender, name, name, name, name, name, name);
const femaleA = (stem: string): Noun => {
  const gen = /[гкхжшчщ]$/.test(stem) ? 'и' : 'ы';
  return noun('f', `${stem}а`, `${stem}${gen}`, `${stem}е`, `${stem}у`, `${stem}ой`, `${stem}е`);
};
const ovMale = (name: string): Noun => noun('m', name, `${name}а`, `${name}у`, `${name}а`, `${name}ым`, `${name}е`);
const ovFemale = (name: string): Noun => noun('f', `${name}а`, `${name}ой`, `${name}ой`, `${name}у`, `${name}ой`, `${name}ой`);

export const DRIVERS: Translation<typeof EN> = {
  'driver.full': '{first} {last}',
  'driver.first.Abe': male('Эйб'),
  'driver.first.Ada': femaleA('Ад'),
  'driver.first.Anya': noun('f', 'Аня', 'Ани', 'Ане', 'Аню', 'Аней', 'Ане'),
  'driver.first.Arlo': fixed('m', 'Арло'),
  'driver.first.Bea': fixed('f', 'Беа'),
  'driver.first.Bo': fixed('m', 'Бо'),
  'driver.first.Boris': male('Борис'),
  'driver.first.Cal': male('Кэл'),
  'driver.first.Cass': fixed('f', 'Касс'),
  'driver.first.Clem': male('Клем'),
  'driver.first.Dace': male('Дейс'),
  'driver.first.Dmitri': noun('m', 'Дмитрий', 'Дмитрия', 'Дмитрию', 'Дмитрия', 'Дмитрием', 'Дмитрии'),
  'driver.first.Dora': femaleA('Дор'),
  'driver.first.Earl': male('Эрл'),
  'driver.first.Edda': femaleA('Эдд'),
  'driver.first.Elias': male('Элайас'),
  'driver.first.Faye': fixed('f', 'Фэй'),
  'driver.first.Fenn': male('Фенн'),
  'driver.first.Gus': male('Гас'),
  'driver.first.Hank': male('Хэнк'),
  'driver.first.Hester': fixed('f', 'Эстер'),
  'driver.first.Ida': femaleA('Ид'),
  'driver.first.Igor': noun('m', 'Игорь', 'Игоря', 'Игорю', 'Игоря', 'Игорем', 'Игоре'),
  'driver.first.Ivy': fixed('f', 'Айви'),
  'driver.first.Jed': male('Джед'),
  'driver.first.Jonah': noun('m', 'Иона', 'Ионы', 'Ионе', 'Иону', 'Ионой', 'Ионе'),
  'driver.first.Juno': fixed('f', 'Джуно'),
  'driver.first.Kat': fixed('f', 'Кэт'),
  'driver.first.Lev': noun('m', 'Лев', 'Льва', 'Льву', 'Льва', 'Львом', 'Льве'),
  'driver.first.Lorna': femaleA('Лорн'),
  'driver.first.Lupe': fixed('f', 'Лупе'),
  'driver.first.Mack': male('Мак'),
  'driver.first.Mae': fixed('f', 'Мэй'),
  'driver.first.Mira': femaleA('Мир'),
  'driver.first.Nell': fixed('f', 'Нелл'),
  'driver.first.Nico': fixed('m', 'Нико'),
  'driver.first.Oleg': male('Олег'),
  'driver.first.Opal': fixed('f', 'Опал'),
  'driver.first.Pike': male('Пайк'),
  'driver.first.Pru': fixed('f', 'Пру'),
  'driver.first.Quill': male('Квилл'),
  'driver.first.Raya': noun('f', 'Рая', 'Раи', 'Рае', 'Раю', 'Раей', 'Рае'),
  'driver.first.Rook': male('Рук'),
  'driver.first.Ruth': fixed('f', 'Рут'),
  'driver.first.Sal': male('Сэл'),
  'driver.first.Sasha': noun('m', 'Саша', 'Саши', 'Саше', 'Сашу', 'Сашей', 'Саше'),
  'driver.first.Silas': male('Сайлас'),
  'driver.first.Tam': male('Тэм'),
  'driver.first.Tess': fixed('f', 'Тесс'),
  'driver.first.Ugo': fixed('m', 'Уго'),
  'driver.first.Vera': femaleA('Вер'),
  'driver.first.Vic': male('Вик'),
  'driver.first.Wade': male('Уэйд'),
  'driver.first.Wren': fixed('f', 'Рен'),
  'driver.first.Yuri': noun('m', 'Юрий', 'Юрия', 'Юрию', 'Юрия', 'Юрием', 'Юрии'),
  'driver.first.Zeke': male('Зик'),
  'driver.first.Zoya': noun('f', 'Зоя', 'Зои', 'Зое', 'Зою', 'Зоей', 'Зое'),
  'driver.last.Ash': male('Эш'),
  'driver.last.Baines': male('Бейнс'),
  'driver.last.Barrow': fixed('m', 'Барроу'),
  'driver.last.Boyle': male('Бойл'),
  'driver.last.Brandt': male('Брандт'),
  'driver.last.Cobb': male('Кобб'),
  'driver.last.Crane': male('Крейн'),
  'driver.last.Culver': male('Калвер'),
  'driver.last.Dawes': male('Доуз'),
  'driver.last.Drummond': male('Драммонд'),
  'driver.last.Dust': male('Даст'),
  'driver.last.Fisk': male('Фиск'),
  'driver.last.Flint': male('Флинт'),
  'driver.last.Gage': male('Гейдж'),
  'driver.last.Garza': noun('m', 'Гарса', 'Гарсы', 'Гарсе', 'Гарсу', 'Гарсой', 'Гарсе'),
  'driver.last.Grell': male('Грелл'),
  'driver.last.Harrow': fixed('m', 'Харроу'),
  'driver.last.Hatch': male('Хэтч'),
  'driver.last.Holt': male('Холт'),
  'driver.last.Irons': male('Айронс'),
  'driver.last.Jarvis': male('Джарвис'),
  'driver.last.Kane': male('Кейн'),
  'driver.last.Kessler': male('Кесслер'),
  'driver.last.Kovac': male('Ковач'),
  'driver.last.Lark': male('Ларк'),
  'driver.last.Lowry': fixed('m', 'Лоури'),
  'driver.last.Marsh': male('Марш'),
  'driver.last.Mercer': male('Мерсер'),
  'driver.last.Morozov': ovMale('Морозов'),
  'driver.last.Nash': male('Нэш'),
  'driver.last.Oakes': male('Оукс'),
  'driver.last.Orlov': ovMale('Орлов'),
  'driver.last.Pell': male('Пелл'),
  'driver.last.Quarry': fixed('m', 'Куорри'),
  'driver.last.Radek': male('Радек'),
  'driver.last.Reyes': male('Рейес'),
  'driver.last.Rusk': male('Раск'),
  'driver.last.Salt': male('Солт'),
  'driver.last.Sokol': male('Сокол'),
  'driver.last.Stroud': male('Страуд'),
  'driver.last.Tallow': fixed('m', 'Таллоу'),
  'driver.last.Thorne': male('Торн'),
  'driver.last.Tulloch': male('Таллох'),
  'driver.last.Vance': male('Вэнс'),
  'driver.last.Volkov': ovMale('Волков'),
  'driver.last.Wick': male('Уик'),
  'driver.last.Yates': male('Йейтс'),
  'driver.last.Zane': male('Зейн'),
  'driver.last.Ash.f': fixed('f', 'Эш'),
  'driver.last.Baines.f': fixed('f', 'Бейнс'),
  'driver.last.Barrow.f': fixed('f', 'Барроу'),
  'driver.last.Boyle.f': fixed('f', 'Бойл'),
  'driver.last.Brandt.f': fixed('f', 'Брандт'),
  'driver.last.Cobb.f': fixed('f', 'Кобб'),
  'driver.last.Crane.f': fixed('f', 'Крейн'),
  'driver.last.Culver.f': fixed('f', 'Калвер'),
  'driver.last.Dawes.f': fixed('f', 'Доуз'),
  'driver.last.Drummond.f': fixed('f', 'Драммонд'),
  'driver.last.Dust.f': fixed('f', 'Даст'),
  'driver.last.Fisk.f': fixed('f', 'Фиск'),
  'driver.last.Flint.f': fixed('f', 'Флинт'),
  'driver.last.Gage.f': fixed('f', 'Гейдж'),
  'driver.last.Garza.f': noun('f', 'Гарса', 'Гарсы', 'Гарсе', 'Гарсу', 'Гарсой', 'Гарсе'),
  'driver.last.Grell.f': fixed('f', 'Грелл'),
  'driver.last.Harrow.f': fixed('f', 'Харроу'),
  'driver.last.Hatch.f': fixed('f', 'Хэтч'),
  'driver.last.Holt.f': fixed('f', 'Холт'),
  'driver.last.Irons.f': fixed('f', 'Айронс'),
  'driver.last.Jarvis.f': fixed('f', 'Джарвис'),
  'driver.last.Kane.f': fixed('f', 'Кейн'),
  'driver.last.Kessler.f': fixed('f', 'Кесслер'),
  'driver.last.Kovac.f': fixed('f', 'Ковач'),
  'driver.last.Lark.f': fixed('f', 'Ларк'),
  'driver.last.Lowry.f': fixed('f', 'Лоури'),
  'driver.last.Marsh.f': fixed('f', 'Марш'),
  'driver.last.Mercer.f': fixed('f', 'Мерсер'),
  'driver.last.Morozov.f': ovFemale('Морозов'),
  'driver.last.Nash.f': fixed('f', 'Нэш'),
  'driver.last.Oakes.f': fixed('f', 'Оукс'),
  'driver.last.Orlov.f': ovFemale('Орлов'),
  'driver.last.Pell.f': fixed('f', 'Пелл'),
  'driver.last.Quarry.f': fixed('f', 'Куорри'),
  'driver.last.Radek.f': fixed('f', 'Радек'),
  'driver.last.Reyes.f': fixed('f', 'Рейес'),
  'driver.last.Rusk.f': fixed('f', 'Раск'),
  'driver.last.Salt.f': fixed('f', 'Солт'),
  'driver.last.Sokol.f': fixed('f', 'Сокол'),
  'driver.last.Stroud.f': fixed('f', 'Страуд'),
  'driver.last.Tallow.f': fixed('f', 'Таллоу'),
  'driver.last.Thorne.f': fixed('f', 'Торн'),
  'driver.last.Tulloch.f': fixed('f', 'Таллох'),
  'driver.last.Vance.f': fixed('f', 'Вэнс'),
  'driver.last.Volkov.f': ovFemale('Волков'),
  'driver.last.Wick.f': fixed('f', 'Уик'),
  'driver.last.Yates.f': fixed('f', 'Йейтс'),
  'driver.last.Zane.f': fixed('f', 'Зейн'),
};
