import type { LOG as EN } from '../en/log';
import type { Translation } from '../msg';

export const LOG: Translation<typeof EN> = {
  'job.search': 'Обыск',
  'job.weld': 'Сварить броню из лома',
  'job.somePart': 'деталь',
  'job.repair': 'Ремонт: {part}',
  'job.strip': 'Снять: {part}',
  'job.theTruck': 'грузовик',
  'job.remove': 'Снять {part} — {truck}',
  'job.refit': 'Переоснащение: {parts}',
  'job.refitNothing': 'Переоснащение',
  'job.patch': 'Ремонт: {truck}',
  'job.patchedBy': 'Чинит: {truck}',
  'job.takingFromYou': 'Забирает у вас: {goods}',
  'job.givingYou': 'Передаёт вам: {goods}',
  'job.givingTo': 'Передача: {goods} — {truck}',
  'job.takingFrom': 'Получение: {goods} — {truck}',
  'cond.junk': 'негодная',
  'cond.pristine': 'новая',
  'cond.rebuilt': 'восст. ×{n}',
  'cond.scrapOnly': 'только на лом',
  'cond.broken': 'сломана',
  'cond.hp': '{hp}/{max} ПЧ',
  'log.you': 'Вы',
  'log.anObstacle': 'препятствие',
  'log.something': 'что-то',
  'npc.gaveUp': 'Сдался',
  'npc.knockedOut': 'Без сознания',
  'npc.traits': 'Черты: {traits}',
  'npc.goodCount': '{good} ×{n}',
  'npc.cargoEmpty': 'Груз: пусто',
  'npc.cargo': 'Груз: {goods}',
  'npc.spares': 'Запчасти: {spares}',
  'npc.cargoAndSpares': 'Груз: {goods}. Запчасти: {spares}',
  'npc.marked': 'Помечен: {n, plural, one {остался # ход} few {осталось # хода} many {осталось # ходов} other {осталось # хода}}',
  'npc.markKey': '[N] Пометить',
  'state.feud': 'Враждует с вами',
  'state.backedOff': 'Отступает от вас',
  'state.towing': 'Тащит вас',
  'state.towOffer': 'Предлагает вам буксир',
  'state.turnedDown': 'Вы отказались от его буксира',
  'state.towPromise': 'Обещал вам буксир',
  'state.answering': 'Едет вас буксировать',
  'state.patch': 'Чинит ваш грузовик',
  'state.truce': 'Перемирие с вами',
  'state.grievance': 'Зол из-за вашего тарана',
  'state.pleaTruce': 'Просил у вас перемирия',
  'state.pleaMercy': 'Молил вас о пощаде',
  'state.trade': 'Тормозит, чтобы поторговать с вами',
  'state.revenge': 'Жаждет мести',
  'state.escort': 'Сопровождает вас',
  'state.aidBringing': 'Везёт вам топливо',
  'state.aidWaiting': 'Ждёт вашего топлива',
  'state.combat': 'В бою',
  'state.strayFire': 'Задет вашим шальным огнём, прощено {forgiven} из {of} урона',
  'state.withTurns': '{label}, {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'log.feudExpired': '{who} прекращает вражду с вами.',
  'log.feudFulfilled': '{who} прекращает вражду: вы побеждены.',
  'log.feudBroken': 'Вражда закончена: {who}.',
  'log.backedOffExpired': '{who} больше не отступает от вас.',
  'log.aidExpired': 'Сделка о топливе истекла: {who}.',
  'log.aidBroken': 'Сделка о топливе сорвалась: {who}.',
  'short.gun': 'Орд',
  'short.eng': 'Дв',
  'short.arm': 'Брн',
  'short.cargo': 'Груз',
  'short.scan': 'Скан',
  'short.store': 'Запас',
  'short.cab': 'Каб',
  'short.trans': 'КПП',
  'short.whl': 'Кол',
  'short.tank': 'Бак',
  'log.partDamage': '{part}: {n}',
  'log.critParts': 'Крит! {parts}',
  'log.strayHits': ', шальной огонь задел: {who}',
  'log.shot': '{gun} → {target}, попаданий {hits}/{rounds}',
  'log.shotAt': '{gun} → {target}, по цели «{part}», попаданий {hits}/{rounds}',
  'log.shotChance': ' ({pct}%)',
  'log.shotCrits': ', крит.: {n}',
  'log.hit': '{part} −{n}',
  'log.hitBroken': '{part} −{n}, сломано',
  'log.damageLead': ': ',
  'log.damageSep': ', ',
  'log.jobStarted': '{what}: начато. Стойте на месте примерно {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}.',
  'log.jobCancelled': '{what}: отменено. Грузовик сдвинулся, появился враг или изменились нужные предметы',
  'log.jobDone': '{what}: готово',
  'log.weather.storm.started': 'Началась пыльная буря',
  'log.weather.storm.ended': 'Пыльная буря закончилась',
  'log.weather.heatwave.started': 'Началась жара',
  'log.weather.heatwave.ended': 'Жара спала',
  'log.weather.overcast.started': 'Небо затянуло',
  'log.weather.overcast.ended': 'Небо прояснилось',
  'log.youHonk': 'Вы сигналите.',
  'log.honksBack': '{who} сигналит в ответ.',
  'log.hornUnseen': 'Где-то вне видимости отвечает гудок.',
  'log.patchStartYou': 'Вы начинаете чинить: {who}. Стойте рядом.',
  'log.patchStartThem': '{who} начинает чинить ваш грузовик. Стойте на месте.',
  'log.patchDoneYou': 'Вы починили: {who}.',
  'log.patchDoneThem': '{who} починил ваш грузовик.',
  'log.patchLapsed': 'Ремонт отменён ({who}): никто не работал.',
  'log.patchBroken': 'Ремонт отменён: {who}.',
  'log.aidNothing': 'Обмена не было: {who}.',
  'log.aidPaid': '{goods} за {paid}',
  'log.aidYouGive': 'Вы передаёте ({who}): {moved}.',
  'log.aidGivesYou': '{who} передаёт вам: {moved}.',
  'log.aidStartYou': 'Вы начинаете передачу: {who}.',
  'log.aidStartThem': '{who} начинает передавать вам товар.',
  'log.say': '{who}: «{line}»',
  'log.towOffer': '{who} предлагает дотащить вас, пункт — {site}, за {fee}.',
  'log.towOfferFree': '{who} предлагает дотащить вас, пункт — {site}, бесплатно.',
  'log.towHitched': '{who} берёт на буксир: {client}, пункт — {site}.',
  'log.towedYouFree': '{who} бесплатно дотащил вас до города.',
  'log.towedYouPaid': '{who} дотащил вас до города и взял {fee}.',
  'log.towedFree': '{who} бесплатно дотащил: {client}.',
  'log.towedPaid': '{who} дотащил ({client}) и взял {fee}.',
  'log.escortPaid': '{client} платит за сопровождение {fee}: {who}.',
  'log.escortHired': '{client} нанимает сопровождение ({who}), пункт — {site}, за {fee}.',
  'log.escortRefused': '{who} отказывается сопровождать: {client}.',
  'log.plea.truce.granted': '{who} просит перемирия ({to}): согласие',
  'log.plea.truce.refused': '{who} просит перемирия ({to}): отказ',
  'log.plea.mercy.granted': '{who} молит о пощаде ({to}): согласие',
  'log.plea.mercy.refused': '{who} молит о пощаде ({to}): отказ',
  'log.towGone': '{who} пропал. {client} отцеплен.',
  'log.towDropped': '{who} бросает буксир: {client}.',
  'log.towDroppedYou.refused': 'Вы отказываетесь от буксира: {who}.',
  'log.towDroppedYou.unhitched': 'Вы отцепляетесь: {who}.',
  'log.towDroppedYou.danger': '{who} бросает буксир. Опасность.',
  'log.towDroppedYou.stranded': '{who} больше не может ехать. Буксир отменён.',
  'log.towDroppedYou.gone': '{who} пропал. Буксир отменён.',
  'log.towDroppedYou.blocked': '{who} не может к вам пробраться. Буксир отменён.',
  'log.searchDoneAt': 'Обыск закончен: {site}.',
  'log.searchDone': 'Обыск закончен.',
  'log.contract.accepted': 'Контракт взят: {what}, оплата {reward}',
  'log.contract.done': 'Контракт выполнен: {what}, оплата {reward}',
  'log.contract.failed': 'Контракт провален: {what}, оплата {reward}',
  'log.contract.lapsed': 'Контракт истёк: {what}, оплата {reward}',
  'log.contract.expiring': 'Срок контракта на исходе: {what}, {due}',
  'log.rankBought': '{skill}: куплен ранг {rank}.',
  'log.rankBoughtPerk': '{skill}: куплен ранг {rank}. Можно выбрать навык [C].',
  'log.debugActivity': '{who}: {what} — {why}',
  'log.debugStall': 'Ошибка: {who} застрял на {what} ({why}) и бросил',
  'log.moneyGain': '+{n} денег: {reason}',
  'log.moneyLoss': '{n} денег: {reason}',
  'log.guardShot': 'Охрана ({site}) → {target}, попаданий {hits}/{rounds}',
  'log.discovered': 'Открыто место: {site}',
  'log.partDisabled': '{who}: {part} выведено из строя',
  'log.breakdown': 'Сломалось: {part}',
  'log.townPatch': 'Вы латаете грузовик ломом.',
  'log.scrapPatch': 'Вы латаете машину ломом, пока она снова не трогается с места.',
  'log.scrapPatchFuel': 'Вы латаете машину ломом, пока она снова не трогается с места. Горожане делятся с вами топливом: {liters} л.',
  'log.npcKnockout': '{who}: без сознания',
  'log.npcWake': '{who} приходит в себя',
  'log.destroyed': '{who}: уничтожен',
  'log.hostile': '{who} становится враждебен к вам',
  'log.death': 'Вы погибли.',
  'log.knockout': 'Вы теряете сознание.',
  'log.wake': 'Вы приходите в себя.',
  'contract.haul': 'Доставить {good} ×{n}, пункт — {site}',
  'contract.rushHaul': 'Срочно: доставить {good} ×{n}, пункт — {site}',
  'contract.fetch': 'Привезти {part}, пункт — {site}: исправную, {n, plural, one {восстановленную не более # раза} few {восстановленную не более # раз} many {восстановленную не более # раз} other {восстановленную не более # раза}}',
  'contract.bounty': 'Вырубить или разбить любого: {target}',
  'contract.window': '{h} ч',
  'contract.due': 'до: {when}',
  'clock.day': 'День {day}',
  'clock.full': 'День {day}, {time}',
  'goods.good': 'Товар',
  'goods.theirs': 'У них',
  'goods.buy': 'Купить',
  'goods.sell': 'Продать',
  'goods.held': 'Есть',
  'goods.profit': 'Прибыль/ед.',
  'goods.profitTitle': 'Цена продажи здесь минус ваша средняя цена закупки. Найденный и перевезённый товар считается по обычной стоимости.',
  'goods.unknown': '?',
  'goods.even': '0',
  'goods.gain': '+{n}',
  'goods.loss': '−{n}',
  'goods.noCost': 'Цена закупки неизвестна',
  'goods.avgCost': 'Средняя цена {n}',
  'goods.buyLot': 'Купить {n} за {total}',
  'goods.sellLot': 'Продать все {n} за {total}',
  'log.stamped': '{time} {line}',
  'log.title': 'Журнал',
  'log.panel': 'Журнал событий',
  'log.expand': 'Развернуть журнал',
  'log.shrink': 'Свернуть журнал',
  // Why a driver took up or ended a goal.
  'goal.arrived': 'Прибыл',
  'goal.avoidCostlyFight': 'Избежать дорогой драки',
  'goal.bringAid': 'Привезти топливо и припасы',
  'goal.buyCargo': 'Купить выгодный груз',
  'goal.cannotAffordCargo': 'Груз не по карману',
  'goal.cannotDrive': 'Не может ехать',
  'goal.cargoFullLoad': 'Некуда грузить',
  'goal.cargoFullLoot': 'Добыча не влезает',
  'goal.cargoFullSalvage': 'Лом не влезает',
  'goal.choseNew': 'Выбрал другое дело',
  'goal.collectSalvage': 'Собрать замеченный лом',
  'goal.combatStopsLooting': 'Бой мешает грабежу',
  'goal.combatStopsRepair': 'Бой мешает ремонту',
  'goal.combatStopsSearch': 'Бой мешает поиску',
  'goal.contactGone': 'Цель пропала',
  'goal.damagedThreatened': 'Повреждён и под угрозой',
  'goal.defendLoot': 'Защитить свою добычу',
  'goal.deliverCargo': 'Доставить купленный груз',
  'goal.droppedTow': 'Бросил буксир',
  'goal.escapeAttacker': 'Уйти от нападающего',
  'goal.escapeThreat': 'Уйти от угрозы',
  'goal.explore': 'Разведка',
  'goal.exploredSpot': 'Осмотрел место',
  'goal.fightBack': 'Дать отпор',
  'goal.fightHostile': 'Атаковать врага в поле зрения',
  'goal.finishedRepairs': 'Закончил ремонт в поле',
  'goal.finishedService': 'Обслужился',
  'goal.fitAgain': 'Снова в строю',
  'goal.followLeader': 'Следовать за ведущим',
  'goal.foundNothing': 'На месте цели пусто',
  'goal.heardHostile': 'Слышал врага за пределами видимости',
  'goal.helpStranded': 'Помочь застрявшему грузовику',
  'goal.homeToLieUp': 'Домой, отлежаться',
  'goal.idle': 'Без дела',
  'goal.inCombat': 'В бою',
  'goal.keepWord': 'Держит слово',
  'goal.leftLeader': 'Отстал от ведущего',
  'goal.legacy': 'Занят',
  'goal.lieUp': 'Отлежаться ради нового снаряжения',
  'goal.loadCargo': 'Загрузиться на месте',
  'goal.lootClaimed': 'Добычу уже застолбили',
  'goal.lootDowned': 'Ограбить подбитый грузовик',
  'goal.lootGone': 'Добыча пропала',
  'goal.lootOnTheWay': 'Собрать лом по пути',
  'goal.lootRobbed': 'Обчистить ограбленный грузовик',
  'goal.lootTaken': 'Там уже кто-то грабит',
  'goal.lostSalvage': 'Потерял лом из виду',
  'goal.lostTarget': 'Потерял цель',
  'goal.lowFuel': 'Мало топлива',
  'goal.lowSupplies': 'Мало припасов',
  'goal.meetingOff': 'Встреча отменена',
  'goal.needsRepairs': 'Нужен ремонт',
  'goal.noExplorePoint': 'Некуда ехать на разведку',
  'goal.noGun': 'Нечем воевать',
  'goal.noHostile': 'Врагов не видно',
  'goal.noProgress': 'Слишком долго без толку',
  'goal.nothingToDo': 'Нечего делать',
  'goal.nothingToLoot': 'Грабить больше нечего',
  'goal.nowhereToRun': 'Дальше бежать некуда',
  'goal.patchOff': 'Ремонт отменён',
  'goal.patchParts': 'Подлатать повреждённые детали',
  'goal.patchTruck': 'Подлатать грузовик',
  'goal.patrolCamp': 'Патрулировать дороги у лагеря',
  'goal.patrolTown': 'Патрулировать дороги у города',
  'goal.patrolledRoad': 'Проехал дозором',
  'goal.pickUpAid': 'Забрать топливо и припасы',
  'goal.prowl': 'Рыскать по дорогам в поисках обломков',
  'goal.prowledRoad': 'Обрыскал дорогу',
  'goal.pullOver': 'Остановиться для торговли',
  'goal.raid': 'Искать добычу в охотничьих угодьях',
  'goal.reachedGround': 'Добрался до угодий',
  'goal.refitted': 'Переоснастился дома',
  'goal.refuseThreat': 'Не поддаваться на угрозы',
  'goal.retreatHome': 'Отступить домой после поражения',
  'goal.robCargo': 'Отнять груз',
  'goal.salvageExhausted': 'Лом кончился',
  'goal.salvageGone': 'Лома больше нет',
  'goal.searchSite': 'Обыскать известную свалку',
  'goal.searchSpot': 'Обыскать место с добычей',
  'goal.sellCargo': 'Продать груз',
  'goal.soldCargo': 'Продал груз',
  'goal.spottedHeard': 'Заметил грузовик, который слышал',
  'goal.strandedRobbery': 'Застрял, бросил грабёж',
  'goal.takeClaimedLoot': 'Забрать застолбленную добычу',
  'goal.takeHandedCargo': 'Забрать отданный груз',
  'goal.towNotNeeded': 'Буксир больше не нужен',
  'goal.towOff': 'Буксировка отменена',
  'goal.towOfferLeft': 'Водитель уехал, не дождавшись буксира',
  'goal.towPlayer': 'Тащить вас в город',
  'goal.towStranded': 'Тащить застрявший грузовик',
  'goal.towUnanswered': 'Не дозвался до грузовика',
  'goal.towedPlayer': 'Дотащил вас до города',
  'goal.towedStranded': 'Дотащил застрявший грузовик',
  'goal.tripToSite': 'Съездить в другое место',
  'goal.truckGotAway': 'Грузовик ушёл',
  'goal.unfitToHunt': 'Не годится для охоты',
  'goal.waitPatch': 'Ждать ремонта',
  'goal.waitTow': 'Ждать буксира',
  'goal.waitTowAnswer': 'Ждать ответа на предложение буксира',
  'goal.warnedOff': 'Отогнали от добычи',
  'note.engineHot': 'Двигатель перегревается.',
  'note.engineOverheat': 'Двигатель перегрелся: двигатель −{hp} ПЧ',
  'note.engineDoused': 'Двигатель залит водой: припасы −{supplies}',
  'note.outOfSupplies': 'Припасы кончились: здоровье −{health}',
  'note.noRoomFuel': 'Топливу нет места: топливо −{fuel}',
  'note.noRoomSupplies': 'Припасам нет места: припасы −{supplies}',
  'note.tankLeak': 'Бак течёт: топливо −{fuel}',
  'note.filledSupplies': 'Припасы пополнены: {site}',
  'note.hazard': 'От светящегося ядра тянет тошнотворным жаром. По коже бегут мурашки, руль дрожит в руках.',
  'note.spawnBlocked': 'Нет места, чтобы появился {template}',
  'money.contract': 'контракт',
  'money.failedHaul': 'проваленный контракт на перевозку',
  'money.towing': 'буксировка: {vehicle}',
  'refusal.noFit': 'Сюда не влезает',
  'refusal.inTheWay': 'Что-то мешает',
  'refusal.armorOnly': 'По бокам ставится только броня',
  'refusal.badLayout': '{cause}. Предметы выпадут из сетки или наложатся друг на друга.',
  'refusal.itemGone': 'Этого предмета уже нет',
  'refusal.refitRunning': 'Сначала закончите переоснащение',
  'refusal.twoInTheWay': 'Мешает больше одного предмета',
  'refusal.refitItemMoved': 'Предмет для переоснащения сдвинулся или пропал',
  'refusal.builtInFixed': 'Встроенные детали не двигаются',
  'refusal.salvageOutOfReach': 'Лом уже не достать',
  'refusal.salvagePartGone': 'Этой детали в ломе больше нет',
  'refusal.builtInStays': 'Встроенные детали остаются на грузовике',
  'refusal.emptyRackFirst': 'Сначала освободите этот багажник',
  'refusal.truckOutOfReach': 'Грузовик вне досягаемости',
  'refusal.truckPartGone': 'Этой детали на грузовике больше нет',
  'refusal.looting.here': 'Здесь уже грабит {by}',
  'refusal.looting.wreck': 'Эти обломки уже грабит {by}',
  'refusal.looting.truck': 'Этот грузовик уже грабит {by}',
  'refusal.needsSpotter': 'Чтобы метить грузовики, нужен навык «Наводчик»',
  'refusal.cannotAct': 'Сейчас вы не можете действовать',
  'refusal.noTruck': 'Некого пометить',
  'refusal.unseen': 'Вы не видите этот грузовик',
  'refusal.notActive.dead': 'Вы мертвы',
  'refusal.notActive.knockedOut': 'Вы без сознания',
  'refusal.topRank': '{skill}: уже высший ранг',
  'refusal.needsXp': 'Нужно опыта: {cost}, у вас: {have}',
  'refusal.failed': 'Не получилось.',
  'refusal.noMoney': 'Не хватает денег',
  'refusal.noCargoRoom': 'Не хватает места в кузове',
  'refusal.theyHaveNoRoom': 'У них нет места',
  'refusal.noSupplyRoom': 'Столько не поместится',
  'refusal.inCombat': 'Не во время боя',
  'refusal.stopFirst': 'Сначала остановите грузовик',
  'unit.part': '{n, plural, one {# деталь} few {# детали} many {# деталей} other {# детали}}',
  'vehicle.yours': 'Ваш грузовик',
  'vehicle.npc': '{profession} {driver}',
};
