import type { LOG as EN } from '../en/log';
import { noun, type Translation } from '../msg';

export const LOG: Translation<typeof EN> = {
  'job.search': 'Поиски',
  'job.weld': 'Сварить броню из лома',
  'job.somePart': noun('f', 'деталь', 'детали', 'детали', 'деталь', 'деталью', 'детали'),
  'job.repair': 'Ремонт {part, case, gen}',
  'job.strip': 'Снятие {part, case, gen}',
  'job.theTruck': noun('m', 'грузовик', 'грузовика', 'грузовику', 'грузовик', 'грузовиком', 'грузовике'),
  'job.remove': 'Снятие {part, case, gen} с {truck, case, gen}',
  'job.refit': 'Переоснащение {parts, case, gen}',
  'job.refitNothing': 'Переоснащение',
  'job.patch': 'Ремонт {truck, case, gen}',
  'job.patchedBy': 'Чинит {truck, case, nom}',
  'job.takingFromYou': 'Забирает у вас {goods}',
  'job.givingYou': 'Отдаёт вам {goods}',
  'job.givingTo': 'Вы отдаёте {truck, case, dat} {goods}',
  'job.takingFrom': 'Вы забираете у {truck, case, gen} {goods}',
  'cond.junk': 'лом',
  'cond.pristine': 'без износа',
  'cond.rebuilt': '{n, plural, one {# капремонт} few {# капремонта} many {# капремонтов} other {# капремонта}}',
  'cond.scrapOnly': 'только на лом',
  'cond.broken': 'не работает',
  'cond.hp': '{hp}/{max} прочн.',
  'log.you': noun('pl', 'вы', 'вас', 'вам', 'вас', 'вами', 'вас'),
  'log.anObstacle': noun('n', 'препятствие', 'препятствия', 'препятствию', 'препятствие', 'препятствием', 'препятствии'),
  'log.something': noun('n', 'что-то', 'чего-то', 'чему-то', 'что-то', 'чем-то', 'чём-то'),
  'npc.gaveUp': 'Сдался',
  'npc.knockedOut': 'Без сознания',
  'npc.traits': 'Черты: {traits}',
  'npc.goodCount': '{good} ×{n}',
  'npc.cargoEmpty': 'Груз: пусто',
  'npc.cargo': 'Груз: {goods, case, nom}',
  'npc.spares': 'Запчасти: {spares, case, nom}',
  'npc.cargoAndSpares': 'Груз: {goods, case, nom}. Запчасти: {spares, case, nom}',
  'npc.marked': 'Помечен: {n, plural, one {остался # ход} few {осталось # хода} many {осталось # ходов} other {осталось # хода}}',
  'npc.markKey': '[N] Пометить',
  'state.feud': 'Враждует с вами',
  'state.backedOff': 'Отступает от вас',
  'state.towing': 'Тащит вас',
  'state.towOffer': 'Предлагает вам буксир',
  'state.turnedDown': 'Вы отказались от его буксира',
  'state.towPromise': 'Обещал вам буксир',
  'state.answering': 'Едет буксировать вас',
  'state.patch': 'Чинит ваш грузовик',
  'state.truce': 'Перемирие с вами',
  'state.grievance': 'Зол из-за вашего тарана',
  'state.pleaTruce': 'Просил у вас перемирия',
  'state.pleaMercy': 'Молил вас о пощаде',
  'state.trade': 'Тормозит, чтобы поторговать с вами',
  'state.revenge': 'Жаждет мести',
  'state.escort': 'Сопровождает вас',
  'state.aidBringing': 'Везёт вам топливо',
  'state.aidWaiting': 'Ждёт вашего топлива',
  'state.combat': 'В бою',
  'state.strayFire': 'Задет вашим шальным огнём, прощено {forgiven} из {of} урона',
  'state.lootWarning': 'Гонит вас от своей добычи',
  'state.lootAgreed': 'Вы согласились не трогать его добычу',
  'state.moving': 'Едет, {n} км/ч',
  'state.parked': 'Стоит',
  'state.shutDown': 'Заглушен',
  'state.join': '{first}. {rest}',
  'loot.place.wreck': 'остова',
  'loot.place.pile': 'кучи',
  'loot.place.spot': 'места',
  'loot.place.truck': 'грузовика',
  'log.lootYielded': '{warner} гонит {looter} от {place}. {looter} уезжает.',
  'log.lootBackedOff': '{warner} гонит {looter} от {place}. {looter} остаётся на месте, а {warner} уезжает.',
  'log.lootFight': '{warner} гонит {looter} от {place}. Они дерутся из-за добычи.',
  'state.withTurns': '{label}, {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'log.feudExpired': '{who} прекращает вражду с вами.',
  'log.feudFulfilled': 'Вы разбиты, и {who, case, nom} прекращает вражду.',
  'log.feudBroken': 'Вражда с {who, case, ins} закончилась.',
  'log.backedOffExpired': '{who} больше не отступает от вас.',
  'log.aidExpired': 'Сделка о топливе с {who, case, ins} истекла.',
  'log.aidBroken': 'Сделка о топливе с {who, case, ins} сорвалась.',
  'short.gun': 'Оруж.',
  'short.eng': 'Двиг.',
  'short.arm': 'Броня',
  'short.cargo': 'Груз',
  'short.scan': 'Скан',
  'short.store': 'Запас',
  'short.cab': 'Каб.',
  'short.trans': 'КПП',
  'short.whl': 'Шины',
  'short.tank': 'Бак',
  'log.partDamage': '{part}: {n}',
  'log.critParts': 'Крит! {parts}',
  'log.strayHits': ', шальной огонь задел {who, case, acc}',
  'log.shot': '{gun} бьёт по {target, case, dat}, попаданий {hits} из {rounds}',
  'log.shotAt': '{gun} бьёт по {target, case, dat}, целясь в {part, case, acc}, попаданий {hits} из {rounds}',
  'log.shotChance': ' ({pct}%)',
  'log.shotCrits': ', {n} крит.',
  'log.hit': '{part, case, nom} −{n}',
  'log.hitBroken': '{part, case, nom} −{n}, {part, gender, m {сломан} f {сломана} n {сломано} pl {сломаны}}',
  'log.damageLead': ': ',
  'log.damageSep': ', ',
  'log.jobStarted': '{what}: работа пошла. Не трогайтесь с места примерно {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}.',
  'log.jobCancelled': '{what}: работа сорвана. Грузовик сдвинулся, появился враг или изменились нужные предметы',
  'log.jobDone': '{what}: готово',
  'log.weather.storm.started': 'Поднялась пыльная буря',
  'log.weather.storm.ended': 'Пыльная буря улеглась',
  'log.weather.heatwave.started': 'Жара навалилась',
  'log.weather.heatwave.ended': 'Жара спала',
  'log.weather.overcast.started': 'Небо затянуло',
  'log.weather.overcast.ended': 'Небо прояснилось',
  'log.youHonk': 'Вы сигналите.',
  'log.honksBack': '{who} сигналит в ответ.',
  'log.hornUnseen': 'Где-то вне видимости отвечает гудок.',
  'log.patchStartYou': 'Вы начинаете чинить {who, case, acc}. Стойте рядом.',
  'log.patchStartThem': '{who} начинает чинить ваш грузовик. Стойте на месте.',
  'log.patchDoneYou': 'Вы починили {who, case, acc}.',
  'log.patchDoneThem': '{who} {who, gender, m {починил} f {починила} n {починило} pl {починили}} ваш грузовик.',
  'log.patchLapsed': 'Ремонт с {who, case, ins} отменён: никто не работал.',
  'log.patchBroken': 'Ремонт с {who, case, ins} отменён.',
  'log.aidNothing': 'Обмена с {who, case, ins} не было.',
  'log.aidPaid': '{goods} за {paid}',
  'log.aidYouGive': 'Вы передаёте {who, case, dat} {moved}.',
  'log.aidGivesYou': '{who} передаёт вам {moved}.',
  'log.aidStartYou': 'Вы начинаете передавать товар {who, case, dat}.',
  'log.aidStartThem': '{who} начинает передавать вам товар.',
  'log.say': '{who}: «{line}»',
  'log.towOffer': '{who} предлагает дотащить вас до {site, case, gen} за {fee}.',
  'log.towOfferFree': '{who} предлагает дотащить вас до {site, case, gen} бесплатно.',
  'log.towHitched': '{who} берёт {client, case, acc} на буксир до {site, case, gen}.',
  'log.towedYouFree': '{who} бесплатно {who, gender, m {дотащил} f {дотащила} n {дотащило} pl {дотащили}} вас до города.',
  'log.towedYouPaid': '{who} {who, gender, m {дотащил} f {дотащила} n {дотащило} pl {дотащили}} вас до города и {who, gender, m {взял} f {взяла} n {взяло} pl {взяли}} {fee}.',
  'log.towedFree': '{who} бесплатно {who, gender, m {дотащил} f {дотащила} n {дотащило} pl {дотащили}} {client, case, acc} до города.',
  'log.towedPaid': '{who} {who, gender, m {дотащил} f {дотащила} n {дотащило} pl {дотащили}} {client, case, acc} до города и {who, gender, m {взял} f {взяла} n {взяло} pl {взяли}} {fee}.',
  'log.escortPaid': '{who} получает {fee} от {client, case, gen} за сопровождение.',
  'log.escortHired': '{who} нанимается сопровождать {client, case, acc} до {site, case, gen} за {fee}.',
  'log.escortRefused': '{who} отказывается сопровождать {client, case, acc}.',
  'log.plea.truce.granted': '{who} просит перемирия у {to, case, gen}: {to, gender, m {согласился} f {согласилась} n {согласилось} pl {согласились}}',
  'log.plea.truce.refused': '{who} просит перемирия у {to, case, gen}: {to, gender, m {отказал} f {отказала} n {отказало} pl {отказали}}',
  'log.plea.mercy.granted': '{who} молит {to, case, acc} о пощаде: {to, gender, m {пощадил} f {пощадила} n {пощадило} pl {пощадили}}',
  'log.plea.mercy.refused': '{who} молит {to, case, acc} о пощаде: {to, gender, m {не пощадил} f {не пощадила} n {не пощадило} pl {не пощадили}}',
  'log.towGone': '{who} {who, gender, m {пропал} f {пропала} n {пропало} pl {пропали}}. {client} {client, gender, m {отцеплен} f {отцеплена} n {отцеплено} pl {отцеплены}}.',
  'log.towDropped': '{who} бросает буксировку {client, case, gen}.',
  'log.towDroppedYou.refused': 'Вы отказываетесь от буксира {who, case, gen}.',
  'log.towDroppedYou.unhitched': 'Вы отцепляетесь от {who, case, gen}.',
  'log.towDroppedYou.danger': '{who} бросает буксир. Опасность.',
  'log.towDroppedYou.stranded': '{who} больше не может ехать. Буксир отменён.',
  'log.towDroppedYou.gone': '{who} {who, gender, m {пропал} f {пропала} n {пропало} pl {пропали}}. Буксир отменён.',
  'log.towDroppedYou.blocked': '{who} не может к вам пробраться. Буксир отменён.',
  'log.searchDoneAt': 'Вы обшарили {site, case, acc}.',
  'log.searchDone': 'Поиски закончены.',
  'log.contract.accepted': 'Контракт взят: {what}, оплата {reward}',
  'log.contract.done': 'Контракт выполнен: {what}, оплата {reward}',
  'log.contract.failed': 'Контракт провален: {what}, оплата {reward}',
  'log.contract.lapsed': 'Контракт истёк: {what}, оплата {reward}',
  'log.contract.expiring': 'Срок контракта на исходе: {what}, {due}',
  'log.contract.fulfilled': 'Награда за голову: {target, case, nom} {target, gender, m {повержен} f {повержена} n {повержено} pl {повержены}}, получите {reward} {site, case, at}',
  'log.rankBought': '{skill}: куплен ранг {rank}.',
  'log.rankBoughtPerk': '{skill}: куплен ранг {rank}. Можно выбрать навык [C].',
  'log.debugActivity': '{who}: {what} — {why}',
  'log.debugStall': 'Ошибка: {who, case, nom} {who, gender, m {застрял} f {застряла} n {застряло} pl {застряли}} на {what} ({why}) и {who, gender, m {бросил} f {бросила} n {бросило} pl {бросили}} это',
  'log.moneyGain': '+{n}: {reason}',
  'log.moneyLoss': '−{n}: {reason}',
  'log.guardShot': 'Охрана {site, case, gen} бьёт по {target, case, dat}, попаданий {hits} из {rounds}',
  'log.discovered': 'Вы нашли {site, case, acc}',
  'log.partDisabled': 'У {who, case, gen} {part, case, nom} {part, gender, m {выведен} f {выведена} n {выведено} pl {выведены}} из строя',
  'log.breakdown': '{part} {part, gender, m {сломался} f {сломалась} n {сломалось} pl {сломались}}',
  'log.townPatch': 'Вы латаете грузовик ломом.',
  'log.scrapPatch': 'Вы латаете машину ломом, и она снова трогается с места.',
  'log.scrapPatchFuel': 'Вы латаете машину ломом, и она снова трогается с места. Горожане отдали вам {liters} л топлива.',
  'log.npcKnockout': '{who} {who, gender, m {потерял} f {потеряла} n {потеряло} pl {потеряли}} сознание',
  'log.npcWake': '{who} приходит в себя',
  'log.destroyed': '{who} {who, gender, m {уничтожен} f {уничтожена} n {уничтожено} pl {уничтожены}}',
  'log.hostile': '{who} теперь враждует с вами',
  'log.death': 'Вы погибли.',
  'log.knockout': 'Вы теряете сознание.',
  'log.wake': 'Вы приходите в себя.',
  'contract.haul': 'Доставить {good, case, acc} ×{n} {site, case, to}',
  'contract.rushHaul': 'Срочно: доставить {good, case, acc} ×{n} {site, case, to}',
  'contract.fetch': 'Привезти {part, case, acc} {site, case, to}: {part, gender, m {исправный} f {исправную} n {исправное} pl {исправные}}, {n, plural, one {не больше # капремонта} few {не больше # капремонтов} many {не больше # капремонтов} other {не больше # капремонта}}',
  'contract.bounty': '{target, gender, m {Любой} f {Любая} n {Любое} pl {Любые}} {target, case, nom}: вырубить или разбить',
  'contract.bountyAt': '{target, gender, m {Любой} f {Любая} n {Любое} pl {Любые}} {target, case, nom}: вырубить или разбить, награда {site, case, at}',
  'contract.bountyMet': '{target} {target, gender, m {повержен} f {повержена} n {повержено} pl {повержены}}, награда {site, case, at}',
  'contract.ready': 'Готово',
  'contract.window': '{h} ч',
  'contract.due': 'срок: {when}',
  'clock.day': 'День {day}',
  'clock.full': 'День {day}, {time}',
  'goods.good': 'Товар',
  'goods.theirs': 'У них',
  'goods.buy': 'Купить',
  'goods.sell': 'Продать',
  'goods.held': 'Есть',
  'goods.profit': 'Прибыль',
  'goods.profitTitle': 'За единицу: цена продажи здесь минус средняя цена закупки. Найденный и перевезённый товар считается по обычной стоимости.',
  'goods.unknown': '?',
  'goods.even': '0',
  'goods.gain': '+{n}',
  'goods.loss': '−{n}',
  'goods.noCost': 'Цена закупки неизвестна',
  'goods.avgCost': 'Средняя цена {cost}',
  'goods.buyLot': 'Купить {n} за {total}',
  'goods.sellLot': 'Продать все {n} за {total}',
  'log.stamped': '{time} {line}',
  'log.title': 'Журнал',
  'log.panel': 'Журнал событий',
  'log.expand': 'Развернуть журнал',
  'log.shrink': 'Свернуть журнал',
  // Why a driver took up or ended a goal.
  'goal.arrived': 'Прибыл',
  'goal.avoidCostlyFight': 'Избежать дорогой драки',
  'goal.bringAid': 'Привезти топливо и припасы',
  'goal.buyCargo': 'Купить выгодный груз',
  'goal.cannotAffordCargo': 'Груз не по карману',
  'goal.cannotDrive': 'Не может ехать',
  'goal.cargoFullLoad': 'Некуда грузить',
  'goal.cargoFullLoot': 'Добыча не влезает',
  'goal.cargoFullSalvage': 'Лом не влезает',
  'goal.choseNew': 'Выбрал другое дело',
  'goal.collectSalvage': 'Собрать замеченный лом',
  'goal.combatStopsLooting': 'Бой мешает грабежу',
  'goal.combatStopsRepair': 'Бой мешает ремонту',
  'goal.combatStopsSearch': 'Бой мешает поиску',
  'goal.contactGone': 'Цель пропала',
  'goal.damagedThreatened': 'Повреждён и под угрозой',
  'goal.defendLoot': 'Защитить свою добычу',
  'goal.deliverCargo': 'Доставить купленный груз',
  'goal.droppedTow': 'Бросил буксир',
  'goal.escapeAttacker': 'Уйти от нападающего',
  'goal.escapeThreat': 'Уйти от угрозы',
  'goal.explore': 'Разведка',
  'goal.exploredSpot': 'Осмотрел место',
  'goal.fightBack': 'Дать отпор',
  'goal.fightHostile': 'Атаковать врага в поле зрения',
  'goal.finishedRepairs': 'Закончил ремонт в поле',
  'goal.finishedService': 'Прошёл обслуживание',
  'goal.fitAgain': 'Снова в строю',
  'goal.followLeader': 'Следовать за ведущим',
  'goal.foundNothing': 'На месте цели пусто',
  'goal.heardHostile': 'Слышал врага за пределами видимости',
  'goal.helpStranded': 'Помочь застрявшему грузовику',
  'goal.homeToLieUp': 'Домой, отсидеться',
  'goal.idle': 'Без дела',
  'goal.inCombat': 'В бою',
  'goal.keepWord': 'Держит слово',
  'goal.leftLeader': 'Отстал от ведущего',
  'goal.legacy': 'Занят',
  'goal.lieUp': 'Отсидеться до нового снаряжения',
  'goal.loadCargo': 'Загрузиться на месте',
  'goal.lootClaimed': 'Добычу уже застолбили',
  'goal.lootDowned': 'Ограбить подбитый грузовик',
  'goal.lootGone': 'Добыча пропала',
  'goal.lootOnTheWay': 'Собрать лом по пути',
  'goal.lootRobbed': 'Обчистить ограбленный грузовик',
  'goal.lootTaken': 'Там уже кто-то грабит',
  'goal.lostSalvage': 'Потерял лом из виду',
  'goal.lostTarget': 'Потерял цель',
  'goal.lowFuel': 'Мало топлива',
  'goal.lowSupplies': 'Мало припасов',
  'goal.meetingOff': 'Встреча отменена',
  'goal.needsRepairs': 'Нужен ремонт',
  'goal.noExplorePoint': 'Некуда ехать на разведку',
  'goal.noGun': 'Нечем воевать',
  'goal.noHostile': 'Врагов не видно',
  'goal.noProgress': 'Слишком долго без толку',
  'goal.nothingToDo': 'Нечего делать',
  'goal.nothingToLoot': 'Грабить больше нечего',
  'goal.nowhereToRun': 'Дальше бежать некуда',
  'goal.patchOff': 'Ремонт отменён',
  'goal.patchParts': 'Подлатать повреждённые детали',
  'goal.patchTruck': 'Подлатать грузовик',
  'goal.patrolCamp': 'Патрулировать дороги у лагеря',
  'goal.patrolTown': 'Патрулировать дороги у города',
  'goal.patrolledRoad': 'Проехал дозором',
  'goal.pickUpAid': 'Забрать топливо и припасы',
  'goal.prowl': 'Рыскать по дорогам в поисках обломков',
  'goal.prowledRoad': 'Прочесал дорогу',
  'goal.pullOver': 'Остановиться для торговли',
  'goal.raid': 'Искать добычу в охотничьих угодьях',
  'goal.reachedGround': 'Добрался до угодий',
  'goal.refitted': 'Переоснастился дома',
  'goal.refuseThreat': 'Не поддаваться на угрозы',
  'goal.retreatHome': 'Отступить домой после поражения',
  'goal.robCargo': 'Отнять груз',
  'goal.salvageExhausted': 'Лом кончился',
  'goal.salvageGone': 'Лома больше нет',
  'goal.searchSite': 'Обшарить известную свалку',
  'goal.searchSpot': 'Обшарить место с добычей',
  'goal.sellCargo': 'Продать груз',
  'goal.soldCargo': 'Продал груз',
  'goal.spottedHeard': 'Заметил грузовик, который слышал',
  'goal.strandedRobbery': 'Застрял, бросил грабёж',
  'goal.takeClaimedLoot': 'Забрать застолбленную добычу',
  'goal.takeHandedCargo': 'Забрать отданный груз',
  'goal.towNotNeeded': 'Буксир больше не нужен',
  'goal.towOff': 'Буксировка отменена',
  'goal.towOfferLeft': 'Вы уехали, не дождавшись буксира',
  'goal.towPlayer': 'Тащить вас в город',
  'goal.towStranded': 'Тащить застрявший грузовик',
  'goal.towUnanswered': 'Не дозвался до грузовика',
  'goal.towedPlayer': 'Дотащил вас до города',
  'goal.towedStranded': 'Дотащил застрявший грузовик',
  'goal.tripToSite': 'Съездить в другое место',
  'goal.truckGotAway': 'Грузовик ушёл',
  'goal.unfitToHunt': 'Не годится для охоты',
  'goal.waitPatch': 'Ждать ремонта',
  'goal.waitTow': 'Ждать буксира',
  'goal.waitTowAnswer': 'Ждать ответа на предложение буксира',
  'goal.warnedOff': 'Отогнан от добычи',
  'goal.holdFull': 'Кузов полон',
  'goal.lootWontFit': 'Добыча не поместится',
  'goal.takeSpilledCargo': 'Забрать просыпанный груз',
  'goal.salvageOutOfReach': 'Лом не достать',
  'goal.leftPost': 'Покинул пост',
  'goal.cannotWearDown': 'Не удаётся измотать цель',
  'goal.fightOverLoot': 'Драться за добычу',
  'goal.looterWontLeave': 'Мародёр не уходит',
  'goal.warningUnanswered': 'Нет ответа на предупреждение',
  'goal.defendPromisedLoot': 'Защитить обещанную добычу',
  'goal.keepLoot': 'Удержать свою добычу',
  'goal.searchOldHulks': 'Обыскать старые корпуса танков',
  'goal.searchOldRuin': 'Обыскать старые руины',
  'goal.cornered': 'Загнан в угол',
  'goal.defeated': 'Разбит',
  'goal.watchedRoad': 'Осмотрел дорогу',
  'goal.ranFromIt': 'Сбежал от него',
  'goal.avoidRanFrom': 'Избегать грузовика, от которого бежал',
  'goal.breakOffFight': 'Выйти из проигрышного боя',
  'note.engineHot': 'Двигатель перегревается.',
  'note.engineOverheat': 'Двигатель перегрелся, прочность −{hp}.',
  'opening.stranded': 'Вы застряли в незнакомых краях. Не лучший момент в вашей жизни.',
  'note.overdriveCutOut': 'Форсаж отключился: двигатель слишком изношен.',
  'note.engineDoused': 'Двигатель залит водой, припасы −{supplies}.',
  'note.outOfSupplies': 'Припасы кончились, здоровье −{health}.',
  'note.noRoomFuel': 'Нет места для топлива, топливо −{fuel}.',
  'note.noRoomSupplies': 'Нет места для припасов, припасы −{supplies}.',
  'note.tankLeak': 'Бак течёт, топливо −{fuel}.',
  'note.filledSupplies': 'Припасы пополнены {site, case, at}',
  'note.hazard': 'От светящегося ядра тянет тошнотворным жаром. По коже бегут мурашки, руль дрожит в руках.',
  'note.spawnBlocked': 'Нет места для появления {template, case, gen}',
  'money.contract': 'контракт',
  'money.failedHaul': 'проваленный контракт на перевозку',
  'money.towing': 'буксировка {vehicle, case, gen}',
  'refusal.noFit': 'Сюда не влезает',
  'refusal.inTheWay': 'Что-то мешает',
  'refusal.armorOnly': 'По бокам ставится только броня',
  'refusal.badLayout': '{cause}. Предметы выпадут из сетки или наложатся друг на друга.',
  'refusal.itemGone': 'Этого предмета уже нет',
  'refusal.refitRunning': 'Сначала закончите переоснащение',
  'refusal.twoInTheWay': 'Мешает больше одного предмета',
  'refusal.refitItemMoved': 'Предмет для переоснащения сдвинулся или пропал',
  'refusal.builtInFixed': 'Встроенные детали не двигаются',
  'refusal.salvageOutOfReach': 'Лом уже не достать',
  'refusal.salvagePartGone': 'Этой детали здесь больше нет',
  'refusal.builtInStays': 'Встроенные детали остаются на грузовике',
  'refusal.emptyRackFirst': 'Сначала освободите этот багажник',
  'refusal.truckOutOfReach': 'Грузовик вне досягаемости',
  'refusal.truckPartGone': 'Этой детали на грузовике больше нет',
  'refusal.looting.here': 'Здесь уже грабит {by, case, nom}',
  'refusal.looting.wreck': 'Эти обломки уже грабит {by, case, nom}',
  'refusal.looting.truck': 'Этот грузовик уже грабит {by, case, nom}',
  'refusal.needsSpotter': 'Чтобы метить грузовики, нужен навык «Наводчик»',
  'refusal.cannotAct': 'Сейчас нельзя действовать',
  'refusal.noTruck': 'Некого пометить',
  'refusal.unseen': 'Вы не видите этот грузовик',
  'refusal.notActive.dead': 'Вы мертвы',
  'refusal.notActive.knockedOut': 'Вы без сознания',
  'refusal.topRank': '{skill}: уже высший ранг',
  'refusal.needsXp': 'Нужно {cost} опыта, у вас {have}',
  'refusal.failed': 'Не получилось.',
  'refusal.noMoney': 'Не хватает денег',
  'refusal.noCargoRoom': 'Не хватает места в кузове',
  'refusal.theyHaveNoRoom': 'У них нет места',
  'refusal.noSupplyRoom': 'Столько не поместится',
  'refusal.inCombat': 'Не во время боя',
  'refusal.stopFirst': 'Сначала остановите грузовик',
  'refusal.utilityPassive': 'Приказы для {part, case, gen} не нужны',
  'refusal.utilityOrder.point': 'Для {part, case, gen} нужна точка цели',
  'refusal.utilityOrder.self': 'Для {part, case, gen} цель не нужна, только запуск',
  'refusal.utilityBlocked': '{part}: {reason}',
  'unit.part': '{n, plural, one {# деталь} few {# детали} many {# деталей} other {# детали}}',
  'vehicle.yours': noun('m', 'ваш грузовик', 'вашего грузовика', 'вашему грузовику', 'ваш грузовик', 'вашим грузовиком', 'вашем грузовике'),
  'vehicle.npc': '{profession} {driver}',
};
