import type { NAMES as EN } from '../en/names';
import { noun, type Translation } from '../msg';

export const NAMES: Translation<typeof EN> = {
  'part.mg': noun('f', 'пулемётная турель', 'пулемётной турели', 'пулемётной турели', 'пулемётную турель', 'пулемётной турелью', 'пулемётной турели'),
  'part.shotgun': 'Дробовик',
  'part.longRifle': 'Длинная винтовка',
  'part.flamer': 'Огнемёт',
  'part.pneumobolter': 'Пневмоболтер',
  'part.slugCannon': 'Жаканомёт',
  'part.heavyMg': 'Тяжёлый пулемёт',
  'part.cannon': 'Курсовая пушка',
  'part.amRifle': 'Крупнокалиберная винтовка',
  'part.autocannon': 'Автопушка',
  'part.recoilless': 'Безоткатное орудие',
  'part.battleRifle': 'Боевая винтовка',
  'part.gatling': 'Пулемёт Гатлинга',
  'part.rocketRack': 'Ракетная установка',
  'part.sniperCannon': 'Снайперская пушка',
  'part.grenadeLauncher': 'Гранатомёт',
  'part.tankGun': 'Танковое орудие',
  'part.flechette': 'Флешеттомёт',
  'part.stockEngine': 'Штатный двигатель',
  'part.tunedEngine': 'Форсированный V8',
  'part.flatFour': 'Лёгкий оппозитный',
  'part.workhorseDiesel': 'Рабочий дизель',
  'part.racingV6': 'Гоночный V6',
  'part.heavyDiesel': 'Тяжёлый дизель',
  'part.turbine': 'Турбина',
  'part.plates': noun('pl', 'стальные плиты', 'стальных плит', 'стальным плитам', 'стальные плиты', 'стальными плитами', 'стальных плитах'),
  'part.cage': 'Арматурная клетка',
  'part.ram': 'Таранный брус',
  'part.scrapPanels': 'Панели из лома',
  'part.ceramicPlates': 'Керамические плиты',
  'part.spacedArmor': 'Разнесённая броня',
  'part.reinforcedCage': 'Усиленная клетка',
  'part.plowRam': 'Таран-отвал',
  'part.steelPlate': 'Стальная плита',
  'part.scrapSheet': 'Лист из лома',
  'part.ceramicTile': 'Керамическая плитка',
  'part.rack': 'Багажник на крышу',
  'part.trailerBox': 'Грузовой короб',
  'part.panniers': 'Боковые корзины',
  'part.flatbed': 'Удлинённая платформа',
  'part.lightFrame': 'Лёгкая грузовая рама',
  'part.enclosedFrame': 'Закрытая грузовая рама',
  'part.heavyFrame': 'Тяжёлая грузовая рама',
  'part.jerrycans': 'Стойка для канистр',
  'part.supplyLocker': 'Ящик для припасов',
  'part.cab': 'Сиденье водителя',
  'part.cabPickup': 'Кабина',
  'part.cabHardtop': 'Закрытая кабина',
  'part.transmission': 'Коробка передач',
  'part.transmissionMid': 'Грузовая коробка передач',
  'part.transmissionHeavy': 'Тяжёлая коробка передач',
  'part.wheel': 'Колесо',
  'part.wheelMid': 'Грузовое колесо',
  'part.wheelHeavy': 'Тяжёлое колесо',
  'part.tank': 'Малый топливный бак',
  'part.tankLong': 'Топливный бак',
  'part.tankMid': 'Грузовой топливный бак',
  'part.tankHeavy': 'Бронированный топливный бак',
  'part.sprout': 'Росток',
  'part.caltrops': 'Шипы-чеснок',
  'part.oilSpiller': 'Маслоразлив',
  'part.patcherCrane': 'Ремонтный кран',
  'part.smokeMortar': 'Дымовой миномёт',
  'part.flareCannon': 'Сигнальная пушка',
  'part.scrapersKnife': 'Нож скрейпера',
  'part.emitter': 'Излучатель',
  'part.harpoon': 'Гарпун',
  'part.claymoreRam': 'Таран «Клеймор»',
  'part.scanner': 'Радиосканер',
  'chassis.scout': 'Пикап-разведчик',
  'chassis.hauler': 'Грузовоз',
  'chassis.buggy': 'Багги',
  'chassis.wagon': 'Боевой фургон',
  'chassis.courier': 'Курьерский',
  'chassis.van': 'Фургон',
  'chassis.longbed': 'Длиннобазный грузовик',
  'chassis.carrier': 'Бронетранспортёр',
  'chassis.tractor': 'Тяжёлый тягач',
  'chassis.jeep': 'Джип',
  'chassis.convertible': 'Кабриолет',
  'chassis.bus': 'Автобус',
  'chassis.loader': 'Колёсный погрузчик',
  'chassis.niva': 'Нива',
  'chassis.bukhanka': 'Буханка',
  'chassis.lincoln': 'Линкольн',
  'good.scrap': 'Металлолом',
  'good.scrap.lower': 'металлолом',
  'good.scrap.subject': 'металлолом',
  'good.scrap.short': 'Лом',
  'good.salt': 'Соль',
  'good.salt.lower': 'соль',
  'good.salt.subject': 'соль',
  'good.salt.short': 'Соль',
  'good.meds': 'Медикаменты',
  'good.meds.lower': 'медикаменты',
  'good.meds.subject': 'медикаменты',
  'good.meds.short': 'Медик',
  'good.grain': 'Зерно',
  'good.grain.lower': 'зерно',
  'good.grain.subject': 'зерно',
  'good.grain.short': 'Зерно',
  'good.textiles': 'Ткани',
  'good.textiles.lower': 'ткани',
  'good.textiles.subject': 'ткани',
  'good.textiles.short': 'Ткани',
  'good.tools': 'Станки',
  'good.tools.lower': 'станки',
  'good.tools.subject': 'станки',
  'good.tools.short': 'Станк',
  'good.batteries': 'Аккумуляторы',
  'good.batteries.lower': 'аккумуляторы',
  'good.batteries.subject': 'аккумуляторы',
  'good.batteries.short': 'Аккум',
  'good.electronics': 'Электроника',
  'good.electronics.lower': 'электроника',
  'good.electronics.subject': 'электроника',
  'good.electronics.short': 'Элект',
  'good.parts': 'Запчасти',
  'good.parts.lower': 'запчасти',
  'good.parts.subject': 'запчасти',
  'good.parts.short': 'Запч',
  'good.fuelDrums': 'Бочки с топливом',
  'good.fuelDrums.lower': 'бочки с топливом',
  'good.fuelDrums.subject': 'бочки с топливом',
  'good.fuelDrums.short': 'Бочки',
  'good.water': 'Вода',
  'good.water.lower': 'вода',
  'good.water.subject': 'вода',
  'good.water.short': 'Вода',
  'site.bowl': 'Чаша',
  'site.nose': 'Нос',
  'site.orchard': 'Старый сад',
  'site.dustwell': 'Пыльный колодец',
  'site.granary': 'Элеватор',
  'site.burnt-convoy': 'Сгоревший конвой',
  'site.podfield': 'Капсульное поле',
  'site.canyon-bridge': 'Мост через каньон',
  'site.glass-flats': 'Стеклянная равнина',
  'site.green-pit': 'Зелёная яма',
  'site.south-lock': 'Южный шлюз',
  'site.ridge-wrecks': 'Обломки на хребте',
  'site.pump-station': 'Насосная станция',
  'site.fallen-sun': 'Павшее солнце',
  'site.salvage-yard': 'Свалка',
  'site.broken-wing': 'Сломанное крыло',
  'site.scrapjaw': 'Ржавая Челюсть',
  'site.kiln': 'Обжиг',
  'terrain.road': 'Дорога',
  'terrain.hardpan': 'Твёрдый грунт',
  'terrain.sand': 'Рыхлый песок',
  'terrain.scrub': 'Кустарник',
  'terrain.scree': 'Осыпь',
  'terrain.mud': 'Грязь',
  'terrain.gravel': 'Гравий',
  'terrain.saltCrust': 'Солончак',
  'terrain.asphalt': 'Растрескавшийся асфальт',
  'terrain.ash': 'Пепел',
  'terrain.field': 'Мёртвое поле',
  'terrain.dirtyWater': 'Грязная вода',
  'terrain.toxic': 'Ядовитая лужа',
  'terrain.track': 'Грунтовка',
  'terrain.canal': 'Оросительный канал',
  'terrain.concrete': 'Растрескавшийся бетон',
  'terrain.glass': 'Оплавленное стекло',
  'npc.buggy': 'Рейдер-разведчик',
  'npc.buggy.profession': 'Рейдер',
  'npc.gunwagon': 'Боевой фургон',
  'npc.gunwagon.profession': 'Рейдер',
  'npc.trader': 'Торговый караван',
  'npc.trader.profession': noun('m', 'торговец', 'торговца', 'торговцу', 'торговца', 'торговцем', 'торговце'),
  'npc.scavenger': 'Мусорщик',
  'npc.scavenger.profession': 'Мусорщик',
  'npc.bowlFarmer': 'Патруль Чаши',
  'npc.bowlFarmer.profession': 'Фермер Чаши',
  'npc.noseArmy': 'Патруль Носа',
  'npc.noseArmy.profession': 'Солдат Носа',
  'npc.courier': 'Курьер',
  'npc.courier.profession': 'Курьер',
  'npc.roamer': 'Бродяга',
  'npc.roamer.profession': 'Бродяга',
  'npc.vulture': 'Стервятник',
  'npc.vulture.profession': 'Стервятник',
  'npc.convoy': 'Конвой снабжения',
  'npc.convoy.profession': 'Водитель конвоя',
  'npc.convoyGuard': 'Охрана конвоя',
  'npc.convoyGuard.profession': 'Охранник конвоя',
  'npc.merc': 'Наёмник',
  'npc.merc.profession': 'Наёмник',
  'trait.trader': 'торговец',
  'trait.scavenger': 'мусорщик',
  'trait.raider': 'рейдер',
  'trait.scumbag': 'подонок',
  'trait.coward': 'трус',
  'trait.lawman': 'законник',
  'trait.courier': 'курьер',
  'trait.roamer': 'бродяга',
  'trait.vulture': 'стервятник',
  'trait.supplier': 'снабженец',
  'trait.guard': 'охранник',
  'trait.merc': 'наёмник',
  'trait.brave': 'смельчак',
  'faction.player': 'игрок',
  'faction.raiders': 'рейдеры',
  'faction.traders': 'торговцы',
  'faction.scavengers': 'мусорщики',
  'faction.bowl': 'Чаша',
  'faction.nose': 'Нос',
  'faction.couriers': 'курьеры',
  'faction.roamers': 'бродяги',
  'faction.vultures': 'стервятники',
  'faction.convoys': 'конвои',
  'faction.mercs': 'наёмники',
  'skill.driving': 'Вождение',
  'skill.driving.grows': 'бездорожье, тараны, побеги',
  'skill.perception': 'Восприятие',
  'skill.perception.grows': 'попадания, обнаружения, открытия',
  'skill.machining': 'Механика',
  'skill.machining.grows': 'полевые работы, починки, обыски',
  'skill.toughness': 'Стойкость',
  'skill.toughness.grows': 'жара, полученный урон, нокауты',
  'skill.social': 'Общение',
  'skill.social.grows': 'торговая прибыль, сделки, контракты, рация',
  'perk.rammer': 'Таранщик',
  'perk.rammer.rule': 'Таран глушит двигатель вражеского грузовика на один ход.',
  'perk.coldRunning': 'Тихий ход',
  'perk.coldRunning.rule': 'Ниже половины скорости ваш двигатель слышно только в пределах видимости.',
  'perk.steadyAim': 'Твёрдая рука',
  'perk.steadyAim.rule': 'Ваша скорость не добавляет разброса выстрелам.',
  'perk.dustScreen': 'Пылевая завеса',
  'perk.dustScreen.rule': 'На полной скорости по пыльной земле ваша пыль закрывает обзор, как холм.',
  'perk.readDriver': 'Видеть насквозь',
  'perk.readDriver.rule': 'Вы видите черты других водителей.',
  'perk.spotter': 'Наводчик',
  'perk.spotter.rule': 'Пометьте замеченный грузовик, и вы будете следить за ним сутки.',
  'perk.cargoEye': 'Намётанный глаз',
  'perk.cargoEye.rule': 'Вы видите товары и запчасти в любом замеченном грузовике.',
  'perk.nightEyes': 'Ночное зрение',
  'perk.nightEyes.rule': 'Ночь не сокращает ваш обзор вдвое.',
  'perk.welder': 'Сварщик',
  'perk.welder.rule': 'Полевая работа превращает 3 металлолома в лист брони из лома.',
  'perk.cannibal': 'Разборщик',
  'perk.cannibal.rule': 'Снять деталь с обломков или подбитого грузовика можно за один ход.',
  'perk.rebuild': 'Восстановление',
  'perk.rebuild.rule': 'Городской гараж может восстановить негодную деталь до последней ступени износа, один раз на деталь.',
  'perk.roadMechanic': 'Дорожный механик',
  'perk.roadMechanic.rule': 'Водители платят вдвое за ваш ремонт.',
  'perk.desertRat': 'Пустынная крыса',
  'perk.desertRat.rule': 'Полуденное солнце греет ваш двигатель, как утреннее.',
  'perk.stormRider': 'Штормовой гонщик',
  'perk.stormRider.rule': 'Пыльные бури не мешают вашему обзору и прицелу.',
  'perk.fightThrough': 'Через силу',
  'perk.fightThrough.rule': 'Разбитая кабина или попадание в кабину ниже половины прочности не вырубают вас, пока здоровье выше половины.',
  'perk.longHaul': 'Дальнобой',
  'perk.longHaul.rule': 'Вы лечитесь в пути, а не только на стоянке.',
  'perk.marketEars': 'Рыночный слух',
  'perk.marketEars.rule': 'Торговец по рации называет цены в последнем городе, откуда уехал, — какими они были тогда.',
  'perk.rumorMill': 'Сарафанное радио',
  'perk.rumorMill.rule': 'Водитель по рации отмечает обломки или место, мимо которых проехал.',
  'perk.paidTruce': 'Купленный мир',
  'perk.paidTruce.rule': 'Можно заплатить враждебному водителю, чтобы он прекратил вражду с вами.',
  'perk.bountyTalk': 'Сговор за награду',
  'perk.bountyTalk.rule': 'Рейдер, сдавшийся вам, засчитывается в контрактах на награду.',
};
