import type { SCREENS as EN } from '../en/screens';
import type { Translation } from '../msg';

export const SCREENS: Translation<typeof EN> = {
  'menu.save': 'Сохранить',
  'menu.load': 'Загрузить',
  'menu.newGame': 'Новая игра',
  'menu.loadSave': 'Загрузить сохранение',
  'menu.close': 'Закрыть',
  'boot.loading': 'Загрузка',
  'boot.code': 'Загружаем игру',
  'boot.map': 'Читаем карту',
  'boot.physics': 'Запускаем физику',
  'boot.models': 'Загружаем модели',
  'boot.sounds': 'Загружаем звуки',
  'boot.loadSave': 'Загружаем сохранение',
  'boot.newGame': 'Начинаем новую игру',
  'boot.ground': 'Рисуем землю',
  'boot.scene': 'Собираем сцену',
  'boot.frame': 'Рисуем первый кадр',
  'boot.waiting': 'ждёт',
  'boot.running': '...',
  'boot.done': 'готово',
  'boot.failed': 'сбой',
  'boot.counted': '{label} ({done} из {total})',
  'boot.stepFailed': '{label}: сбой',
  'boot.failedToLoad': 'Игра не загрузилась. Проверьте подключение и перезагрузите страницу.',
  'save.slot.auto': 'Автосохранение',
  'save.slot.day': 'Начало дня',
  'save.slot.manual': 'Ячейка {n}',
  'save.damaged': 'Старое или повреждённое сохранение',
  'save.savedTo': 'Сохранено: {slot}',
  'save.savedAt': '{when} ({real})',
  'save.none': 'Сохранений пока нет',
  'save.empty': 'Пусто',
  'save.confirmLoad': 'Загрузить это сохранение? Всё, что было после него, пропадёт.',
  'save.confirmNew': 'Начать новую игру? Автосохранения удалятся, ячейки сохранений останутся.',
  'save.needsMigrating': 'Сохранение нужно перенести',
  'save.migrateExplain': 'Это обновление изменило мир. Перенос сохранит умения, навыки, деньги, грузовик, детали и груз и переместит вас в город. Остальной мир начнётся заново.',
  'save.migrate': 'Перенести сохранение',
  'save.unreadable': 'Сохранение не читается',
  'save.migrated': 'Сохранение перенесено',
  'save.allCarried': 'Всё перенесено',
  'save.driveOn': 'В путь',
  'save.sold': 'Продано: {good} ×{n} за {money}',
  'save.toGarage': 'Перенесено в гараж: {parts}',
  'save.lost': 'Утеряно, этого больше нет в игре: {ids}',
  'save.held': 'Не сохранено: после последнего удачного хода произошла ошибка.',
  'save.turnFailed': 'Ход не удался и не был сыгран. Игра не сохранена.',
  'save.error.unreadable': 'Сохранение не читается',
  'save.error.otherMap': 'Сохранение сделано на другой карте',
  'save.error.bakedProps': 'В сохранении есть объекты карты, которые берутся из файла карты',
  'save.error.brokenProp': 'В сохранении есть сломанный объект, которого нет среди разрушаемых объектов карты',
  'save.error.invalidWorld': 'Сохранённый мир повреждён',
  'save.error.invalidSave': 'Сохранение повреждено',
  'save.error.incompatible': 'Формат сохранения {major}.{minor} от несовместимой версии игры. Начните новую игру.',
  'save.error.newer': 'Формат сохранения {major}.{minor} от более новой версии игры',
  'save.error.notMigrated': 'Сохранение формата {major}.{minor} не удалось перенести',
  'save.error.noFormat': 'У сохранения нет версии формата',
  'save.error.badExplored': 'Повреждена разведанная часть карты',
  'save.error.badOldSpots': 'В сохранении сломан набор старых мест с добычей',
  'save.error.badQuests': 'В сохранении состояние заданий, которого эта версия не знает',
  'save.error.badSetup': 'В сохранении неверные настройки мира',
  'save.failed': 'Игру не удалось сохранить.',
  'death.title': 'Вы погибли',
  'death.epitaph': 'Жизнь великого машинера оборвалась',
  'character.close': 'Закрыть [C]',
  'character.title': 'Персонаж',
  'character.health': 'Здоровье',
  'character.knockoutsTitle': 'Нокауты',
  'character.knockouts': '{n, plural, one {# нокаут} few {# нокаута} many {# нокаутов} other {# нокаута}}',
  'character.xpTitle': 'Опыт за дела, его тратят на ранги умений',
  'character.xp': 'Можно потратить {n} опыта',
  'character.grows': 'Опыт дают: {what}',
  'character.rankOf': 'Ранг {rank} из {max}',
  'character.rank': 'Ранг {rank}',
  'character.today': 'Получено сегодня',
  'character.todayXp': '{n} / {cap} опыта',
  'character.max': 'макс.',
  'character.spendTitle': '{skill}, ранг {rank}: потратить {cost} опыта',
  'character.buy': 'Купить ранг {rank} за {cost} опыта',
  'character.locked': 'Ранг {rank}: {a} или {b}',
  'character.pick': 'Навык ранга {rank}: выберите один',
  'sound.music': 'Музыка',
  'sound.sfx': 'Эффекты',
  'sound.ambient': 'Ветер',
  'sound.ui': 'Интерфейс',
  'sound.next': 'Следующий трек',
  'sound.volume': 'Громкость: {bus}',
  'sound.percent': '{n}%',
  'sound.on': 'Звук',
  'sound.mute': 'Тихо',
  'sound.unmuteTitle': 'Включить звук [M]',
  'sound.muteTitle': 'Выключить звук [M]',
  'crash.title': 'Игра упала',
  'webgl.title': 'Road Machiners нужен WebGL',
  'webgl.intro': 'Браузер не смог запустить 3D-графику. Попробуйте одно из этого:',
  'webgl.acceleration': '• Включите аппаратное ускорение в настройках браузера.',
  'webgl.driver': '• Обновите драйвер видеокарты.',
  'webgl.browser': '• Откройте игру в другом браузере.',
  'webgl.firefox': '• В Firefox о состоянии WebGL расскажет about:support.',
  'webgl.saves': 'Ваши сохранения остаются в этом браузере. Игра загрузит их, когда WebGL заработает.',
  'crash.hint': 'Перезагрузите страницу, чтобы начать заново.',
  'language.label': 'Язык',
  'language.en': 'English',
  'language.ru': 'Русский',
  'hud.stopToUse': 'Остановитесь, чтобы использовать',
  'hud.combatBlocked': 'Нельзя в бою, {n, plural, one {остался # ход} few {осталось # хода} many {осталось # ходов} other {осталось # хода}}',
  'hud.clockTitle': 'День и время',
  'hud.clockLabel': 'Время: {when}',
  'hud.recenter': 'К грузовику (F)',
  'hud.guideTitle': 'Управление в пути и в бою',
  'hud.guideMark': '?',
  'hud.guide.drive': 'Клик по земле: ехать туда по дороге. Shift+клик: остановиться там.',
  'hud.guide.space': 'Пробел: ехать или пауза. Удерживать Пробел: ускорить. Клик по своему грузовику: тормоз.',
  'hud.guide.manual': 'R: ручное вождение, прямо к точке.',
  'hud.guide.pads': 'Клик по городу или месту: встать на его площадку. E на площадке: торговля, ремонт или добыча.',
  'hud.guide.radio': 'T: вызвать по рации осмотренный грузовик. 1-9: ответ. H: гудок.',
  'hud.guide.combat': 'Клик по грузовику: осмотреть его или навести выбранное оружие на корпус. 1-4: выбрать оружие. 0: всё. Q: автоогонь. X: показать оружие.',
  'hud.guide.keys': 'P: авторемонт. C: персонаж. I: инвентарь. Esc: закрыть.',
  'hud.guide.camera': 'WASD или правая кнопка: обзор. Колесо: масштаб. F: к грузовику. V: камера. M: звук.',
  'hud.feedbackTitle': 'Сообщить об ошибке или предложить идею',
  'hud.feedbackMark': '!',
  'hud.reportBug': 'Сообщить об ошибке',
  'hud.requestFeature': 'Предложить идею',
  'hud.camAuto': 'Камера: авто',
  'hud.camCentered': 'По центру',
  'hud.camTitle': 'Режим камеры: смотреть вперёд к точке приказа или держать грузовик в центре [V]',
  'hud.workLeft': '{label}, {n, plural, one {остался # ход} few {осталось # хода} many {осталось # ходов} other {осталось # хода}}',
  'hud.workProgress': '{label}: прогресс',
  'hud.actionKey': '[E] {label}',
  'hud.count': '{n}/{of}',
  'hud.knockedOut': 'Без сознания',
  'hud.underTow': 'На буксире',
  'hud.towsYou': '{who} {who, gender, m {буксирует} f {буксирует} n {буксирует} pl {буксируют}} вас до {town, case, gen}.',
  'hud.fee': 'Плата',
  'hud.towFee': 'Плата {fee} по прибытии.',
  'hud.unhitch': 'Отцепиться',
  'hud.stranded': 'Застряли',
  'hud.callingTow': 'Вызываем буксир.',
  'hud.beaconOn': 'Маяк вкл.',
  'hud.beaconOff': 'Маяк выкл.',
  'hud.beaconTitle': 'Вызвать буксир по рации.',
  'hud.contracts': 'Контракты',
  'hud.contractLine': '{what} — {due}',
  'hud.lightsOn': 'Фары',
  'hud.lightsOff': 'Выкл.',
  'hud.lightsTitle': 'Фары [L]',
  'hud.overdrive': 'Форсаж',
  'hud.normal': 'Обычный',
  'hud.overdriveTitle': 'Быстрее, но двигатель быстро греется [O]',
  'hud.douseTitle': 'Расход: {n, plural, one {# ящик} few {# ящика} many {# ящиков} other {# ящика}} [G]',
  'hud.douse': 'Остудить [G]',
  'hud.characterMarked': 'Есть опыт или навык на выбор [C]',
  'hud.character': 'Водитель и навыки [C]',
  'hud.characterKeyMarked': '! [C]',
  'hud.journalKey': '[J]',
  'hud.characterKey': '[C]',
  'hud.inventoryTitle': 'Инвентарь грузовика [I]',
  'hud.inventoryLabel': 'Открыть инвентарь грузовика',
  'hud.readout': '{label}: {value}',
  'hud.readoutWarning': '{label}: {value}, внимание',
  'hud.warned': '! {value}',
  'hud.manual': 'Вручную',
  'hud.route': 'Маршрут',
  'hud.manualTitle': 'Ручной режим едет прямо к точке, маршрут идёт по дорогам [R]',
  'hud.autoPatch': 'Ремонт',
  'hud.noPatch': 'Выкл.',
  'hud.autoPatchTitle': 'Латать повреждённые детали на стоянке [P]',
  'hud.hostile': '{faction}, враждебны',
  'hud.neutral': '{faction}, нейтральны',
  'hud.speed': 'Скорость {n} км/ч',
  'hud.aimHint': 'Кликните по детали, чтобы навести на неё выбранное оружие',
  'action.giveAid': 'Передать {goods} {truck, case, dat}',
  'action.takeAid': 'Забрать {goods} у {truck, case, gen}',
  'action.trade': 'Торговать с {truck, case, ins}',
  'action.enter': 'Въехать {site, case, to}',
  'action.lootTruck': 'Обобрать {truck, case, acc}',
  'action.refill': 'Пополнить припасы {site, case, at}',
  'action.noLoot': 'Добычи не осталось',
  'action.lootingIt': 'Его уже обирает {truck, case, nom}',
  'stock.search.pile': 'Обшарить кучу',
  'stock.search.wreck': 'Обшарить обломки',
  'stock.search.spot': 'Обшарить',
  'stock.search.site': 'Обшарить {site, case, acc}',
  'stock.loot.pile': 'Забрать из кучи',
  'stock.loot.wreck': 'Обобрать обломки',
  'stock.loot.spot': 'Забрать добычу',
  'stock.loot.site': 'Обобрать {site, case, acc}',
  'stock.empty.pile': 'Куча пуста',
  'stock.empty.wreck': 'Обломки обобраны дочиста',
  'stock.empty.spot': 'Обобрано дочиста',
  'stock.empty.site': '{site} {site, gender, m {обобран} f {обобрана} n {обобрано} pl {обобраны}} дочиста',
  'condition.broken': '{part} {part, gender, m {сломан} f {сломана} n {сломано} pl {сломаны}}',
  'condition.percent': '{part}: {pct}%',
  'weather.heatwave': 'Жара',
  'weather.overcast': 'Пасмурно',
  'weather.storm': 'Пыльная буря',
  'weather.stormNear': 'Рядом буря',
  'weather.clear': 'Ясно',
  'money.debt': 'Долг {n}',
  'money.amount': '{n}',
  'stranded.spareEngine': 'Нет рабочего двигателя. Поставьте запасной [I].',
  'stranded.noEngine': 'Нет рабочего двигателя.',
  'stranded.transmission': 'Коробка передач сломана.',
  'stranded.noFuel': 'Кончилось топливо.',
  'speed.pctZero': '0%',
  'speed.pctUp': '+{n}%',
  'speed.pctDown': '−{n}%',
  'speed.kphUp': '+{n} км/ч',
  'speed.kphDown': '−{n} км/ч',
  'speed.chassis': 'Шасси',
  'speed.engineWorn': 'Двигатель изношен',
  'speed.engine': 'Двигатель',
  'speed.load': 'Груз',
  'speed.wheels': '{n, plural, one {# колесо сломано} few {# колеса сломано} many {# колёс сломано} other {# колеса сломано}}',
  'speed.guns': 'Мощность на оружие',
  'speed.floor': 'Минимальная скорость',
  'speed.overdrive': 'Форсаж',
  'speed.transmission': 'Сломана коробка',
  'speed.limp.noEngine': 'Нет двигателя',
  'speed.limp.brokenEngine': 'Двигатель сломан',
  'speed.limp.stalled': 'Двигатель заглох',
  'speed.towing': 'Буксировка',
  'speed.line': '{label}: {effect}',
  'speed.base': 'Базовая',
  'speed.kph': '{n} км/ч',
  'speed.crawlValue': 'ползком {n} км/ч',
  'speed.crawl': 'ползком',
  'speed.lowFuelLabel': 'Мало топлива',
  'speed.lowFuelValue': 'макс. {n} км/ч',
  'speed.emptyTankLabel': 'Пустой бак',
  'power.noCostStalled': 'без потери скорости, пока заглох',
  'power.noneStalled': 'нет, пока заглох',
  'power.noCost': 'без потери скорости',
  'power.none': 'нет',
  'power.cost': '{pct} скорости',
  'power.costLong': '{pct} скорости, −{n} км/ч',
  'power.noEngine': 'Нет рабочего двигателя',
  'power.noEngineDetail': 'Нет рабочего двигателя: оружие не отнимает скорость.',
  'power.over': 'перебор на {n}',
  'power.spare': 'запас {n}',
  'power.detail': 'Оружие отбирает {draw} из {capacity} мощности, {balance}. Цена: {cost}.',
  'power.chip': '{draw} / {capacity} мощности, {cost}',
  'power.chipOver': '{draw} / {capacity} мощности, {balance}, {cost}',
  'readout.money': 'Деньги',
  'readout.fuel': 'Топливо',
  'readout.supplies': 'Припасы',
  'readout.driver': 'Водитель',
  'readout.heat': 'Жара',
  'readout.engine': 'Двигатель',
  'readout.weather': 'Погода',
  'readout.liters': '{n} / {max} л',
  'readout.ofMax': '{n} / {max}',
  'readout.engineHeat': 'Нагрев двигателя',
  'hud.tagHostile': 'враждебны',
  'hud.tagNeutral': 'нейтральны',
  'readout.litersShort': '{n} л',
  'readout.celsius': '{n} °C',
  'units.kg': '{n} кг',
  'ui.key': '[{key}]',
  'map.unknownSite': '???',
  'map.rumor': 'Обломки (слух)',
  'map.radio': '[T] Рация',
  'hint.waypoint': 'Кликните по земле, чтобы поставить точку пути.',
  'hint.drive': '[Пробел], чтобы ехать к точке пути.',
  'hint.autoStop': '[Пробел], чтобы остановить автоматический путь.',
  'hint.stop': 'Кликните по своему грузовику, чтобы остановиться.',
  'hint.stopAt': '[Shift]+клик ставит точку остановки.',
  'hint.manual': '[R], чтобы ехать вручную.',
  'hint.zones': 'Кликните по зоне, чтобы ехать: зелёная разгоняет, жёлтая держит скорость, красная тормозит.',
  'hint.aim': 'Выберите оружие и кликните по грузовику, чтобы навести на корпус.',
  'hint.honk': '[H], чтобы посигналить.',
  'hint.farewell': 'Вот и всё, удачи.',
  'hint.closeMark': '×',
  'hud.cycleKey': '[{key}]',
  'log.expandMark': '⤢',
  'radio.ghost': '{blocks}',
  'hud.prevMark': '‹',
  'hud.nextMark': '›',
  'block.disabled': 'выведено из строя',
  'block.cooldown': 'остывает',
  'block.empty': 'перезарядка',
  'block.range': 'вне досягаемости',
  'block.arc': 'вне сектора',
  'block.blocked': 'обзор закрыт своим грузовиком',
  'block.noTarget': 'не стрелять',
  'block.unseen': 'не видно',
  'block.covered': 'за укрытием',
  'block.talking': 'на связи',
  'block.out': 'водитель без сознания',
  'blockShort.disabled': 'сломано',
  'blockShort.cooldown': 'ждём',
  'blockShort.cooldownIn': 'ждём {n}',
  'blockShort.empty': 'заряд',
  'blockShort.emptyIn': 'заряд {n}',
  'blockShort.range': 'далеко',
  'blockShort.arc': 'сектор',
  'blockShort.blocked': 'закрыто',
  'blockShort.unseen': 'не видно',
  'blockShort.covered': 'укрыт',
  'blockShort.talking': 'рация',
  'blockShort.out': 'вырублен',
  'weapon.bodyShot': 'по корпусу',
  'weapon.readyIn': 'готово через {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'weapon.reloadingFor': 'перезарядка: {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'weapon.ammo': '{n}/{of}',
  'weapon.reloadingLeft': 'перезарядка, осталось {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'weapon.rounds': '{n}/{of} патронов',
  'weapon.ready': 'готово',
  'weapon.title': 'Оружие',
  'weapon.toggleTitle': 'Показать или скрыть оружие [X]',
  'weapon.hide': 'Скрыть [X]',
  'weapon.show': 'Показать [X]',
  'weapon.autoTitle': 'Автоогонь: оружие само стреляет по врагам [Q]',
  'weapon.auto': 'Автоогонь [Q]',
  'weapon.allTitle': 'Навести всё оружие следующим кликом [0]',
  'weapon.all': 'Всё [0]',
  'weapon.none': 'Оружие не установлено',
  'weapon.targetGone': 'цель недоступна',
  'weapon.noTarget': 'нет цели',
  'weapon.slotLabel': '{name}: {status}, {target}',
  'weapon.slotTitle': '{name}: {rounds} × {damage} урона, пробитие {pen}, дальность {range} м, выстрел раз в {cooldown, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}, {magazine} выстрелов, перезарядка {reload, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}. {status}, {target}',
  'weapon.holdTitle': 'Прекратить огонь: выключить автоогонь и сбросить цель этого оружия',
  'weapon.hold': 'Стоп',
  'weapon.reloadTitle': 'Перезарядка: сбросить магазин и снарядить заново за {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'weapon.reloadLabel': 'Перезарядить {name, case, acc}',
  'weapon.cutHint': 'Перерезать трос',
  'weapon.cutLabel': 'Перерезать трос: {name, case, acc}',
  'weapon.noLine': 'Трос не выпущен',
  'turn.autoTitle': 'Автоматический путь. Пробел или клик, чтобы остановить.',
  'turn.stopAuto': 'Остановить автоматический путь',
  'turn.auto': 'Авто',
  'turn.endTitle': 'Закончить ход [Пробел]. Удерживайте для ускорения.',
  'turn.inProgress': 'Идёт: {phase}',
  'turn.end': 'Закончить ход',
  'turn.running': '{phase}…',
  'turn.space': 'Пробел',
  'phase.moving': 'Движение',
  'phase.firing': 'Стрельба',
  'phase.results': 'Итоги',
  'hit.detail': '{pct}% попадают в точку, {m} м, цель видна шириной {wide} м, разброс оружия {deg}°',
  'hit.causeMore': ' +{deg}° {cause}',
  'hit.causeLess': ' −{deg}° {cause}',
  'hit.cause.range': 'дальность',
  'hit.cause.crossing': 'поперечное движение',
  'hit.cause.own': 'своя скорость',
  'hit.cause.recoil': 'отдача',
  'hit.cause.skill': 'восприятие',
  'hit.cause.weather': 'погода',
  'hit.cause.still': 'цель стоит',
  'hit.reason.far': 'далеко',
  'hit.reason.crossing': 'цель быстро идёт поперёк',
  'hit.reason.moving': 'вы в движении',
  'hit.reason.kick': 'отдача',
  'hit.reason.weather': 'плохая погода',
  'hit.reason.loose': 'разболтанное оружие',
  'hit.reason.covered': 'мешают детали',
  'hit.reason.parked': 'цель стоит: легко',
  'hit.reason.clear': 'чистый выстрел',
  'hit.label': '{name} {ammo}',
  'hit.chance': '{pct}%',
  'hit.slot': '[{n}] {gun}',
  'hit.noWeapons': 'Нет оружия',
  'hit.mine': 'Вы → цель',
  'hit.theirs': 'Цель → вы',
  'condition.panel': 'Состояние деталей грузовика, нос вверх',
  'condition.aimedBy': 'Наведено оружие {guns}',
  'icon.star': 'Без износа',
  'icon.money': 'Деньги',
  'icon.fuel': 'Топливо',
  'icon.supplies': 'Припасы',
  'icon.driver': 'Водитель',
  'icon.truck': 'Инвентарь грузовика',
  'icon.cannon': 'Курсовая пушка',
  'icon.mg': 'Пулемётная турель',
  'icon.engine': 'Двигатель',
  'icon.armor': 'Броня',
  'icon.cargo': 'Груз',
  'icon.wheel': 'Колесо',
  'icon.trade': 'Торговля',
  'icon.transmission': 'Коробка передач',
  'icon.cab': 'Кабина',
  'icon.salt': 'Соль',
  'icon.turn': 'Конец хода',
  'icon.tools': 'Станки',
  'icon.parts': 'Запчасти',
  'icon.scanner': 'Радиосканер',
  'icon.damage': 'Урон',
  'icon.pen': 'Пробитие',
  'icon.range': 'Дальность',
  'icon.reload': 'Перезарядка',
  'icon.cooldown': 'Пауза',
  'icon.magazine': 'Магазин',
  'icon.spread': 'Разброс',
  'icon.arc': 'Сектор обстрела',
  'icon.speed': 'Скорость',
  'icon.accel': 'Разгон',
  'icon.noise': 'Шум',
  'icon.ram': 'Таран',
  'icon.rows': 'Ряды груза',
  'icon.hp': 'Прочность',
  'icon.mass': 'Масса',
  'icon.turning': 'Поворот',
  'icon.cells': 'Ячейки груза',
  'icon.load': 'Номинальный груз',
  'icon.recoil': 'Отдача',
  'icon.power': 'Мощность',
  'icon.blast': 'Защита от взрыва',
  'icon.heat': 'Нагрев',
  'icon.patch': 'Полевой ремонт',
  'icon.tall': 'Высота',
  'icon.clock': 'Осталось времени',
  'icon.journal': 'Журнал',
  'stat.same': '=',
  'stat.footprint': '{w}×{h} ячеек',
  'stat.condition': 'Состояние: {hp} из {max} прочн.',
  'stat.compared': 'Сравнение с {part, case, ins} ',
  'stat.layout': 'Схема {chassis, case, gen}',
  'stat.plus0': '+{n}',
  'stat.minus0': '−{n}',
  'stat.plus1': '+{n}',
  'stat.minus1': '−{n}',
  'stat.roundsTimes': '{n}×{damage}',
  'stat.span': '{a}–{b}',
  'stat.rowsUnit': '{n, plural, one {ряд} few {ряда} many {рядов} other {ряда}}',
  'stat.mass': 'Масса',
  'stat.detection': 'Дальность обнаружения',
  'stat.extraFuel': 'Доп. топливо',
  'stat.extraSupplies': 'Доп. припасы',
  'stat.extraRows': 'Доп. ряды груза',
  'stat.pen': 'Пробитие',
  'stat.height': 'Высота',
  'stat.tall': 'высокая',
  'stat.low': 'низкая',
  'stat.damage': 'Урон за выстрел',
  'stat.range': 'Дальность',
  'stat.cooldown': 'Ходов между выстрелами',
  'stat.magazine': 'Выстрелов в магазине',
  'stat.reload': 'Ходов на перезарядку',
  'stat.arc': 'Сектор обстрела',
  'stat.recoil': 'Отдача',
  'stat.spread': 'Разброс',
  'icon.cut': 'Перерезать трос',
  'stat.draw': 'Отбор мощности',
  'stat.topSpeed': 'Макс. скорость',
  'stat.accel': 'Разгон',
  'stat.gunPower': 'Мощность на оружие',
  'stat.fuelUse': 'Расход топлива',
  'stat.heat': 'Нагрев',
  'stat.armor': 'Броня',
  'stat.blastArmor': 'Защита от взрыва',
  'stat.ram': 'Урон тараном',
  'stat.repair.none': 'Ремонт: только в мастерской',
  'stat.repair.capped': 'Полевой ремонт: частичный',
  'stat.repair.full': 'Полевой ремонт: полный',
  'stat.repairShort.none': 'мастерская',
  'stat.repairShort.capped': 'частично',
  'stat.repairShort.full': 'полный',
  'stat.turning': 'Поворот',
  'stat.baseSpeed': 'Базовая макс. скорость',
  'stat.cells': 'Ячейки груза',
  'stat.ratedLoad': 'Номинальный груз',
  'stat.emptyMass': 'Снаряжённая масса',
  'stat.fuelTank': 'Топливный бак',
  'unit.kg': 'кг',
  'unit.m': 'м',
  'unit.t': 'х.',
  'unit.deg': '°',
  'unit.kph': 'км/ч',
  'unit.mps2': 'м/с²',
  'unit.times': '×',
  'unit.liters': 'л',
  'unit.blast': 'взрыв',
  'inv.parkForStorage': 'Встаньте у мастерской, чтобы пользоваться гаражом. Перетащите на крепление, чтобы начать переоснащение.',
  'inv.dump': 'Бросьте сюда, чтобы выкинуть',
  'inv.legend': 'Крепления и управление',
  'inv.legendMounts': 'Вид сверху, нос вверх. Коричневые клетки: крепления на палубе для оружия, сканеров и грузовых рам. Сине-серые клетки: место двигателя. Клетки вокруг грузовика: крепления брони. Наведите на клетку, чтобы узнать, что на неё ставится.',
  'inv.legendWorks': 'Деталь работает, только если целиком лежит на креплениях одного вида. Метки на оружии показывают закрытые стороны.',
  'inv.legendDrag': 'Перетаскивайте, чтобы двигать или менять местами. R или правый клик поворачивает предмет.',
  'inv.refitLeft': 'Переоснащение: осталось {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'inv.refitPlanned': 'Переоборудование: {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'inv.cancelPlan': 'Отмена',
  'inv.equipment': 'Снаряжение',
  'inv.selectHint': 'Выберите деталь или груз, чтобы осмотреть.',
  'inv.cancelRefitTitle': 'Прервать переоснащение и оставить все детали на местах',
  'inv.cancelRefit': 'Отменить переоснащение',
  'inv.refitHint': 'Перетащите на крепление или с него, чтобы начать переоснащение.',
  'inv.patchTitle': 'Ремонт: {turns, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}, запчастей {parts} из {needed}, +{hp} прочн.',
  'inv.patchBlocked': 'Ремонт ({reason})',
  'inv.patch': 'Ремонт: {turns} х., {parts} дет.',
  'inv.repairTitle': 'Восстановить до {hp} прочн.',
  'inv.rebuildTitle': 'Восстановить до последней ступени износа, один раз на деталь',
  'inv.repair': 'Починить {cost}',
  'inv.rebuild': 'Восстановить {cost}',
  'inv.stripTitle': 'Разборка: {turns, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}, выйдет запчастей {parts}',
  'inv.stripBlocked': 'Разобрать',
  'inv.strip': 'Разобрать {turns} х., {parts} дет.',
  'inv.weldTitle': 'Сварка: {turns, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}, выйдет {part}, уйдёт {scrap} металлолома',
  'inv.weldBlocked': 'Сварка ({reason})',
  'inv.weld': 'Сварка {turns} х.',
  'inv.storage': 'Гараж',
  'inv.storageEmpty': 'Бросьте сюда детали, чтобы оставить их в гараже.',
  'inv.goodCount': '{good} ×{n}',
  'inv.takeStores': 'Взять топливо {fuel} л, припасы {supplies}',
  'inv.salvage': 'Добыча',
  'inv.salvageAt': 'Добыча: {site}',
  'inv.nothingLeft': 'Здесь ничего не осталось.',
  'inv.searchMore': 'Искать ещё',
  'inv.takeAll': 'Взять всё, что влезет',
  'inv.dragToGrid': 'Перетащите предметы на сетку.',
  'inv.truckGone': 'Грузовик ушёл',
  'inv.truckGaveUp': '{truck} {truck, gender, m {сдался} f {сдалась} n {сдалось} pl {сдались}}',
  'inv.truckOut': '{truck} без сознания',
  'inv.dragToYours': 'Перетащите предметы на свою сетку.',
  'inv.close': 'Закрыть [I]',
  'inv.title': 'Инвентарь',
  'inv.freeCellsTitle': 'Свободные ячейки груза',
  'inv.freeCells': 'свободно: {n}',
  'inv.loadTitle': 'Масса и допустимая нагрузка',
  'speed.loadChip': '{mass} / {rated}',
  'inv.stopToPatch': 'Остановитесь для ремонта',
  'inv.noParts': 'Нет запчастей',
  'inv.stopToStrip': 'Остановитесь для разборки',
  'inv.busy': 'Занято',
  'inv.stopToWeld': 'Остановитесь для сварки',
  'inv.needsScrap': 'Нужно {n} металлолома',
  'inv.patchShopOnly': 'Ремонт (только в мастерской)',
  'inv.dumpShort': 'Выкинуть',
  'inv.itemRefit': '{item}, переоснащение: осталось {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'inv.patchYield': 'запчастей {parts} из {needed}, +{hp} прочн.',
  'inv.patchLabel': 'Ремонт: {turns, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}, {parts, plural, one {# запчасть} few {# запчасти} many {# запчастей} other {# запчасти}}',
  'inv.stripLabel': 'Разборка: {turns, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}, {parts, plural, one {# запчасть} few {# запчасти} many {# запчастей} other {# запчасти}}',
  'inv.weldSpends': 'Уйдёт {scrap} металлолома',
  'inv.weldLabel': 'Сварка: {part}, {turns, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'inv.verb.patch': 'Ремонт',
  'inv.shopOnly': 'Только в мастерской',
  'inv.verb.repair': 'Починить',
  'inv.verb.rebuild': 'Восстановить',
  'inv.against': 'Сравнение с {part, case, ins} ',
  'cell.deck': 'крепление на палубе для оружия, сканера, грузовой рамы или запаса',
  'cell.engine': 'место двигателя',
  'cell.front': 'крепление передней брони',
  'cell.back': 'крепление задней брони',
  'cell.left': 'крепление левой брони',
  'cell.right': 'крепление правой брони',
  'cell.builtIn': 'встроенная деталь',
  'item.title': '{part}\n{state}',
  'item.partTitle': '{name} ({kind}) {wear}, {hp}/{max} прочн., {w}x{h}',
  'item.cargo': 'Ящик, {mass}',
  'item.builtIn': 'Часть шасси',
  'item.mounted': 'На креплении',
  'item.spare': 'В запасе',
  'kind.weapon': 'оружие',
  'kind.engine': 'двигатель',
  'kind.armor': 'броня',
  'kind.cargo': 'груз',
  'kind.scanner': 'сканер',
  'kind.store': 'запас',
  'kind.core': 'основа',
  'trade.leave': 'Уехать [Esc]',
  'trade.tab.market': 'Рынок',
  'trade.tab.people': 'Люди',
  'trade.tab.buyParts': 'Купить детали',
  'trade.tab.sellParts': 'Продать детали',
  'trade.tab.trucks': 'Грузовики',
  'trade.tab.contracts': 'Контракты',
  'trade.tradeTab.goods': 'Товары',
  'trade.tradeTab.parts': 'Детали',
  'trade.tradeTab.supplies': 'Топливо и припасы',
  'trade.plus': '+{n}',
  'trade.minus': '−{n}',
  'trade.all': 'Все',
  'trade.buyFor': 'Купить {price}',
  'trade.sellFor': 'Продать {price}',
  'trade.toStorage': 'Нет места: уйдёт в гараж',
  'trade.noneOfKind': 'Деталей такого вида нет.',
  'trade.noStock': 'Деталей нет.',
  'trade.filter.all': 'Все',
  'trade.filter.weapon': 'Оружие',
  'trade.filter.engine': 'Двигатели',
  'trade.filter.armor': 'Броня',
  'trade.filter.cargo': 'Груз',
  'trade.filter.scanner': 'Сканеры',
  'trade.filter.store': 'Запасы',
  'trade.sellTitle': 'Продать запасные детали и детали из гаража',
  'trade.noSpares': 'Нет запасных деталей и деталей в гараже.',
  'trade.liters': '{n} л',
  'trade.ofCap': '{have} / {cap}',
  'trade.per': '{price} за {unit}',
  'trade.each': '{price} за штуку',
  'trade.plusAmount': '+{amount}',
  'trade.fill': 'Залить {amount}',
  'trade.onOffer': '{pricing}, в продаже {amount}',
  'trade.broken': 'сломано: {n}',
  'trade.basicsFine': 'Основа в порядке',
  'trade.repairBasics': 'Починить основу {cost}',
  'trade.noRepairs': 'Ремонт не нужен',
  'trade.repairAll': 'Починить всё {cost}',
  'trade.versus': 'вместо {chassis, case, gen}',
  'trade.swap': 'Сменить {cost}',
  'trade.swapBack': 'Сменить, вернут {back}',
  'trade.tradeIn': 'Ваш грузовик примут в зачёт за {price}.',
  'trade.hint.short': 'Здесь дефицит',
  'trade.hint.flooded': 'Здесь затоварено',
  'trade.hint.cheap': 'Здесь дёшево',
  'trade.hint.dear': 'Здесь дорого',
  'trade.noGoods': 'Ни в одном грузовике нет товара на обмен.',
  'trade.theirSpares': 'Их запасные детали',
  'trade.yourSpares': 'Ваши запасные детали',
  'trade.nothingSpare': 'Ничего лишнего.',
  'trade.them': 'Они',
  'trade.theirMoney': 'Их деньги',
  'trade.theirCells': 'Их свободные ячейки груза',
  'trade.noRoom': 'Нет места',
  'trade.noRoomThem': 'У них нет места в кузове',
  'trade.nothingToSell': 'Продавать нечего',
  'trade.needMore': 'Не хватает {price}',
  'trade.full': 'Уже полно',
  'trade.fillBare': 'Залить',
  'trade.nothingToRepair': 'Чинить нечего',
  'trade.repairBasicsVerb': 'Починить основное',
  'trade.repairAllVerb': 'Починить всё',
  'trade.swapVerb': 'Обменять',
  'trade.includesTradeIn': 'Включает {price} за ваш грузовик',
  'trade.filterEmpty': 'Нет в наличии: {kind}',
  'trade.theyNone': 'У них ничего нет',
  'trade.theyHave': 'У них только {amount}',
  'trade.theyLack': 'Им не хватает {price}',
  'trade.perUnit': 'За {unit}',
  'trade.eachUnit': 'За штуку',
  'contract.offers': 'Предложения',
  'contract.needMore': 'Не хватает: {good}, ещё {n}',
  'contract.accept': 'Взять',
  'contract.full': 'У вас уже {n, plural, one {# контракт} few {# контракта} many {# контрактов} other {# контракта}}',
  'contract.board': 'Доска контрактов',
  'contract.noOffers': 'Предложений нет.',
  'contract.yours': 'Ваши контракты {n} / {max}',
  'contract.none': 'У вас нет контрактов.',
  'contract.deliverAt': 'Сдать {site, case, at}',
  'contract.notEnoughCargo': 'Пока мало груза',
  'contract.needsPart': 'Нужна деталь',
  'contract.deliver': 'Сдать',
  'contract.paysGiveUp': 'Оплата за нокаут, уничтожение или сдачу',
  'contract.pays': 'Оплата за нокаут или уничтожение',
  'contract.windowTitle': 'Срок: {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}} с момента взятия',
  'contract.dueTitle': '{n, plural, one {Остался # ход} few {Осталось # хода} many {Осталось # ходов} other {Осталось # хода}}',
  'journal.wagonBowl.title': 'Мародёр с армейской рацией',
  'journal.wagonBowl.from': 'Хэтти, колодезная будка в Чаше',
  'journal.wagonBowl.text': 'В Чашу заезжал мародёр и продавал армейскую рацию с Носа. Говорил, что снял её с мёртвого армейского фургона в холмах к северо-востоку от Чаши. Когда фермеры спросили где, он поспешно укатил на Нос.',
  'journal.wagonNose.title': 'Фургон номер семь',
  'journal.wagonNose.from': 'Сержант Ковач, диспетчерская на Носу',
  'journal.wagonNose.text': 'Рацию сняли с армейского фургона номер семь с Носа. Он пропал на пути от Насосной станции к Чаше. Экипаж вернулся пешком, рейдеры шли по пятам. Мародёр клялся, что фургон стоит недалеко от колеи. С Носа никто так и не поехал посмотреть.',
  'journal.wagonRoad.title': 'Мёртвый армейский фургон в низине',
  'journal.wagonRoad.from': 'Водитель по рации',
  'journal.wagonRoad.text': 'Водитель видел мёртвый армейский фургон в низине, ближе к северной дороге от Чаши, чем к колее у Насосной станции, к югу от старой фермы с водонапорной башней.',
  'journal.wagonFound.title': 'Фургон номер семь списан',
  'journal.wagonFound.from': 'Сержант Ковач, диспетчерская на Носу',
  'journal.wagonFound.text': 'Ковач слышал, что фургон номер семь нашли и обыскали. Армия давно его списала, и он ничего не просит вернуть.',
  'journal.greenPit.title': 'Чистая вода в Зелёной яме',
  'journal.greenPit.from': 'Лена, механик с Носа',
  'journal.greenPit.text': 'Лена говорит, что вода в Зелёной яме чистая, и её никто не охраняет.',
  'journal.glassTank.title': 'Танк на Стеклянной равнине',
  'journal.glassTank.from': 'Хэтти, колодезная будка в Чаше',
  'journal.glassTank.text': 'Хэтти клянётся, что на Стеклянной равнине до сих пор ходит танк Старого мира и выезжает он по ночам.',
  'journal.burntConvoy.title': 'Сгоревший конвой обобран дочиста',
  'journal.burntConvoy.from': 'Старый Ибо, радиорубка на Носу',
  'journal.burntConvoy.text': 'Старый Ибо говорит, что Сгоревший конвой давно обобрали и топлива там тратить не на что.',
  'local.ruben.name': 'Рубен',
  'local.ruben.role': 'Смотритель канала',
  'local.hattie.name': 'Хэтти',
  'local.hattie.role': 'Хозяйка колодезной будки',
  'local.dag.name': 'Даг',
  'local.dag.role': 'Дозорный фермеров Чаши',
  'local.kovac.name': 'Сержант Ковач',
  'local.kovac.role': 'Диспетчер',
  'local.lena.name': 'Лена',
  'local.lena.role': 'Механик',
  'local.ibo.name': 'Старый Ибо',
  'local.ibo.role': 'Радист',
  'log.noted': 'В журнале появилась запись: {title}.',
  'journal.close': 'Закрыть [J]',
  'journal.title': 'Журнал',
  'journal.empty': 'Пока нечего записывать.',
  'journal.entryHead': 'День {day}, {from}',
  'journal.hint': 'Журнал: слухи и зацепки, о которых вам рассказали [J]',
  'quest.leave': 'Уйти',
  'quest.leaveKey': 'Уйти [Esc]',
  'quest.next': 'Дальше',
  'quest.speaker': '{name}: ',
  'quest.choice': '{n}. {text}',
  'quest.offer': '{summary}, оплата {pay}, срок {window}.',
};
