import type { TALK as EN } from '../en/talk';
import type { Translation } from '../msg';

export const TALK: Translation<typeof EN> = {
  'line.aWreckNobodyPicked': 'Обломки, которые ещё никто не обобрал, — {bearing} от тебя, примерно в {distance}.',
  'line.agreedGunsDown': 'Договорились. Стволы вниз.',
  'line.allRightIAm': 'Ладно. Я всё. Бери что хочешь.',
  'line.allRightItIs': 'Ладно! Груз на земле. Теперь оставь нас в покое.',
  'line.alreadySaid': 'Уже сказано.',
  'line.anythingInteresting': 'Есть что интересное?',
  'line.busy': 'Занят! Освободи канал.',
  'line.canYouDoAnything': 'Двигатель, коробка или бак. Сделаешь что-нибудь?',
  'line.clearTheChannel': 'Освободи канал.',
  'line.comeAndGetIt': 'Подойди и возьми.',
  'line.comeAndTakeIt': 'Иди и отними.',
  'line.dealHitchMeUp': 'Договорились. Цепляй.',
  'line.dealHitchUp': 'Договорились. Цепляйся.',
  'line.dealIWillStay': 'Договорились. Стою на месте.',
  'line.dealPlain': 'Договорились.',
  'line.dealPullOverAnd': 'Договорились. Тормози и жди.',
  'line.dealSendingIt': 'Договорились. Отправляю.',
  'line.dealStayWhereYou': 'Договорились. Стой где стоишь.',
  'line.dealTerms': '{deal}',
  'line.demandCargo': 'Сбрасывай груз и катись дальше. Или снимем его с твоих обломков.',
  'line.dropYourCargoOr': 'Сбрасывай груз, или открываем огонь.',
  'line.dumpAndDrive': 'Сбрасывай груз и уезжай.',
  'line.enoughOfThisWe': 'Хватит. Разъедемся.',
  'line.enoughShootingCanWe': 'Хватит стрелять. Может, перемирие?',
  'line.findYourOwnWreck': 'Найди себе другие обломки.',
  'line.findersKeepers': 'Кто нашёл, того и добыча.',
  'line.fineItsYours': 'Ладно. Твоё.',
  'line.fineKeepYourGuns': 'Ладно. Стволы не поднимай.',
  'line.fineTakeIt': 'Ладно. Забирай.',
  'line.fineThanksForThe': 'Ладно. Спасибо, что подтащил.',
  'line.getLost': 'Проваливай.',
  'line.getOffMyChannel': 'Уйди с моей волны.',
  'line.giveUpOffer': 'Твой грузовик встал посреди дороги. Сдавайся, и мы оба поедем дальше.',
  'line.goAhead': 'Говори.',
  'line.going': 'Уезжаю.',
  'line.good': 'Хорошо.',
  'line.hangUp': 'Отключиться.',
  'line.haveItYourWay': 'Как знаешь.',
  'line.heardYou': 'Слышал.',
  'line.heardYouTheFirst': 'Я с первого раза услышал.',
  'line.hehNo': 'Хе. Нет.',
  'line.holdOnIAm': 'Держись. Сейчас подъеду.',
  'line.howArePricesIn': 'Какие цены в городе?',
  'line.iAmLettingYou': 'Отцепляю тебя здесь.',
  'line.iAmListening': 'Слушаю.',
  'line.iAmRunningDry': 'У меня всё на исходе. Поделишься?',
  'line.iAmStrandedCan': 'Я застрял. Дотащишь меня?',
  'line.iCanSpareAid': 'Могу дать вот что: {aid}. Стой на месте, я подъеду.',
  'line.iCannotHelpSorry': 'Не смогу помочь, извини.',
  'line.iCouldUseAid': 'Мне бы не помешало вот что: {aid}. Могу заплатить {price}.',
  'line.iGiveUpLet': 'Сдаюсь. Отпусти меня.',
  'line.iToldYouAlready': 'Я тебе уже сказал.',
  'line.keepItShort': 'Короче.',
  'line.keepOffThisChannel': 'Не лезь на этот канал.',
  'line.lastIWasIn': '{town}, когда я там был: {prices}.',
  'line.leaveItOnThe': 'Оставь всё на земле и проваливай.',
  'line.letMeCheckMy': 'Сейчас проверю баки.',
  'line.letMeHearWhat': 'Рассказывай, что сломалось.',
  'line.listening': 'Слушаю.',
  'line.makeItShort': 'Покороче.',
  'line.maybeIPassedSomething': 'Может быть. Проезжал кое-что по пути.',
  'line.moneyIsInGuns': 'Деньги пришли. Стволы вниз.',
  'line.moveAlong': 'Проезжай.',
  'line.myTruckIsBroken': 'Мой грузовик сломался. Подлатаешь?',
  'line.myTruckIsDead': 'Мой грузовик заглох намертво. Подлатаешь?',
  'line.needATowTo': 'Дотащить до города?',
  'line.neverMind': 'Неважно.',
  'line.noCharge': 'Бесплатно.',
  'line.noChargeHitchUp': 'Бесплатно. Цепляйся.',
  'line.noDeals': 'Никаких сделок.',
  'line.noFreeRideDump': 'Даром не отпущу. Сбрасывай груз и катись, тогда мы в расчёте.',
  'line.noMercy': 'Пощады не будет.',
  'line.noThanks': 'Нет, спасибо.',
  'line.noTimeOut': 'Некогда. Отбой.',
  'line.noWeFinishThis': 'Нет. Закончим это.',
  'line.notInterested': 'Не интересует.',
  'line.notNowSomethingElse': 'Не сейчас. Ещё вопрос.',
  'line.notTalking': 'Не разговариваю.',
  'line.notToday': 'Не сегодня.',
  'line.notTodayRun': 'Не сегодня!',
  'line.notWhileICan': 'Пока могу жать на спуск — нет.',
  'line.notWithWhatI': 'С тем, что у меня есть, — никак. Извини.',
  'line.nothingForYou': 'Для тебя ничего нет.',
  'line.nothingToSayTo': 'Мне с тобой не о чем говорить.',
  'line.oldNewsFriend': 'Старые новости, друг.',
  'line.onSecondThoughtI': 'Нет, пожалуй, не смогу.',
  'line.overAndOut': 'Конец связи.',
  'line.overMyDeadBody': 'Только через мой труп.',
  'line.pullFree': 'Могу дотащить тебя, пункт — {town}. Бесплатно.',
  'line.pullPaid': 'Могу дотащить тебя, пункт — {town}. С тебя {fee}, когда доедем.',
  'line.pullingOver': 'Съезжаю.',
  'line.rollingOn': 'Еду дальше.',
  'line.runThen': 'Тогда беги.',
  'line.runningLowICan': 'На исходе? Могу поделиться.',
  'line.saidThatAlready': 'Уже говорил.',
  'line.sayThatAgain': 'Повтори-ка?',
  'line.saysWho': 'Кто сказал?',
  'line.seenAnythingWorthA': 'Видел что-нибудь стоящее?',
  'line.sitTight': 'Сиди тихо.',
  'line.siteBearing': '{site} — {bearing} от тебя, примерно в {distance}.',
  'line.smartChoice': 'Разумно.',
  'line.sorryCannotSpareAny': 'Извини. Самому не хватает.',
  'line.spare': 'С тебя и взять нечего.',
  'line.speakUp': 'Говори громче.',
  'line.standDownAndLet': 'Сдавайся и дай мне разобрать твой грузовик.',
  'line.standingDown': 'Сдаюсь.',
  'line.stateYourBusiness': 'Излагай, что нужно.',
  'line.stopShootingIGive': 'Не стреляй! Сдаюсь. Забирай, что я везу, и отпусти.',
  'line.surePullOverAnd': 'Давай. Съезжай на обочину, я подъеду.',
  'line.surrenderOffer': 'Твой грузовик мёртв. Отдай груз и лучшие детали, и грузовик останется при тебе. Откажешься — сниму всё с обломков.',
  'line.takeMeToSite': 'Мне туда — {site}. Заплачу {fee}, когда доедем.',
  'line.takeWhatICarry': 'Забирай, что я везу. Только дай уехать.',
  'line.talk': 'Говори.',
  'line.talkFast': 'Говори быстрее.',
  'line.thanksIWillWait': 'Спасибо. Жду.',
  'line.thanksOverAndOut': 'Спасибо. Конец связи.',
  'line.thanksSomethingElse': 'Спасибо. Ещё вопрос.',
  'line.thenComeAndGet': 'Тогда приезжай и бери.',
  'line.thenWeFinishThis': 'Тогда закончим это.',
  'line.thisIsMine': 'Это моё.',
  'line.thisWreckIsMine': 'Эти обломки мои. Отвали.',
  'line.tipTold': '{tip}',
  'line.tooLateForTalk': 'Поздно болтать.',
  'line.tooMuch': 'Слишком дорого.',
  'line.townBearing': '{town} — {bearing} от тебя, примерно в {distance}.',
  'line.truceCost': '{price}, и забудем.',
  'line.understood': 'Понял.',
  'line.wantToTrade': 'Поторгуем?',
  'line.weAlreadyTalkedAbout': 'Мы это уже обсудили.',
  'line.weBothDriveAway': 'Разъедемся по-хорошему.',
  'line.weCoveredThat': 'Это мы уже прошли.',
  'line.weWillSee': 'Посмотрим.',
  'line.whatAreYouOffering': 'Что предлагаешь?',
  'line.whatCanYouOffer': 'Что можешь предложить?',
  'line.whatDoYouWant': 'Чего тебе?',
  'line.whatWouldItCost': 'Сколько стоит покончить с этим?',
  'line.whatWouldItTake': 'Двигатель, коробка или бак. Во что обойдётся?',
  'line.whateverYouCanSpare': 'Сколько не жалко.',
  'line.where': 'Где?',
  'line.whereIsTheNearest': 'Где ближайший город?',
  'line.yeahMakeItQuick': 'Ну? Только быстро.',
  'line.youHeardMeCargo': 'Ты слышал. Груз на землю, живо.',
  'line.youHeardMeLeave': 'Ты слышал. Оставь.',
  'line.youKnowHowThen': 'Умеешь? Тогда называй цену.',
  'line.youLookDryI': 'Вижу, ты на мели. Могу дать вот что: {aid}, бесплатно.',
  'line.youSaidThat': 'Ты это уже говорил.',
  'line.youWantToPick': 'Хочешь обобрать мой грузовик до нитки?',
  'line.yourCallLastChance': 'Решай. Последний шанс.',
  'line.yourEngineSoundsRough': 'Двигатель у тебя барахлит. Подлатать, пока не заглох?',
  'line.yourFuneral': 'Сам напросился.',
  'line.yourTruckIsFinished': 'Твоему грузовику конец. Сдавайся и дай мне его разобрать — останешься жив.',
  'line.yourTruckLooksDead': 'Твой грузовик, похоже, встал. Подлатать?',
  'deal.paid.npc': 'Детали у меня есть. {parts} и работа — всего {price}.',
  'deal.paid.player': 'Заплачу {price}, если поставишь своё: {parts}.',
  'deal.ownParts.npc': 'Нужно твоё: {parts}. За работу беру {price}.',
  'deal.ownParts.player': 'У меня есть: {parts}. {price} за твою работу.',
  'deal.free.npc': 'Сделаю даром. Детали мои: {parts}.',
  'deal.free.player': 'Платить нечем. Не выделишь {parts}?',
  'tip.dear': 'Заезжал недавно — {site}. Там втридорога: {subject}.',
  'tip.cheap': 'Заезжал недавно — {site}. Там почти даром: {subject}.',
  'tip.none': 'Рассказывать нечего.',
  'compass.east': 'к востоку',
  'compass.southEast': 'к юго-востоку',
  'compass.south': 'к югу',
  'compass.southWest': 'к юго-западу',
  'compass.west': 'к западу',
  'compass.northWest': 'к северо-западу',
  'compass.north': 'к северу',
  'compass.northEast': 'к северо-востоку',
  'call.km': '{km} км',
  'call.m': '{m} м',
  'call.money': '{amount}',
  'call.price': '{good}: покупка {buy}, продажа {sell}',
  'call.fuel': '{liters} л топлива',
  'call.supplies': '{n, plural, one {# ящик припасов} few {# ящика припасов} many {# ящиков припасов} other {# ящика припасов}}',
  'call.aid': '{fuel} и {supplies}',
  'call.speaker': 'Рация: {who}',
  'call.said': '«{line}»',
  'call.option': '{n}. {line}',
  'radio.ident.0': 'Это Джей-Джей на радио «Время в трубу». Тратим ваше время с тех пор, как упало небо.',
  'radio.ident.1': '«Время в трубу», у микрофона Джей-Джей. Никто не звал, а я всё равно тут.',
  'radio.dawn.0': 'Над котловиной встало солнце. Водоносы опередили его на рынке.',
  'radio.dawn.1': 'Утро, мальчики. Роса на стекле, песок в шестернях. Как вчера.',
  'radio.dawn.2': 'Сводка на рассвете: в небе ничего съедобного. Подъём и в путь.',
  'radio.noon.0': 'Полдень. Моторы поют песню, которую я так и не полюбила.',
  'radio.noon.1': 'Полдень над котловиной. Даже ящерицы догадались переждать.',
  'radio.dusk.0': 'Солнце садится. Где-то кто-то только что стал ориентиром.',
  'radio.dusk.1': 'Вечерняя сводка: дневной урожай опять сухой. Везите домой, мальчики.',
  'radio.midnight.0': 'Полночь. Только моторы знают, чья это дорога.',
  'radio.midnight.1': 'Полночь на радио «Время в трубу». Я всё ещё тут. Всё ещё трачу.',
  'radio.heatwaveStart.0': 'Идёт жара. Хор радиаторов начал распевку.',
  'radio.heatwaveStart.1': 'Над котловиной жара. Радиаторы закипят раньше чайников.',
  'radio.heatwaveEnd.0': 'Жара спала. Моторный хор, к счастью, умолк.',
  'radio.heatwaveEnd.1': 'Жара наконец отпустила. Благодарите, кого привыкли.',
  'radio.overcastStart.0': 'Над котловиной тучи. Солнце взяло выходной.',
  'radio.overcastStart.1': 'Пасмурно и прохладно. Небо вспомнило, как быть добрым.',
  'radio.stormStart.0': 'Пыльная буря {place}, идёт {heading}.',
  'radio.stormStart.1': 'Пылевая стена {place}, идёт {heading}. Горизонт уволился.',
  'radio.stormEnd.0': 'Пыльная буря {place} выдохлась.',
  'radio.stormEnd.1': 'Буря {place} улеглась. Кто-нибудь, откопайте дорогу.',
  'radio.haul.0': 'Новая перевозка, {shop}: груз — {good}, пункт — {to}.',
  'radio.haul.1': '{shop}: нужен извоз, {good} — {to}. Работа честная.',
  'radio.fetch.0': '{shop} ищет исправную деталь: {part}.',
  'radio.fetch.1': 'Розыск, {shop}: деталь «{part}», ещё дышащая.',
  'radio.bounty.0': 'Награда, {shop}: {target}. Говорят, это бизнес, а не убийство.',
  'radio.bounty.1': 'На доске, {shop}, листовка: {target}. Я просто читаю доску, мальчики.',
  'radio.raid.0': 'Рейдерские дела {place}. Ещё один горячий день для бухгалтеров.',
  'radio.raid.1': 'Рейдеры работают на дороге {place}. Груз там меняет хозяев.',
  'radio.raid.2': 'Слышно о налёте {place}. Рейдеры соблюдают график.',
  'radio.raidKnockout.0': 'Ещё одна машина затихла {place}. Судя по звуку, рейдеры.',
  'radio.raidKnockout.1': 'Машина мертва {place}. Рейдеры взяли своё. Больше не берите.',
  'radio.wisdom.0': 'У полуденного солнца своё мнение о моторах. Тень держит своё при себе.',
  'radio.wisdom.1': 'У городских пушек память длиннее, чем у городского писаря.',
  'radio.wisdom.2': 'В темноте соседа слышно задолго до того, как его видно.',
  'radio.wisdom.3': 'У тихой машины на обочине либо хорошие тормоза, либо плохая удача.',
  'radio.wisdom.4': 'Дорожная пыль представляет водителя раньше, чем его имя.',
  'radio.wisdom.5': 'В споре с лёгкой машиной последнее слово всегда за тяжёлой.',
  'radio.wisdom.6': 'Километры по бездорожью любят превращаться в счета за ремонт.',
  'radio.wisdom.7': 'К застрявшему торговцу приходят гости. О застрявшем рейдере ходят байки.',
  'radio.wisdom.8': 'Пыль снова проглотила горизонт. Я ему и так не доверяла.',
  'radio.wisdom.9': 'Стрелка топлива на нуле рассказывает самые длинные истории.',
  'radio.wisdom.10': 'Городские койки дороги. Ночь без гаечного ключа дороже.',
  'radio.wisdom.11': 'Кто-то посигналил торговцу. Торговец ответил. Общество живёт.',
  'radio.wisdom.12': 'Продюсер говорит, нам нужен спонсор. Я сказала, что нам нужен продюсер.',
  'radio.wisdom.13': 'Нашла прогноз погоды Старого мира. В конце: «возможен дождь». Чудная выдумка.',
  'radio.wisdom.14': 'Мачта ещё стоит. Кофе кончился. У кого-то из нас есть приоритеты.',
  'radio.wisdom.15': 'Сегодня у дороги гости. Завтра она скажет, что никого не знает.',
  'radio.wisdom.16': 'Слушатель прислал карту. На ней одна пометка: «не здесь». Разумная картография.',
  'radio.wisdom.17': 'Меня обвиняют в разговорах с самой собой. Вы — улика против меня.',
  'radio.wisdom.18': 'Помехи заказали песню. Я сказала, что они уже её исполняют.',
  'radio.wisdom.19': 'Где-то честный механик ушёл на покой. Остальные подняли цены.',
  'radio.band': 'WOT RADIO',
  'radio.frequency': 'FM 66.6',
  'radio.near': 'в районе «{site}»',
  'radio.basin.east': 'на востоке',
  'radio.basin.southEast': 'в юго-восточной котловине',
  'radio.basin.south': 'на юге',
  'radio.basin.southWest': 'в юго-западной котловине',
  'radio.basin.west': 'на западе',
  'radio.basin.northWest': 'в северо-западной котловине',
  'radio.basin.north': 'на севере',
  'radio.basin.northEast': 'в северо-восточной котловине',
  'radio.heading.east': 'на восток',
  'radio.heading.southEast': 'на юго-восток',
  'radio.heading.south': 'на юг',
  'radio.heading.southWest': 'на юго-запад',
  'radio.heading.west': 'на запад',
  'radio.heading.northWest': 'на северо-запад',
  'radio.heading.north': 'на север',
  'radio.heading.northEast': 'на северо-восток',
};
