import type { UI as EN } from '../en/ui';
import type { Translation } from '../msg';

export const UI: Translation<typeof EN> = {
  'money.m': '{n} М',
  'menu.menu': 'Меню',
  'menu.help': 'Помощь',
  'help.title': 'Управление',
  'help.errorsSent': 'Ошибки игры отправляются разработчикам вместе с сохранением.',
  'hud.overdriveWorn': 'Двигатель слишком изношен для форсажа. Почините его выше {pct}% [O]',
  'hit.cause.smoke': 'дым',
  'hit.reason.smoke': 'дым',
  'hit.shutDown': 'Отключён, осталось {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'save.exportSave': 'Экспорт сохранения',
  'save.exportSaveTitle': 'Скачать игру в её нынешнем состоянии',
  'save.exportLog': 'Экспорт журнала забега',
  'save.exportLogTitle': 'Скачать всё, что случилось за забег, по одному событию в строке',
  'stat.lineHolds': 'Ходов держится трос',
  'hint.wreck': 'Двигатель почти мёртв. [Shift]+клик по земле у обломков задаёт точку остановки, затем [Пробел], чтобы доехать.',
  'hint.search': 'Нажмите «Обшарить обломки», затем [Пробел], чтобы начать поиск.',
  'hint.loot': 'Перетащите детали и арматурную клетку на свой грузовик или нажмите «Взять всё, что влезет».',
  'hint.patch': '[I] открывает ваш грузовик. Нажмите на двигатель, затем «Ремонт». Закройте грузовик, и [Пробел] запустит ремонт.',
  'hint.install': '[I] открывает ваш грузовик. Перетащите арматурную клетку на свободную ячейку у его края, закройте его, и [Пробел] смонтирует клетку.',
  'mode.roaming': 'Скитания',
  'mode.roaming.description': 'Открытая пустошь. Езжайте, торгуйте, собирайте хлам и сражайтесь как хотите.',
  'setting.damage': 'Урон',
  'setting.damage.description': 'Урон всех орудий и аварий для каждого грузовика.',
  'setting.fuelUse': 'Расход топлива',
  'setting.fuelUse.description': 'Сколько топлива сжигает каждый грузовик на каждую пройденную клетку.',
  'setting.supplyUse': 'Расход припасов',
  'setting.supplyUse.description': 'Сколько припасов съедает каждая команда за ход.',
  'save.download': 'Скачать сохранение',
  'save.reportBug': 'Если это похоже на ошибку, скачайте сохранение и приложите его к обращению на GitHub.',
  'save.settingReset': 'Настройка «{setting}» сброшена до {pct}%',
  'inv.nothingFound': 'Пока ничего не найдено.',
  'inv.instantHint': 'Детали встают сразу: перетащите их на крепление или с него.',
  'block.unmounted': 'не установлено',
  'block.shutDown': 'отключено',
  'block.armed': 'уже взведено',
  'block.fuel': 'не хватает топлива',
  'block.lineOut': 'трос выпущен',
  'blockShort.unmounted': 'в кузове',
  'blockShort.shutDown': 'выкл.',
  'blockShort.lineOut': 'трос',
  'utility.pick': 'цель: клик по земле',
  'utility.fires': 'сработает в этом ходу',
  'utility.armed': 'взведено',
  'utility.noFuel': 'нет топлива',
  'utility.recharging': 'перезарядка {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'utility.slotLabel': '{name}: {status}',
  'utility.keyTitle': '{name} [{key}]',
  'weapon.allGuns': 'все орудия',
  'weapon.gunN': 'орудие {n}',
  'weapon.body': 'Корпус',
  'weapon.bodyTitle': 'Выстрел по корпусу ({guns}): снаряды бьют в любую деталь, до которой долетят. Нажмите ещё раз, чтобы отменить.',
  'icon.utility': 'Оборудование',
  'stat.recharge': 'Ходов на перезарядку',
  'stat.lasts': 'Ходов действует',
  'stat.slick': 'Длина пятна',
  'stat.radius': 'Радиус',
  'trade.filter.utility': 'Оборудование',
  'trade.theyCantPay': 'Им нечем заплатить',
  'contract.claim': 'Забрать награду',
  'contract.claimAt': 'Забрать награду: {site}',
  'contract.notMet': 'Условие ещё не выполнено',
  'contract.ready': 'Готово',
  'short.util': 'Обор.',
  'log.found': 'Найдено: {items}.',
  'log.caltropsYou': 'Вы наезжаете на шипы',
  'log.caltropsThem': '{who} наезжает на шипы',
  'log.pulseNone': 'Ваш импульс излучателя никого не задел',
  'log.pulseYours': 'Ваш импульс излучателя отключает: {who}',
  'log.pulseTheirs': 'Импульс излучателя ({who}) отключает ваш грузовик на {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'log.cookOffYours': 'Ваш таран-клеймор ломается и взрывается',
  'log.cookOffTheirs': 'Таран-клеймор ({who}) ломается и взрывается',
  'log.obstacle.rock': 'камень',
  'log.obstacle.wreck': 'обломки',
  'log.obstacle.building': 'здание',
  'log.obstacle.water': 'воду',
  'log.obstacle.site': 'постройку',
  'log.obstacle.landmark': 'ориентир',
  'log.claymoreWallYours': 'Ваш таран-клеймор взрывается о такой объект: {what}',
  'log.claymoreWallTheirs': 'Таран-клеймор ({who}) взрывается о такой объект: {what}',
  'log.claymoreYours': 'Ваш таран-клеймор накрывает цель: {whom}',
  'log.claymoreYou': 'Таран-клеймор ({who}) накрывает ваш грузовик',
  'log.claymoreTheirs': 'Таран-клеймор ({who}) накрывает цель: {whom}',
  'log.cargoSpilledOther': '{who}: груз рассыпался по земле',
  'log.cargoSpilledYours': 'Сломалась деталь «{part}». Выпало: {n, plural, one {# предмет} few {# предмета} many {# предметов} other {# предмета}}.',
  'log.harpoon': '{gun} → {target}: {what}',
  'log.harpoonLine': 'трос на детали «{part}»',
  'log.harpoonMissed': 'промах',
  'log.lineTornYou': 'Вы вырываетесь из гарпунного троса',
  'log.lineTornThem': '{who} вырывается из гарпунного троса',
  'newGame.mode': 'Режим игры',
  'newGame.settings': 'Настройки мира',
  'newGame.start': 'Начать',
  'newGame.back': 'Назад',
  'newGame.reset': 'Сбросить настройки',
  'newGame.default': 'по умолчанию {pct}',
  'setup.part': '{setting} {pct}',
  'setting.percent': '{n}%',
  'cell.deadRows': 'Сломанные ряды груза. Почините грузовую деталь, чтобы пользоваться ими.',
  'kind.utility': 'оборудование',
};
