import type { UI as EN } from '../en/ui';
import type { Translation } from '../msg';

export const UI: Translation<typeof EN> = {
  'money.m': '{n} М',
  'menu.menu': 'Меню',
  'menu.help': 'Помощь',
  'help.title': 'Управление',
  'help.errorsSent': 'Ошибки игры отправляются разработчикам вместе с сохранением.',
  'hud.overdriveWorn': 'Двигатель слишком изношен для форсажа. Нужна прочность выше {pct}% [O]',
  'hit.cause.smoke': 'дым',
  'hit.reason.smoke': 'дым',
  'hit.shutDown': 'Отключён, осталось {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'save.exportSave': 'Экспорт сохранения',
  'save.exportSaveTitle': 'Скачать игру в её нынешнем состоянии',
  'save.exportLog': 'Экспорт журнала забега',
  'save.exportLogTitle': 'Скачать всё, что случилось за забег, по одному событию в строке',
  'stat.lineHolds': 'Ходов держится трос',
  'hint.wreck': 'Двигатель почти мёртв. [Shift]+клик по земле у обломков задаёт точку остановки, затем [Пробел], чтобы доехать.',
  'hint.search': 'Нажмите «Обшарить обломки», затем [Пробел], чтобы начать поиск.',
  'hint.loot': 'Перетащите детали и арматурную клетку на грузовик или нажмите «Взять всё, что влезет».',
  'hint.patch': '[I] открывает грузовик. Нажмите на двигатель, затем «Ремонт». Закройте грузовик, и [Пробел] запустит ремонт.',
  'hint.install': '[I] открывает грузовик. Перетащите арматурную клетку на свободную ячейку у его края, закройте грузовик, и [Пробел] смонтирует клетку.',
  'mode.roaming': 'Скитания',
  'mode.roaming.description': 'Открытая пустошь. Езжайте, торгуйте, собирайте хлам и сражайтесь как хотите.',
  'setting.damage': 'Урон',
  'setting.damage.description': 'Урон всех орудий и аварий для каждого грузовика.',
  'setting.fuelUse': 'Расход топлива',
  'setting.fuelUse.description': 'Сколько топлива сжигает каждый грузовик на каждую пройденную клетку.',
  'setting.supplyUse': 'Расход припасов',
  'setting.supplyUse.description': 'Сколько припасов съедает каждая команда за ход.',
  'save.download': 'Скачать сохранение',
  'save.reportBug': 'Если это похоже на ошибку, скачайте сохранение и приложите его к обращению на GitHub.',
  'save.settingReset': 'Настройка «{setting}» сброшена до {pct}%',
  'inv.nothingFound': 'Пока ничего не найдено.',
  'inv.instantHint': 'Детали встают сразу: перетащите их на крепление или с него.',
  'block.unmounted': 'не установлено',
  'block.shutDown': 'отключено',
  'block.armed': 'уже взведено',
  'block.fuel': 'не хватает топлива',
  'block.lineOut': 'трос выпущен',
  'blockShort.unmounted': 'в кузове',
  'blockShort.shutDown': 'выкл.',
  'blockShort.lineOut': 'трос',
  'utility.pick': 'цель: клик по земле',
  'utility.fires': 'сработает в этом ходу',
  'utility.armed': 'взведено',
  'utility.noFuel': 'нет топлива',
  'utility.recharging': 'перезарядка {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'utility.slotLabel': '{name}: {status}',
  'utility.keyTitle': '{name} [{key}]',
  'weapon.allGuns': 'все орудия',
  'weapon.gunN': 'орудие {n}',
  'weapon.body': 'Корпус',
  'weapon.bodyTitle': 'Выстрел по корпусу ({guns}): снаряды бьют в любую деталь, до которой долетят. Нажмите ещё раз, чтобы отменить.',
  'icon.utility': 'Оборудование',
  'stat.recharge': 'Ходов на перезарядку',
  'stat.lasts': 'Ходов действует',
  'stat.slick': 'Длина пятна',
  'stat.radius': 'Радиус',
  'trade.filter.utility': 'Оборудование',
  'trade.theyCantPay': 'Им нечем заплатить',
  'contract.claim': 'Забрать награду',
  'contract.claimAt': 'Награда {site, case, at}',
  'contract.notMet': 'Условие ещё не выполнено',
  'contract.ready': 'Готово',
  'short.util': 'Обор.',
  'log.found': 'Найдено: {items}.',
  'log.caltropsYou': 'Вы наезжаете на шипы',
  'log.caltropsThem': '{who} наезжает на шипы',
  'log.pulseNone': 'Ваш импульс излучателя никого не задел',
  'log.pulseYours': 'Ваш импульс излучателя отключает {who, case, acc}',
  'log.pulseTheirs': 'Импульс излучателя {who, case, gen} отключает ваш грузовик на {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'log.cookOffYours': 'Ваш таран-клеймор ломается и взрывается',
  'log.cookOffTheirs': 'Таран-клеймор {who, case, gen} ломается и взрывается',
  'log.obstacle.rock': 'камень',
  'log.obstacle.wreck': 'обломки',
  'log.obstacle.building': 'здание',
  'log.obstacle.water': 'воду',
  'log.obstacle.site': 'постройку',
  'log.obstacle.landmark': 'ориентир',
  'log.claymoreWallYours': 'Ваш таран-клеймор врезается в {what} и взрывается',
  'log.claymoreWallTheirs': 'Таран-клеймор {who, case, gen} врезается в {what} и взрывается',
  'log.claymoreYours': 'Ваш таран-клеймор накрывает {whom, case, acc}',
  'log.claymoreYou': 'Таран-клеймор {who, case, gen} накрывает ваш грузовик',
  'log.claymoreTheirs': 'Таран-клеймор {who, case, gen} накрывает {whom, case, acc}',
  'log.cargoSpilledOther': 'Груз {who, case, gen} рассыпался по земле',
  'log.cargoSpilledYours': '{part} {part, gender, m {сломался} f {сломалась} n {сломалось} pl {сломались}}. {n, plural, one {Выпал # предмет} few {Выпало # предмета} many {Выпало # предметов} other {Выпало # предмета}}.',
  'log.harpoon': '{gun} → {target}: {what}',
  'log.harpoonLine': 'трос на {part, case, prep}',
  'log.harpoonMissed': 'промах',
  'log.lineTornYou': 'Вы вырываетесь из гарпунного троса',
  'log.lineTornThem': '{who} вырывается из гарпунного троса',
  'newGame.mode': 'Режим игры',
  'newGame.settings': 'Настройки мира',
  'newGame.start': 'Начать',
  'newGame.back': 'Назад',
  'newGame.reset': 'Сбросить настройки',
  'newGame.default': 'по умолчанию {pct}',
  'setup.part': '{setting} {pct}',
  'setting.percent': '{n}%',
  'cell.deadRows': 'Сломанные ряды груза. Почините грузовую деталь, чтобы пользоваться ими.',
  'kind.utility': 'оборудование',
};
