import type { UI as EN } from '../en/ui';
import { noun, type Translation } from '../msg';

export const UI: Translation<typeof EN> = {
  'money.minus': '−{n, plural, one {# М} few {# М} many {# М} other {# М}}',
  'money.m': '{n, plural, one {# М} few {# М} many {# М} other {# М}}',
  'menu.menu': 'Меню',
  'menu.help': 'Помощь',
  'menu.options': 'Настройки',
  'options.title': 'Настройки',
  'help.title': 'Управление',
  'help.errorsSent': 'Ошибки игры отправляются разработчикам вместе с сохранением.',
  'hud.overdriveNoEngine': 'Нет двигателя',
  'hud.overdriveWorn': 'Двигатель слишком изношен для форсажа. Нужна прочность выше {pct}% [O]',
  'hit.cause.smoke': 'дым',
  'hit.reason.smoke': 'дым',
  'hit.shutDown': 'Отключён, осталось {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'save.exportSave': 'Экспорт сохранения',
  'save.exportSaveTitle': 'Скачать игру в её нынешнем состоянии',
  'save.exportLog': 'Экспорт журнала забега',
  'save.exportLogTitle': 'Скачать всё, что случилось за забег, по одному событию в строке',
  'stat.lineHolds': 'Ходов держится трос',
  'hint.wreck': '[Shift]+клик по земле у обломков, затем [Пробел], чтобы доехать.',
  'hint.search': 'Нажмите «Обшарить обломки», затем [Пробел].',
  'hint.loot': 'Нажмите «Взять всё, что влезет».',
  'hint.patch': '[I], нажмите на двигатель, затем «Ремонт», затем [Пробел].',
  'hint.install': '[I], перетащите арматурный каркас на свободную ячейку у края грузовика, затем [Пробел].',
  'mode.roaming': 'Скитания',
  'mode.roaming.description': 'Открытая пустошь. Езжайте, торгуйте, собирайте хлам и сражайтесь как хотите.',
  'setting.damage': 'Урон',
  'setting.damage.description': 'Урон всех орудий и аварий для каждого грузовика.',
  'setting.fuelUse': 'Расход топлива',
  'setting.fuelUse.description': 'Сколько топлива сжигает каждый грузовик на каждую пройденную клетку.',
  'setting.supplyUse': 'Расход припасов',
  'setting.supplyUse.description': 'Сколько припасов съедает каждая команда за ход.',
  'save.download': 'Скачать сохранение',
  'save.reportBug': 'Если это похоже на ошибку, скачайте сохранение и приложите его к обращению на GitHub.',
  'save.settingReset': 'Настройка «{setting}» сброшена до {pct}%',
  'inv.nothingFound': 'Пока ничего не найдено.',
  'inv.instantHint': 'Детали встают сразу: перетащите их на крепление или с него.',
  'block.unmounted': 'не установлено',
  'block.shutDown': 'отключено',
  'block.armed': 'уже взведено',
  'block.fuel': 'не хватает топлива',
  'block.lineOut': 'трос выпущен',
  'blockShort.unmounted': 'в кузове',
  'blockShort.shutDown': 'выкл.',
  'blockShort.lineOut': 'трос',
  'utility.pick': 'цель: клик по земле',
  'utility.fires': 'сработает в этом ходу',
  'utility.armed': 'взведено',
  'utility.noFuel': 'нет топлива',
  'utility.recharging': 'перезарядка {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'utility.slotLabel': '{name}: {status}',
  'utility.keyTitle': '{name} [{key}]',
  'weapon.allGuns': 'все орудия',
  'weapon.gunN': 'орудие {n}',
  'weapon.body': 'Корпус',
  'weapon.bodyTitle': 'Выстрел по корпусу ({guns}): снаряды бьют в любую деталь, до которой долетят. Нажмите ещё раз, чтобы отменить.',
  'icon.utility': 'Оборудование',
  'stat.recharge': 'Ходов на перезарядку',
  'stat.lasts': 'Ходов действует',
  'stat.slick': 'Длина пятна',
  'stat.radius': 'Радиус',
  'trade.filter.utility': 'Оборудование',
  'trade.theyCantPay': 'Им нечем заплатить',
  'contract.claim': 'Забрать награду',
  'contract.claimAt': 'Награда {site, case, at}',
  'contract.notMet': 'Условие ещё не выполнено',
  'contract.ready': 'Готово',
  'short.util': 'Обор.',
  'log.found': 'Найдено: {items}.',
  'log.caltropsYou': 'Вы наезжаете на шипы',
  'log.caltropsThem': '{who} наезжает на шипы',
  'log.pulseNone': 'Ваш импульс излучателя никого не задел',
  'log.pulseYours': 'Ваш импульс излучателя отключает {who, case, acc}',
  'log.pulseTheirs': 'Импульс излучателя {who, case, gen} отключает ваш грузовик на {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'log.cookOffYours': 'Ваш таран-клеймор ломается и взрывается',
  'log.cookOffTheirs': 'Таран-клеймор {who, case, gen} ломается и взрывается',
  'log.obstacle.rock': 'камень',
  'log.obstacle.wreck': 'обломки',
  'log.obstacle.building': 'здание',
  'log.obstacle.water': 'воду',
  'log.obstacle.site': 'постройку',
  'log.obstacle.landmark': 'ориентир',
  'log.claymoreWallYours': 'Ваш таран-клеймор врезается в {what} и взрывается',
  'log.claymoreWallTheirs': 'Таран-клеймор {who, case, gen} врезается в {what} и взрывается',
  'log.claymoreYours': 'Ваш таран-клеймор накрывает {whom, case, acc}',
  'log.claymoreYou': 'Таран-клеймор {who, case, gen} накрывает ваш грузовик',
  'log.claymoreTheirs': 'Таран-клеймор {who, case, gen} накрывает {whom, case, acc}',
  'log.cargoSpilledOther': 'Груз {who, case, gen} рассыпался по земле',
  'log.cargoSpilledYours': '{part} {part, gender, m {сломался} f {сломалась} n {сломалось} pl {сломались}}. {n, plural, one {Выпал # предмет} few {Выпало # предмета} many {Выпало # предметов} other {Выпало # предмета}}.',
  'log.harpoon': '{gun} → {target}: {what}',
  'log.harpoonLine': 'трос зацепил {part, case, acc}',
  'log.harpoonMissed': 'промах',
  'log.lineTornYou': 'Вы вырываетесь из гарпунного троса',
  'log.lineTornThem': '{who} вырывается из гарпунного троса',
  'newGame.mode': 'Режим игры',
  'newGame.settings': 'Настройки мира',
  'newGame.start': 'Начать',
  'newGame.back': 'Назад',
  'newGame.reset': 'Сбросить настройки',
  'newGame.default': 'по умолчанию {pct}',
  'setup.part': '{setting} {pct}',
  'setting.percent': '{n}%',
  'cell.deadRows': 'Сломанные ряды груза. Почините грузовую деталь, чтобы пользоваться ими.',
  'kind.utility': 'оборудование',
  'menu.showTips': 'Показывать советы',
  'menu.showTipsOn': '✓ Показывать советы',
  'menu.closeEsc': 'Закрыть [Esc]',
  'menu.waitForTurn': 'Дождитесь конца хода',
  'help.group.drive': 'Езда',
  'help.group.places': 'Места и разговоры',
  'help.group.fight': 'Бой',
  'help.group.view': 'Обзор',
  'help.key.click': 'Клик',
  'help.key.shift': 'Shift',
  'help.key.space': 'Пробел',
  'help.key.holdSpace': 'Удерживать Пробел',
  'help.key.rightDrag': 'Правая кнопка',
  'help.key.wheel': 'Колесо',
  'help.on.ground': 'по земле',
  'help.on.yourTruck': 'по своему грузовику',
  'help.on.townOrSite': 'по городу или месту',
  'help.on.pad': 'на площадке',
  'help.on.truck': 'по грузовику',
  'help.to': '–',
  'help.does.driveByRoad': 'Ехать по дороге',
  'help.does.stopThere': 'Остановиться там',
  'help.does.driveOrPause': 'Ехать или пауза',
  'help.does.fastForward': 'Ускорить',
  'help.does.brake': 'Тормоз',
  'help.does.manual': 'Ручное вождение',
  'help.does.autoPatch': 'Авторемонт',
  'help.does.stopAtPad': 'Встать на площадку',
  'help.does.padWork': 'Торговля, ремонт или добыча',
  'help.does.radio': 'Вызвать по рации осмотренный грузовик',
  'help.does.reply': 'Ответ',
  'help.does.honk': 'Гудок',
  'help.does.inspectOrAim': 'Осмотр или наведение',
  'help.does.pickWeapon': 'Выбрать оружие',
  'help.does.allWeapons': 'Всё оружие',
  'help.does.autoFire': 'Автоогонь',
  'help.does.showWeapons': 'Показать оружие',
  'help.does.pan': 'Обзор',
  'help.does.zoom': 'Масштаб',
  'help.does.center': 'К грузовику',
  'help.does.camera': 'Камера',
  'help.does.mute': 'Звук',
  'help.does.inventory': 'Инвентарь',
  'help.does.character': 'Персонаж',
  'help.does.journal': 'Журнал',
  'hitTip.weapon': 'Расшатанное оружие',
  'hitTip.range': 'Далеко',
  'hitTip.recoil': 'Отдача',
  'hitTip.skill': 'Внимательность водителя',
  'hitTip.weather': 'Плохая погода',
  'hitTip.smoke': 'Дым',
  'hitTip.mine.crossing': 'Цель быстро пересекает курс',
  'hitTip.mine.own': 'Вы в движении',
  'hitTip.mine.still': 'Цель стоит',
  'hitTip.theirs.crossing': 'Вы быстро пересекаете курс',
  'hitTip.theirs.own': 'Он в движении',
  'hitTip.theirs.still': 'Вы стоите',
  'hitTip.base': 'Базовый шанс',
  'hit.wellYou': 'Вы',
  'hit.wellThem': 'Они',
  'weapon.turnPlaying': 'Ход идёт',
  'weapon.reloadBroken': 'Сломано',
  'weapon.reloadBusy': 'Идёт перезарядка',
  'weapon.reloadFull': 'Магазин полон',
  'weapon.noHoldTarget': 'Цели нет',
  'weapon.statusReady': 'Готово',
  'weapon.switchShow': 'Показать',
  'weapon.switchHide': 'Скрыть',
  'weapon.autoFire': 'Автоогонь',
  'weapon.autoOff': 'Выкл.',
  'weapon.autoSwitchTitle': 'Оружие само стреляет по врагам [Q]',
  'weapon.allOn': 'Всё',
  'weapon.allOff': 'Одно',
  'weapon.allSwitchTitle': 'Навести всё оружие [0]',
  'weapon.holdHint': 'Выключить автоогонь и сбросить цель этого оружия',
  'utility.aiming': 'наведение',
  'character.xpPoolTitle': 'Опыт на покупку рангов',
  'character.maxRank': 'Макс.',
  'character.colSkill': 'Навык',
  'character.colRank': 'Ранг',
  'hint.closeThis': 'Закрыть совет',
  'hint.turnOff': 'Выключить советы',
  'hit.deltaUp': '+{n}%',
  'hit.deltaDown': '−{n}%',
  'weapon.hitChanceOn': 'Шанс попасть: {target, case, acc}',
  'weapon.reloadHint': 'Сбросить магазин и снарядить заново за {n, plural, one {# ход} few {# хода} many {# ходов} other {# хода}}',
  'character.xpPool': '{n} опыта',
  'character.buyShort': 'Купить за {cost} опыта',
  'character.colPerk': 'Перк {rank} ранга',
  'character.colToday': 'Сегодня, до {cap} опыта',
  'stat.value': '{text} {unit}',
  'stat.valueTight': '{text}{unit}',
  'actBlock.knockedOut': 'Без сознания',
  'actBlock.towed': 'На буксире',
  'actBlock.onRadio': 'В эфире',
  'hud.tipsOff': 'Подсказки выключены. Меню, Показывать подсказки, включит их снова.',
  'hud.douseBlock.noSupplies': 'Нужно припасов: {n}',
  'hud.douseBlock.engineCool': 'Двигатель холодный',
  'mode.furyRoad': 'Дорога ярости',
  'mode.furyRoad.description': 'Бесконечное шоссе на север от форпоста к форпосту.',
  'boot.nextWindow': 'Открываем дорогу на север',
  'death.wrecked': 'Грузовик разбит',
  'death.stranded': 'Вы застряли',
  'death.restartRun': 'Начать заезд заново',
  'death.runReached': '{mode}. Дошли до {site, case, gen}, {north} на север.',
  'death.runStart': '{mode}. Первый перегон, {north} на север.',
  'hud.confirmEndRun': 'Закончить заезд здесь? Это нельзя отменить.',
  'hud.endRun': 'Закончить заезд',
  'readout.run': 'Заезд',
  'readout.runValue': '{stretch}: {left}',
  'readout.runTip': 'Перегон {stretch}: {left} до {site, case, gen}',
  'log.outpostReached': '{site}. Заплатили {pay} за дорогу.',
  'log.outpostReachedWrecks': '{site}. Заплатили {pay} за дорогу и {n, plural, one {# разбитую машину} few {# разбитые машины} many {# разбитых машин} other {# разбитой машины}}.',
  'log.runWrecked': 'Грузовик разбит. Заезд окончен на {n}-м перегоне.',
  'log.runEnded': 'Вы закончили заезд на {n}-м перегоне.',
  'money.outpost': 'плата форпоста',
  'outpost.name': '{word} {n}',
  'outpost.word': noun('m', 'аванпост', 'аванпоста', 'аванпосту', 'аванпост', 'аванпостом', 'аванпосте'),
  'outpost.soldOut': 'Всё раскуплено',
  'outpost.waitForRoad': 'Ждать проезда',
  'action.enterOutpost': 'Въехать на {site, case, acc}',
  'units.km': '{n} км',
  'units.m': '{n} м',
};
