// Copies of the English text that saves of major format 2 held before minor format 20, with the id each became. The
// save step from 19 to 20 reads only these tables, so later text changes never move it. Phrases from earlier minor
// formats map to the id of the goal or line that replaced them.

// Goal reasons, as NpcActivity.reason held them.
export const GOAL_REASONS_2_19: Readonly<Record<string, string>> = {
  'the hold is full': 'holdFull',
  'the loot will not fit': 'lootWontFit',
  'take the spilled cargo': 'takeSpilledCargo',
  'salvage out of reach': 'salvageOutOfReach',
  'left its post': 'leftPost',
  'cannot wear the target down': 'cannotWearDown',
  'watched the road': 'watchedRoad',
  'ran from it': 'ranFromIt',
  'avoid a truck it ran from': 'avoidRanFrom',
  'break off a losing fight': 'breakOffFight',
  'cornered': 'cornered',
  'Explore': 'explore',
  'a foe in sight stops the repair': 'combatStopsRepair',
  'a foe in sight stops the search': 'combatStopsSearch',
  'arrived': 'arrived',
  'avoid a costly fight': 'avoidCostlyFight',
  'bring fuel and supplies': 'bringAid',
  'buy profitable cargo': 'buyCargo',
  'cannot afford trade cargo': 'cannotAffordCargo',
  'cannot drive': 'cannotDrive',
  'cargo cannot hold salvage': 'cargoFullSalvage',
  'cargo cannot hold the load': 'cargoFullLoad',
  'cargo cannot hold the loot': 'cargoFullLoot',
  'chose something new': 'choseNew',
  'collect visible salvage': 'collectSalvage',
  'combat stops the looting': 'combatStopsLooting',
  'combat stops the repair': 'combatStopsRepair',
  'combat stops the search': 'combatStopsSearch',
  'could not get through to the truck': 'towUnanswered',
  'damaged and threatened': 'damagedThreatened',
  'defend its claimed loot': 'defendLoot',
  'deliver purchased cargo': 'deliverCargo',
  'dropped the tow': 'droppedTow',
  'escape a threat': 'escapeThreat',
  'escape an attacker': 'escapeAttacker',
  'explore the open map': 'explore',
  'explored the spot': 'exploredSpot',
  'fight a hostile in sight': 'fightHostile',
  'fight back': 'fightBack',
  'finished field repairs': 'finishedRepairs',
  'finished service': 'finishedService',
  'fit again': 'fitAgain',
  'follow its leader': 'followLeader',
  'found nothing at the contact': 'foundNothing',
  'heard a hostile beyond sight': 'heardHostile',
  'help a stranded truck': 'helpStranded',
  'home to lie up': 'homeToLieUp',
  'in combat': 'inCombat',
  'keep its word': 'keepWord',
  'lie up for fresh gear': 'lieUp',
  'load cargo at its source': 'loadCargo',
  'look for prey at known hunting grounds': 'raid',
  'loot a knocked-out truck': 'lootDowned',
  'loot salvage on the way': 'lootOnTheWay',
  'loot the robbed truck': 'lootRobbed',
  'lost sight of the salvage': 'lostSalvage',
  'lost the target': 'lostTarget',
  'low fuel': 'lowFuel',
  'low supplies': 'lowSupplies',
  'make a trip to another site': 'tripToSite',
  'needs repairs': 'needsRepairs',
  'no free point to explore': 'noExplorePoint',
  'no gun left to fight with': 'noGun',
  'no hostile in sight': 'noHostile',
  'no longer follows its leader': 'leftLeader',
  'no progress for too long': 'noProgress',
  'nothing left to loot': 'nothingToLoot',
  'nothing worth doing': 'nothingToDo',
  'nowhere farther to run': 'nowhereToRun',
  'patch a stranded truck': 'patchTruck',
  'patch a truck': 'patchTruck',
  'patch damaged parts': 'patchParts',
  'patrol the roads near camp': 'patrolCamp',
  'patrol the roads near town': 'patrolTown',
  'patrolled the road': 'patrolledRoad',
  'pick up fuel and supplies': 'pickUpAid',
  'prowl the roads for wrecks': 'prowl',
  'prowled the road': 'prowledRoad',
  'pull over to trade': 'pullOver',
  'reached hunting ground': 'reachedGround',
  'refitted at home': 'refitted',
  'refuse a threat': 'refuseThreat',
  'retreat home after a defeat': 'retreatHome',
  'rob cargo': 'robCargo',
  'salvage exhausted': 'salvageExhausted',
  'salvage no longer available': 'salvageGone',
  'search a known salvage site': 'searchSite',
  'search a loot spot': 'searchSpot',
  'sell carried cargo': 'sellCargo',
  'sold cargo': 'soldCargo',
  'someone else is looting it': 'lootTaken',
  'spotted the truck it heard': 'spottedHeard',
  'stranded, gave up the robbery': 'strandedRobbery',
  'take the claimed loot': 'takeClaimedLoot',
  'take the handed-over cargo': 'takeHandedCargo',
  'the contact is gone': 'contactGone',
  'the loot is claimed': 'lootClaimed',
  'the loot is gone': 'lootGone',
  'the meeting is off': 'meetingOff',
  'the patch is off': 'patchOff',
  'the player drove away from the tow offer': 'towOfferLeft',
  'the tow is off': 'towOff',
  'the truck got away': 'truckGotAway',
  'the truck needs no tow anymore': 'towNotNeeded',
  'tow a stranded truck': 'towStranded',
  'tow the player to town': 'towPlayer',
  'towed a stranded truck': 'towedStranded',
  'towed the player to town': 'towedPlayer',
  'unfit to hunt': 'unfitToHunt',
  'wait for a patch': 'waitPatch',
  'wait for a tow': 'waitTow',
  'wait for an answer to a tow offer': 'waitTowAnswer',
  'warned off the loot': 'warnedOff',
};

// Radio lines, as the open call's line held them.
export const LINES_2_19: Readonly<Record<string, string>> = {
  'A wreck nobody picked clean, {bearing} of you, about {distance} out.': 'aWreckNobodyPicked',
  'Agreed. Guns down.': 'agreedGunsDown',
  'All right! It is on the ground. Now leave us alone.': 'allRightItIs',
  'All right. I am done. Take what you want.': 'allRightIAm',
  'All right. It is on the ground. Let me go.': 'allRightItIs',
  'Already said.': 'alreadySaid',
  'Anything interesting?': 'anythingInteresting',
  'Busy here! Off the channel.': 'busy',
  'Clear the channel.': 'clearTheChannel',
  'Come and get it.': 'comeAndGetIt',
  'Come and take it.': 'comeAndTakeIt',
  'Deal.': 'dealPlain',
  'Deal. Hitch me up.': 'dealHitchMeUp',
  'Deal. Hitch up.': 'dealHitchUp',
  'Deal. I will stay put.': 'dealIWillStay',
  'Deal. Pull over and wait.': 'dealPullOverAnd',
  'Deal. Sending it.': 'dealSendingIt',
  'Deal. Stay where you are.': 'dealStayWhereYou',
  'Drop your cargo, or we open fire.': 'dropYourCargoOr',
  'Dump your cargo and drive off.': 'dumpAndDrive',
  'Dump your cargo and roll on. Or we take it off your wreck.': 'demandCargo',
  'Engine or gearbox. Can you do anything?': 'canYouDoAnything',
  'Engine or gearbox. What would it take?': 'whatWouldItTake',
  'Engine, gearbox or tank. Can you do anything?': 'canYouDoAnything',
  'Engine, gearbox or tank. What would it take?': 'whatWouldItTake',
  'Enough of this. We both drive away.': 'enoughOfThisWe',
  'Enough shooting. Can we call a truce?': 'enoughShootingCanWe',
  'Find your own wreck.': 'findYourOwnWreck',
  'Finders keepers.': 'findersKeepers',
  'Fine. It\'s yours.': 'fineItsYours',
  'Fine. Keep your guns down.': 'fineKeepYourGuns',
  'Fine. Take it.': 'fineTakeIt',
  'Fine. Thanks for the pull.': 'fineThanksForThe',
  'Get lost.': 'getLost',
  'Get off my channel.': 'getOffMyChannel',
  'Go ahead.': 'goAhead',
  'Going.': 'going',
  'Good.': 'good',
  'Hang up.': 'hangUp',
  'Have it your way.': 'haveItYourWay',
  'Heard you the first time.': 'heardYouTheFirst',
  'Heard you.': 'heardYou',
  'Heh. No.': 'hehNo',
  'Hold on. I am coming over.': 'holdOnIAm',
  'How are prices in town?': 'howArePricesIn',
  'I am letting you off the rope here.': 'iAmLettingYou',
  'I am listening.': 'iAmListening',
  'I am running dry. Can you spare some?': 'iAmRunningDry',
  'I am stranded. Can you tow me?': 'iAmStrandedCan',
  'I can pull you to {town}. No charge.': 'pullFree',
  'I can pull you to {town}. {fee} when we get there.': 'pullPaid',
  'I can spare {aid}. Stay put, I am coming.': 'iCanSpareAid',
  'I cannot help, sorry.': 'iCannotHelpSorry',
  'I could use {aid}. I can pay {price}.': 'iCouldUseAid',
  'I give up. Let me go.': 'iGiveUpLet',
  'I told you already.': 'iToldYouAlready',
  'Keep it short.': 'keepItShort',
  'Keep off this channel.': 'keepOffThisChannel',
  'Last I was in {town}: {prices}.': 'lastIWasIn',
  'Leave it on the ground and go.': 'leaveItOnThe',
  'Let me check my tanks.': 'letMeCheckMy',
  'Let me hear what broke.': 'letMeHearWhat',
  'Listening.': 'listening',
  'Make it short.': 'makeItShort',
  'Maybe. I passed something on my way.': 'maybeIPassedSomething',
  'Money is in. Guns down.': 'moneyIsInGuns',
  'Move along.': 'moveAlong',
  'My engine is dead out here. Can you patch me up?': 'myTruckIsDead',
  'My truck is broken down. Can you patch it?': 'myTruckIsBroken',
  'My truck is dead out here. Can you patch me up?': 'myTruckIsDead',
  'Need a tow to town?': 'needATowTo',
  'Never mind.': 'neverMind',
  'No charge.': 'noCharge',
  'No charge. Hitch up.': 'noChargeHitchUp',
  'No deals.': 'noDeals',
  'No free ride. Dump your cargo and roll on, and we call it square.': 'noFreeRideDump',
  'No mercy.': 'noMercy',
  'No thanks.': 'noThanks',
  'No time. Out.': 'noTimeOut',
  'No. We finish this.': 'noWeFinishThis',
  'Not interested.': 'notInterested',
  'Not now. Something else.': 'notNowSomethingElse',
  'Not talking.': 'notTalking',
  'Not today!': 'notTodayRun',
  'Not today.': 'notToday',
  'Not while I can still pull a trigger.': 'notWhileICan',
  'Not with what I have. Sorry.': 'notWithWhatI',
  'Nothing for you.': 'nothingForYou',
  'Nothing to say to you.': 'nothingToSayTo',
  'Old news, friend.': 'oldNewsFriend',
  'On second thought, I cannot.': 'onSecondThoughtI',
  'Over and out.': 'overAndOut',
  'Over my dead body.': 'overMyDeadBody',
  'Pulling over.': 'pullingOver',
  'Rolling on.': 'rollingOn',
  'Run, then.': 'runThen',
  'Running low? I can spare some.': 'runningLowICan',
  'Said that already.': 'saidThatAlready',
  'Say that again?': 'sayThatAgain',
  'Says who?': 'saysWho',
  'Seen anything worth a look out there?': 'seenAnythingWorthA',
  'Sit tight.': 'sitTight',
  'Smart choice.': 'smartChoice',
  'Sorry. Cannot spare any.': 'sorryCannotSpareAny',
  'Speak up.': 'speakUp',
  'Stand down and let me strip your truck.': 'standDownAndLet',
  'Standing down.': 'standingDown',
  'State your business.': 'stateYourBusiness',
  'Stop shooting! I give up. Take what I carry and let me go.': 'stopShootingIGive',
  'Sure. Pull over and I will come alongside.': 'surePullOverAnd',
  'Take me to {site}. I can pay {fee} when we get there.': 'takeMeToSite',
  'Take what I carry. Just let me drive away.': 'takeWhatICarry',
  'Talk fast.': 'talkFast',
  'Talk.': 'talk',
  'Thanks. I will wait.': 'thanksIWillWait',
  'Thanks. Over and out.': 'thanksOverAndOut',
  'Thanks. Something else.': 'thanksSomethingElse',
  'That pile is mine. Roll on.': 'thisIsMine',
  'Then come and get me.': 'thenComeAndGet',
  'Then we finish this.': 'thenWeFinishThis',
  'This is mine.': 'thisIsMine',
  'This wreck is mine. Back off.': 'thisWreckIsMine',
  'Too late for talk.': 'tooLateForTalk',
  'Too much.': 'tooMuch',
  'Understood.': 'understood',
  'Want to trade?': 'wantToTrade',
  'We already talked about that.': 'weAlreadyTalkedAbout',
  'We both drive away.': 'weBothDriveAway',
  'We covered that.': 'weCoveredThat',
  'We will see.': 'weWillSee',
  'What are you offering?': 'whatAreYouOffering',
  'What can you offer?': 'whatCanYouOffer',
  'What do you want?': 'whatDoYouWant',
  'What would it cost to call this off?': 'whatWouldItCost',
  'Whatever you can spare.': 'whateverYouCanSpare',
  'Where is the nearest town?': 'whereIsTheNearest',
  'Where?': 'where',
  'Yeah? Make it quick.': 'yeahMakeItQuick',
  'You are not worth the trouble.': 'spare',
  'You heard me. Cargo on the ground, now.': 'youHeardMeCargo',
  'You heard me. Leave it.': 'youHeardMeLeave',
  'You know how? Then name it.': 'youKnowHowThen',
  'You look dry. I can spare {aid}, no charge.': 'youLookDryI',
  'You said that.': 'youSaidThat',
  'You want my truck stripped?': 'youWantToPick',
  'You want to pick my truck clean?': 'youWantToPick',
  'Your call. Last chance.': 'yourCallLastChance',
  'Your engine sounds rough. Want me to patch it before it quits?': 'yourEngineSoundsRough',
  'Your funeral.': 'yourFuneral',
  'Your truck is dead in the road. Stand down and we both drive on.': 'giveUpOffer',
  'Your truck is dead in the road. Stand down and we both drive on. Or I shoot for your cab.': 'giveUpOffer',
  'Your truck is dead. Hand over the cargo and your best parts, and you keep the truck. Or I shoot for your cab.': 'surrenderOffer',
  'Your truck is dead. Hand over the cargo and your best parts, and you keep the truck. Refuse, and I take it off your wreck.': 'surrenderOffer',
  'Your truck is finished. Dump your cargo and your best parts, and drive off alive.': 'yourTruckIsFinished',
  'Your truck is finished. Stand down and let me strip it, and you live.': 'yourTruckIsFinished',
  'Your truck looks dead. Want me to patch it?': 'yourTruckLooksDead',
  '{deal}': 'dealTerms',
  '{price}, and we forget it.': 'truceCost',
  '{site} lies {bearing} of you, about {distance} out.': 'siteBearing',
  '{tip}': 'tipTold',
  '{town} lies {bearing} of you, about {distance} out.': 'townBearing',
};
