// The event log, the words of jobs, states and contracts, and the words of the sim's ids.
import { m } from '../msg';

export const LOG = {
  // Job and work labels.
  'job.search': 'Search',
  'job.weld': 'Weld scrap armor',
  'job.somePart': 'part',
  'job.repair': m('Repair {part}', { part: 'text' }),
  'job.strip': m('Strip {part}', { part: 'text' }),
  'job.theTruck': 'the truck',
  'job.remove': m('Remove {part} from {truck}', { part: 'text', truck: 'text' }),
  'job.refit': m('Refit {parts}', { parts: 'text' }),
  'job.refitNothing': 'Refit',
  'job.patch': m('Patch {truck}', { truck: 'text' }),
  'job.patchedBy': m('Patched by {truck}', { truck: 'text' }),
  'job.takingFromYou': m('Taking {goods} from you', { goods: 'text' }),
  'job.givingYou': m('Giving you {goods}', { goods: 'text' }),
  'job.givingTo': m('Giving {goods} to {truck}', { goods: 'text', truck: 'text' }),
  'job.takingFrom': m('Taking {goods} from {truck}', { goods: 'text', truck: 'text' }),
  // Part condition.
  'cond.junk': 'junk',
  'cond.pristine': 'pristine',
  'cond.rebuilt': m('rebuilt x{n}', { n: 'count' }),
  'cond.scrapOnly': 'scrap only',
  'cond.broken': 'broken',
  'cond.hp': m('{hp}/{max} HP', { hp: 'int', max: 'int' }),
  // Trucks in log lines.
  'log.you': 'You',
  'log.anObstacle': 'an obstacle',
  'log.something': 'something',
  // The hover panel over a truck.
  'npc.gaveUp': 'Gave up',
  'npc.knockedOut': 'Knocked out',
  'npc.letsPass': m('Lets you pass: {why}', { why: 'text' }),
  'log.preyPassed': m('{who} lets {prey} pass: {why}', { who: 'text', prey: 'text', why: 'text' }),
  'pass.nothing': 'nothing worth taking',
  'pass.busy': 'busy with another fight',
  'pass.outgunned': 'too tough to take on',
  'pass.poorLoad': 'load not worth the risk',
  'pass.chance': 'let you be this time',
  'npc.traits': m('Traits: {traits}', { traits: 'text' }),
  'npc.goodCount': m('{good} ×{n}', { good: 'text', n: 'int' }),
  'npc.cargoEmpty': 'Cargo: empty',
  'npc.cargo': m('Cargo: {goods}', { goods: 'text' }),
  'npc.spares': m('Spares: {spares}', { spares: 'text' }),
  'npc.cargoAndSpares': m('Cargo: {goods}. Spares: {spares}', { goods: 'text', spares: 'text' }),
  'npc.marked': m('Marked: {n, plural, one {# turn left} other {# turns left}}', { n: 'count' }),
  'npc.markKey': '[N] Mark',
  // States an NPC holds toward the player.
  'state.feud': 'Feud with you',
  'state.backedOff': 'Backing off from you',
  'state.towing': 'Towing you',
  'state.towOffer': 'Tow offer to you',
  'state.turnedDown': 'You turned down its tow',
  'state.towPromise': 'Promised you a tow',
  'state.answering': 'Coming to tow you',
  'state.patch': 'Patching your truck',
  'state.truce': 'Truce with you',
  'state.grievance': 'Angry at your crash',
  'state.pleaTruce': 'Asked you for a truce',
  'state.pleaMercy': 'Begged you for mercy',
  'state.trade': 'Pulling over to trade with you',
  'state.revenge': 'Wants revenge on you',
  'state.escort': 'Escorting you',
  'state.aidBringing': 'Bringing you fuel',
  'state.aidWaiting': 'Waiting for your fuel',
  'state.combat': 'In combat',
  'state.strayFire': m('Hit by your stray fire, {forgiven} of {of} damage forgiven', { forgiven: 'int', of: 'int' }),
  'state.lootWarning': 'Warning you off its loot',
  'state.lootAgreed': 'You agreed to leave its loot',
  'state.moving': m('Moving, {n} km/h', { n: 'int' }),
  'state.parked': 'Parked',
  'state.shutDown': 'Shut down',
  'state.join': m('{first}. {rest}', { first: 'text', rest: 'text' }),
  'loot.place.wreck': 'wreck',
  'loot.place.pile': 'pile',
  'loot.place.spot': 'spot',
  'loot.place.truck': 'truck',
  'log.lootYielded': m('{warner} warns {looter} off the {place}. {looter} rolls on.', { warner: 'text', looter: 'text', place: 'text' }),
  'log.lootBackedOff': m('{warner} warns {looter} off the {place}. {looter} stays put, and {warner} rolls on.', { warner: 'text', looter: 'text', place: 'text' }),
  'log.lootFight': m('{warner} warns {looter} off the {place}. They fight over it.', { warner: 'text', looter: 'text', place: 'text' }),
  'state.withTurns': m('{label}, {n, plural, one {# turn} other {# turns}}', { label: 'text', n: 'count' }),
  // Log lines.
  'log.feudExpired': m('{who} gives up the feud with you.', { who: 'text' }),
  'log.feudFulfilled': m('{who} ends the feud: you are beaten.', { who: 'text' }),
  'log.feudBroken': m('The feud with {who} is over.', { who: 'text' }),
  'log.backedOffExpired': m('{who} stops backing off from you.', { who: 'text' }),
  'log.aidExpired': m('The fuel deal with {who} ran out.', { who: 'text' }),
  'log.aidBroken': m('The fuel deal with {who} is off.', { who: 'text' }),
  'short.gun': 'Gun',
  'short.eng': 'Eng',
  'short.arm': 'Arm',
  'short.cargo': 'Cargo',
  'short.scan': 'Scan',
  'short.store': 'Store',
  'short.cab': 'Cab',
  'short.trans': 'Trans',
  'short.whl': 'Whl',
  'short.tank': 'Tank',
  'log.partDamage': m('{part}: {n}', { part: 'text', n: 'int' }),
  'log.critParts': m('Crit! {parts}', { parts: 'text' }),
  'log.strayHits': m(', stray fire hits {who}', { who: 'text' }),
  'log.shot': m('{gun} → {target}, {hits}/{rounds} hit', { gun: 'text', target: 'text', hits: 'int', rounds: 'int' }),
  'log.shotAt': m('{gun} → {target} at {part}, {hits}/{rounds} hit', { gun: 'text', target: 'text', part: 'text', hits: 'int', rounds: 'int' }),
  'log.shotChance': m(' ({pct}%)', { pct: 'int' }),
  'log.shotCrits': m(', {n} crit', { n: 'int' }),
  'log.hit': m('{part} −{n}', { part: 'text', n: 'int' }),
  'log.hitBroken': m('{part} −{n} broken', { part: 'text', n: 'int' }),
  'log.damageLead': ': ',
  'log.damageSep': ', ',
  'log.jobStarted': m('{what} started: stay parked about {n, plural, one {# turn} other {# turns}}.', { what: 'text', n: 'count' }),
  'log.jobCancelled': m('{what} cancelled: the truck moved, a hostile came in sight, or required items changed', { what: 'text' }),
  'log.jobDone': m('{what} done', { what: 'text' }),
  'log.weather.storm.started': 'Dust storm started',
  'log.weather.storm.ended': 'Dust storm ended',
  'log.weather.heatwave.started': 'Heat wave started',
  'log.weather.heatwave.ended': 'Heat wave ended',
  'log.weather.overcast.started': 'Overcast started',
  'log.weather.overcast.ended': 'Overcast ended',
  'log.youHonk': 'You honk.',
  'log.honksBack': m('{who} honks back.', { who: 'text' }),
  'log.hornUnseen': 'A horn answers out of sight.',
  'log.patchStartYou': m('You start patching {who}. Stay parked beside it.', { who: 'text' }),
  'log.patchStartThem': m('{who} starts patching your truck. Stay parked.', { who: 'text' }),
  'log.patchDoneYou': m('You patched {who}.', { who: 'text' }),
  'log.patchDoneThem': m('{who} patched your truck.', { who: 'text' }),
  'log.patchLapsed': m('The patch with {who} is off: nobody worked on it.', { who: 'text' }),
  'log.patchBroken': m('The patch with {who} is off.', { who: 'text' }),
  'log.aidNothing': m('Nothing changed hands with {who}.', { who: 'text' }),
  'log.aidPaid': m('{goods} for {paid}', { goods: 'text', paid: 'text' }),
  'log.aidYouGive': m('You give {who} {moved}.', { who: 'text', moved: 'text' }),
  'log.aidGivesYou': m('{who} gives you {moved}.', { who: 'text', moved: 'text' }),
  'log.aidStartYou': m('You start handing {who} the goods.', { who: 'text' }),
  'log.aidStartThem': m('{who} starts handing you the goods.', { who: 'text' }),
  'log.say': m('{who}: “{line}”', { who: 'text', line: 'text' }),
  'log.towOffer': m('{who} offers to tow you to {site} for {fee}.', { who: 'text', site: 'text', fee: 'text' }),
  'log.towOfferFree': m('{who} offers to tow you to {site} for free.', { who: 'text', site: 'text' }),
  'log.towHitched': m('{who} takes {client} in tow to {site}.', { who: 'text', client: 'text', site: 'text' }),
  'log.towedYouFree': m('{who} tows you into town for free.', { who: 'text' }),
  'log.towedYouPaid': m('{who} tows you into town and takes {fee}.', { who: 'text', fee: 'text' }),
  'log.towedFree': m('{who} tows {client} in for free.', { who: 'text', client: 'text' }),
  'log.towedPaid': m('{who} tows {client} in and takes {fee}.', { who: 'text', client: 'text', fee: 'text' }),
  'log.escortPaid': m('{client} pays {who} {fee} for the escort.', { client: 'text', who: 'text', fee: 'text' }),
  'log.escortHired': m('{client} hires {who} as escort to {site} for {fee}.', { client: 'text', who: 'text', site: 'text', fee: 'text' }),
  'log.escortRefused': m('{who} turns down an escort job from {client}.', { who: 'text', client: 'text' }),
  'log.plea.truce.granted': m('{who} asks for a truce from {to}: granted', { who: 'text', to: 'text' }),
  'log.plea.truce.refused': m('{who} asks for a truce from {to}: refused', { who: 'text', to: 'text' }),
  'log.plea.mercy.granted': m('{who} begs for mercy from {to}: granted', { who: 'text', to: 'text' }),
  'log.plea.mercy.refused': m('{who} begs for mercy from {to}: refused', { who: 'text', to: 'text' }),
  'log.towGone': m('{who} is gone. {client} is off the rope.', { who: 'text', client: 'text' }),
  'log.towDropped': m('{who} drops the tow of {client}.', { who: 'text', client: 'text' }),
  'log.towDroppedYou.refused': m('You turn down the tow from {who}.', { who: 'text' }),
  'log.towDroppedYou.unhitched': m('You unhitch from {who}.', { who: 'text' }),
  'log.towDroppedYou.danger': m('{who} drops the tow. There is danger.', { who: 'text' }),
  'log.towDroppedYou.stranded': m('{who} can no longer drive. The tow is off.', { who: 'text' }),
  'log.towDroppedYou.gone': m('{who} is gone. The tow is off.', { who: 'text' }),
  'log.towDroppedYou.blocked': m('{who} cannot get through to you. The tow is off.', { who: 'text' }),
  'log.searchDoneAt': m('Search done at {site}.', { site: 'text' }),
  'log.searchDone': 'Search done.',
  'log.contract.accepted': m('Contract taken: {what}, pays {reward}', { what: 'text', reward: 'text' }),
  'log.contract.done': m('Contract done: {what}, pays {reward}', { what: 'text', reward: 'text' }),
  'log.contract.failed': m('Contract failed: {what}, pays {reward}', { what: 'text', reward: 'text' }),
  'log.contract.lapsed': m('Contract lapsed: {what}, pays {reward}', { what: 'text', reward: 'text' }),
  'log.contract.expiring': m('Contract due soon: {what}, {due}', { what: 'text', due: 'text' }),
  'log.contract.fulfilled': m('Bounty met: {target} beaten, claim {reward} at {site}', { target: 'text', reward: 'text', site: 'text' }),
  'log.rankBought': m('{skill} rank {rank} bought.', { skill: 'text', rank: 'int' }),
  'log.rankBoughtPerk': m('{skill} rank {rank} bought. Perk ready [C].', { skill: 'text', rank: 'int' }),
  'log.debugActivity': m('{who}: {what} — {why}', { who: 'text', what: 'text', why: 'text' }),
  'log.debugStall': m('Bug: {who} stuck on {what} ({why}), gave it up', { who: 'text', what: 'text', why: 'text' }),
  'log.moneyGain': m('+{n}: {reason}', { n: 'text', reason: 'text' }),
  'log.moneyLoss': m('−{n}: {reason}', { n: 'text', reason: 'text' }),
  'log.guardShot': m('{site} guards → {target}, {hits}/{rounds} hit', { site: 'text', target: 'text', hits: 'int', rounds: 'int' }),
  'log.discovered': m('Discovered {site}', { site: 'text' }),
  'log.partDisabled': m('{who}: {part} disabled', { who: 'text', part: 'text' }),
  'log.breakdown': m('{part} broke down', { part: 'text' }),
  'log.townPatch': 'You patch your truck with scrap.',
  'log.scrapPatch': 'You patch up your car with scrap until it starts moving again.',
  'log.scrapPatchFuel': m('You patch up your car with scrap until it starts moving again. Townsfolk spare you {liters} L of fuel.', { liters: 'int' }),
  'log.npcKnockout': m('{who} knocked out', { who: 'text' }),
  'log.npcWake': m('{who} regains consciousness', { who: 'text' }),
  'log.destroyed': m('{who} destroyed', { who: 'text' }),
  'log.hostile': m('{who} turns hostile to you', { who: 'text' }),
  'log.death': 'You died.',
  'log.knockout': 'You are knocked out.',
  'log.wake': 'You come to.',
  // Contracts.
  'contract.haul': m('Haul {n, plural, one {# crate} other {# crates}} of {good} to {site}', { n: 'count', good: 'text', site: 'text' }),
  'contract.rushHaul': m('Rush: Haul {n, plural, one {# crate} other {# crates}} of {good} to {site}', { n: 'count', good: 'text', site: 'text' }),
  'contract.fetch': m('Bring {part} to {site}: working, {n, plural, one {rebuilt at most once} other {rebuilt at most # times}}', { part: 'text', site: 'text', n: 'count' }),
  'contract.bounty': m('Knock out or wreck any {target}', { target: 'text' }),
  'contract.bountyAt': m('Knock out or wreck any {target}, claim at {site}', { target: 'text', site: 'text' }),
  'contract.bountyMet': m('{target} beaten, claim at {site}', { target: 'text', site: 'text' }),
  'contract.ready': 'Ready',
  'contract.window': m('{h} h', { h: 'int' }),
  'contract.due': m('by {when}', { when: 'text' }),
  // The game clock.
  'clock.day': m('Day {day}', { day: 'int' }),
  'clock.full': m('Day {day} {time}', { day: 'int', time: 'text' }),
  // The goods table.
  'goods.good': 'Good',
  'goods.theirs': 'Theirs',
  'goods.buy': 'Buy',
  'goods.sell': 'Sell',
  'goods.held': 'Held',
  'goods.profit': 'Profit/crate',
  'goods.crateNote': m('Prices are per {mass} crate. One crate fills one cargo cell.', { mass: 'text' }),
  'goods.profitTitle': 'Per unit: sell price here minus your average cost. Salvaged and hauled goods count at their usual value.',
  'goods.unknown': '?',
  'goods.even': '0',
  'goods.gain': m('+{n}', { n: 'int' }),
  'goods.loss': m('−{n}', { n: 'int' }),
  'goods.noCost': 'No cost on record',
  'goods.avgCost': m('Avg cost {cost}', { cost: 'text' }),
  'goods.buyLot': m('Buy {n} for {total} total', { n: 'int', total: 'text' }),
  'goods.sellLot': m('Sell all {n} for {total} total', { n: 'int', total: 'text' }),
  // The log panel.
  'log.stamped': m('{time} {line}', { time: 'text', line: 'text' }),
  'log.title': 'Log',
  'log.panel': 'Event log',
  'log.expand': 'Expand log',
  'log.shrink': 'Shrink log',
  // Why a driver took up or ended a goal. A seen driver's goal shows under its name.
  'goal.arrived': 'Arrived',
  'goal.avoidCostlyFight': 'Avoid a costly fight',
  'goal.bringAid': 'Bring fuel and supplies',
  'goal.buyCargo': 'Buy profitable cargo',
  'goal.cannotAffordCargo': 'Cannot afford trade cargo',
  'goal.cannotDrive': 'Cannot drive',
  'goal.cargoFullLoad': 'Cargo cannot hold the load',
  'goal.cargoFullLoot': 'Cargo cannot hold the loot',
  'goal.cargoFullSalvage': 'Cargo cannot hold salvage',
  'goal.choseNew': 'Chose something new',
  'goal.collectSalvage': 'Collect visible salvage',
  'goal.combatStopsLooting': 'Combat stops the looting',
  'goal.combatStopsRepair': 'Combat stops the repair',
  'goal.combatStopsSearch': 'Combat stops the search',
  'goal.contactGone': 'The contact is gone',
  'goal.damagedThreatened': 'Damaged and threatened',
  'goal.defendLoot': 'Defend its claimed loot',
  'goal.deliverCargo': 'Deliver purchased cargo',
  'goal.droppedTow': 'Dropped the tow',
  'goal.escapeAttacker': 'Escape an attacker',
  'goal.escapeThreat': 'Escape a threat',
  'goal.explore': 'Explore',
  'goal.exploredSpot': 'Explored the spot',
  'goal.fightBack': 'Fight back',
  'goal.fightHostile': 'Fight a hostile in sight',
  'goal.finishedRepairs': 'Finished field repairs',
  'goal.finishedService': 'Finished service',
  'goal.fitAgain': 'Fit again',
  'goal.followLeader': 'Follow its leader',
  'goal.foundNothing': 'Found nothing at the contact',
  'goal.heardHostile': 'Heard a hostile beyond sight',
  'goal.springOnPrey': 'Spring on prey it heard',
  'goal.helpStranded': 'Help a stranded truck',
  'goal.homeToLieUp': 'Home to lie up',
  'goal.idle': 'Idle',
  'goal.inCombat': 'In combat',
  'goal.keepWord': 'Keep its word',
  'goal.leftLeader': 'No longer follows its leader',
  'goal.legacy': 'Busy',
  'goal.lieUp': 'Lie up for fresh gear',
  'goal.loadCargo': 'Load cargo at its source',
  'goal.lootClaimed': 'The loot is claimed',
  'goal.lootDowned': 'Loot a knocked-out truck',
  'goal.lootGone': 'The loot is gone',
  'goal.lootOnTheWay': 'Loot salvage on the way',
  'goal.lootRobbed': 'Loot the robbed truck',
  'goal.lootTaken': 'Someone else is looting it',
  'goal.lostSalvage': 'Lost sight of the salvage',
  'goal.lostTarget': 'Lost the target',
  'goal.lowFuel': 'Low fuel',
  'goal.lowSupplies': 'Low supplies',
  'goal.meetingOff': 'The meeting is off',
  'goal.needsRepairs': 'Needs repairs',
  'goal.noExplorePoint': 'No free point to explore',
  'goal.noGun': 'No gun left to fight with',
  'goal.noHostile': 'No hostile in sight',
  'goal.noProgress': 'No progress for too long',
  'goal.nothingToDo': 'Nothing worth doing',
  'goal.nothingToLoot': 'Nothing left to loot',
  'goal.nowhereToRun': 'Nowhere farther to run',
  'goal.patchOff': 'The patch is off',
  'goal.patchParts': 'Patch damaged parts',
  'goal.patchTruck': 'Patch a truck',
  'goal.patrolCamp': 'Patrol the roads near camp',
  'goal.patrolTown': 'Patrol the roads near town',
  'goal.patrolledRoad': 'Patrolled the road',
  'goal.pickUpAid': 'Pick up fuel and supplies',
  'goal.prowl': 'Prowl the roads for wrecks',
  'goal.prowledRoad': 'Prowled the road',
  'goal.pullOver': 'Pull over to trade',
  'goal.raid': 'Look for prey at known hunting grounds',
  'goal.reachedGround': 'Reached hunting ground',
  'goal.refitted': 'Refitted at home',
  'goal.refuseThreat': 'Refuse a threat',
  'goal.retreatHome': 'Retreat home after a defeat',
  'goal.robCargo': 'Rob cargo',
  'goal.salvageExhausted': 'Salvage exhausted',
  'goal.salvageGone': 'Salvage no longer available',
  'goal.searchSite': 'Search a known salvage site',
  'goal.searchSpot': 'Search a loot spot',
  'goal.sellCargo': 'Sell carried cargo',
  'goal.soldCargo': 'Sold cargo',
  'goal.spottedHeard': 'Spotted the truck it heard',
  'goal.strandedRobbery': 'Stranded, gave up the robbery',
  'goal.takeClaimedLoot': 'Take the claimed loot',
  'goal.takeHandedCargo': 'Take the handed-over cargo',
  'goal.towNotNeeded': 'The truck needs no tow anymore',
  'goal.towOff': 'The tow is off',
  'goal.towOfferLeft': 'The player drove away from the tow offer',
  'goal.towPlayer': 'Tow the player to town',
  'goal.towStranded': 'Tow a stranded truck',
  'goal.towUnanswered': 'Could not get through to the truck',
  'goal.towedPlayer': 'Towed the player to town',
  'goal.towedStranded': 'Towed a stranded truck',
  'goal.tripToSite': 'Make a trip to another site',
  'goal.truckGotAway': 'The truck got away',
  'goal.unfitToHunt': 'Unfit to hunt',
  'goal.waitPatch': 'Wait for a patch',
  'goal.waitTow': 'Wait for a tow',
  'goal.waitTowAnswer': 'Wait for an answer to a tow offer',
  'goal.warnedOff': 'Warned off the loot',
  'goal.holdFull': 'The hold is full',
  'goal.lootWontFit': 'The loot will not fit',
  'goal.takeSpilledCargo': 'Take the spilled cargo',
  'goal.salvageOutOfReach': 'Salvage out of reach',
  'goal.leftPost': 'Left its post',
  'goal.cannotWearDown': 'Cannot wear the target down',
  'goal.fightOverLoot': 'Fight over loot',
  'goal.looterWontLeave': 'The looter would not leave',
  'goal.warningUnanswered': 'No answer to its warning',
  'goal.defendPromisedLoot': 'Defend the loot it was promised',
  'goal.keepLoot': 'Keep its loot',
  'goal.searchOldHulks': 'Search old tank hulks',
  'goal.searchOldRuin': 'Search an old ruin',
  'goal.cornered': 'Cornered',
  'goal.defeated': 'Defeated',
  'goal.watchedRoad': 'Watched the road',
  'goal.ranFromIt': 'Ran from it',
  'goal.avoidRanFrom': 'Avoid a truck it ran from',
  'goal.breakOffFight': 'Break off a losing fight',
  // Notes the sim adds to the player's log.
  'note.engineHot': 'Engine running hot.',
  'note.engineOverheat': m('Engine overheated: engine -{hp} HP', { hp: 'int' }),
  'opening.stranded': 'You find yourself stranded in an unfamiliar land. Not your finest moment.',
  'note.overdriveCutOut': 'Overdrive cut out: the engine is too worn.',
  'note.engineDoused': m('Doused the engine: supplies -{supplies}', { supplies: 'int' }),
  'note.outOfSupplies': m('Out of supplies: health -{health}', { health: 'int' }),
  'note.noRoomFuel': m('No room for fuel: fuel -{fuel}', { fuel: 'dec1' }),
  'note.noRoomSupplies': m('No room for supplies: supplies -{supplies}', { supplies: 'dec1' }),
  'note.tankLeak': m('Fuel tank leaks: fuel -{fuel}', { fuel: 'dec1' }),
  'note.filledSupplies': m('Filled supplies at {site}', { site: 'text' }),
  'note.hazard': 'A sick heat rolls off the glowing core. Your skin crawls, and the wheel shakes in your hands.',
  'note.spawnBlocked': m('No free spot to spawn {template}', { template: 'text' }),
  // Why money moved, after the amount in the log.
  'money.contract': 'contract',
  'money.failedHaul': 'failed haul contract',
  'money.towing': m('towing {vehicle}', { vehicle: 'text' }),
  // Why the sim turned down a command.
  'refusal.noFit': 'Does not fit there',
  'refusal.inTheWay': 'Something is in the way',
  'refusal.armorOnly': 'Only armor fits on the sides',
  'refusal.badLayout': m('{cause}. Items would fall off the grid or overlap.', { cause: 'text' }),
  'refusal.itemGone': 'That item is gone',
  'refusal.refitRunning': 'Finish the refit before changing inventory',
  'refusal.twoInTheWay': 'More than one item is in the way',
  'refusal.refitItemMoved': 'An item needed for the refit has moved or disappeared',
  'refusal.builtInFixed': 'Built-in parts cannot be moved',
  'refusal.salvageOutOfReach': 'Salvage is no longer in reach',
  'refusal.salvagePartGone': 'The salvage part is no longer available',
  'refusal.builtInStays': 'Built-in parts stay on the truck',
  'refusal.emptyRackFirst': 'Empty that rack first',
  'refusal.truckOutOfReach': 'The truck is out of reach',
  'refusal.truckPartGone': 'The part is no longer on the truck',
  'refusal.looting.here': m('{by} is looting here', { by: 'text' }),
  'refusal.looting.wreck': m('{by} is looting this wreck', { by: 'text' }),
  'refusal.looting.truck': m('{by} is looting this truck', { by: 'text' }),
  'refusal.needsSpotter': 'Marking a truck needs the spotter perk',
  'refusal.cannotAct': 'You cannot act now',
  'refusal.noTruck': 'No other truck to mark',
  'refusal.unseen': 'You do not see that truck',
  'refusal.notActive.dead': 'You are dead',
  'refusal.notActive.knockedOut': 'You are knocked out',
  'refusal.topRank': m('{skill} is at the top rank', { skill: 'text' }),
  'refusal.needsXp': m('Needs {cost} XP, you have {have} XP', { cost: 'int', have: 'int' }),
  'refusal.failed': 'That did not work.',
  'refusal.noMoney': 'Not enough money',
  'refusal.noCargoRoom': 'Not enough cargo space',
  'refusal.theyHaveNoRoom': 'No room on their truck',
  'refusal.noSupplyRoom': 'No room for that much',
  'refusal.inCombat': 'Not while in combat',
  'refusal.stopFirst': 'Stop the truck first',
  'refusal.utilityPassive': m('{part} is passive and takes no order', { part: 'text' }),
  'refusal.utilityOrder.point': m('{part} needs a target point', { part: 'text' }),
  'refusal.utilityOrder.self': m('{part} takes no target, only a trigger', { part: 'text' }),
  'refusal.utilityBlocked': m('{part}: {reason}', { part: 'text', reason: 'text' }),
  // A counted call value with its unit.
  'unit.part': m('{n, plural, one {# part} other {# parts}}', { n: 'count' }),
  // Truck titles.
  'vehicle.yours': 'Your truck',
  'vehicle.npc': m('{profession} {driver}', { profession: 'text', driver: 'text' }),
};
