// Names by data id: parts, chassis, goods, places, ground, people, traits, factions, skills and perks.

export const NAMES = {
  // Parts by part id.
  'part.mg': 'MG turret',
  'part.shotgun': 'Shotgun',
  'part.longRifle': 'Long rifle',
  'part.flamer': 'Flamer',
  'part.pneumobolter': 'Pneumobolter',
  'part.slugCannon': 'Slug cannon',
  'part.heavyMg': 'Heavy MG',
  'part.cannon': 'Forward cannon',
  'part.amRifle': 'Anti-materiel rifle',
  'part.autocannon': 'Autocannon',
  'part.recoilless': 'Recoilless rifle',
  'part.battleRifle': 'Battle rifle',
  'part.gatling': 'Gatling MG',
  'part.rocketRack': 'Rocket rack',
  'part.sniperCannon': 'Sniper cannon',
  'part.grenadeLauncher': 'Grenade launcher',
  'part.tankGun': 'Tank gun',
  'part.flechette': 'Flechette gun',
  'part.stockEngine': 'Stock engine',
  'part.tunedEngine': 'Tuned V8',
  'part.flatFour': 'Light flat-four',
  'part.workhorseDiesel': 'Workhorse diesel',
  'part.racingV6': 'Racing V6',
  'part.heavyDiesel': 'Heavy diesel',
  'part.turbine': 'Turbine',
  'part.plates': 'Steel plates',
  'part.cage': 'Rebar cage',
  'part.ram': 'Ram bar',
  'part.scrapPanels': 'Scrap panels',
  'part.ceramicPlates': 'Ceramic plates',
  'part.spacedArmor': 'Spaced armor',
  'part.reinforcedCage': 'Reinforced cage',
  'part.plowRam': 'Plow ram',
  'part.steelPlate': 'Steel plate',
  'part.scrapSheet': 'Scrap sheet',
  'part.ceramicTile': 'Ceramic tile',
  'part.rack': 'Roof rack',
  'part.trailerBox': 'Cargo box',
  'part.panniers': 'Panniers',
  'part.flatbed': 'Flatbed extension',
  'part.lightFrame': 'Light cargo frame',
  'part.enclosedFrame': 'Enclosed cargo frame',
  'part.heavyFrame': 'Heavy cargo frame',
  'part.jerrycans': 'Jerrycan rack',
  'part.supplyLocker': 'Supply locker',
  'part.cab': 'Driver seat',
  'part.cabPickup': 'Cab',
  'part.cabHardtop': 'Hardtop cab',
  'part.transmission': 'Transmission',
  'part.transmissionMid': 'Truck transmission',
  'part.transmissionHeavy': 'Heavy transmission',
  'part.wheel': 'Wheel',
  'part.wheelMid': 'Truck wheel',
  'part.wheelHeavy': 'Heavy wheel',
  'part.tank': 'Small fuel tank',
  'part.tankLong': 'Fuel tank',
  'part.tankMid': 'Truck fuel tank',
  'part.tankHeavy': 'Armored fuel tank',
  'part.sprout': 'Sprout',
  'part.caltrops': 'Caltrops',
  'part.oilSpiller': 'Oil spiller',
  'part.patcherCrane': 'Patcher crane',
  'part.smokeMortar': 'Smoke mortar',
  'part.flareCannon': 'Flare cannon',
  'part.scrapersKnife': 'Scraper\'s knife',
  'part.emitter': 'Emitter',
  'part.harpoon': 'Harpoon',
  'part.claymoreRam': 'Claymore ram',
  'part.scanner': 'Radio scanner',
  // Chassis by chassis id.
  'chassis.scout': 'Scout pickup',
  'chassis.hauler': 'Hauler',
  'chassis.buggy': 'Buggy',
  'chassis.wagon': 'Gunwagon',
  'chassis.courier': 'Courier',
  'chassis.van': 'Utility van',
  'chassis.longbed': 'Longbed truck',
  'chassis.carrier': 'Armored carrier',
  'chassis.tractor': 'Heavy tractor',
  'chassis.jeep': 'Jeep',
  'chassis.convertible': 'Convertible',
  'chassis.bus': 'Bus',
  'chassis.loader': 'Wheel loader',
  'chassis.niva': 'Niva',
  'chassis.bukhanka': 'Bukhanka',
  'chassis.lincoln': 'Lincoln',
  // Goods by good id: the name, the name inside a sentence, the subject of "was" in a trading tip, and the short label of a dragged good.
  'good.scrap': 'Scrap metal',
  'good.scrap.lower': 'scrap metal',
  'good.scrap.subject': 'scrap metal was',
  'good.scrap.short': 'Scrap',
  'good.salt': 'Salt',
  'good.salt.lower': 'salt',
  'good.salt.subject': 'salt was',
  'good.salt.short': 'Salt',
  'good.meds': 'Meds',
  'good.meds.lower': 'meds',
  'good.meds.subject': 'meds were',
  'good.meds.short': 'Meds',
  'good.grain': 'Grain',
  'good.grain.lower': 'grain',
  'good.grain.subject': 'grain was',
  'good.grain.short': 'Grain',
  'good.textiles': 'Textiles',
  'good.textiles.lower': 'textiles',
  'good.textiles.subject': 'textiles were',
  'good.textiles.short': 'Texti',
  'good.tools': 'Machine tools',
  'good.tools.lower': 'machine tools',
  'good.tools.subject': 'machine tools were',
  'good.tools.short': 'Machi',
  'good.batteries': 'Batteries',
  'good.batteries.lower': 'batteries',
  'good.batteries.subject': 'batteries were',
  'good.batteries.short': 'Batte',
  'good.electronics': 'Electronics',
  'good.electronics.lower': 'electronics',
  'good.electronics.subject': 'electronics were',
  'good.electronics.short': 'Elect',
  'good.parts': 'Parts',
  'good.parts.lower': 'parts',
  'good.parts.subject': 'parts were',
  'good.parts.short': 'Parts',
  'good.fuelDrums': 'Fuel drums',
  'good.fuelDrums.lower': 'fuel drums',
  'good.fuelDrums.subject': 'fuel drums were',
  'good.fuelDrums.short': 'Fuel ',
  'good.water': 'Water',
  'good.water.lower': 'water',
  'good.water.subject': 'water was',
  'good.water.short': 'Water',
  // Towns and locations by site id.
  'site.bowl': 'Bowl',
  'site.nose': 'Nose',
  'site.orchard': 'Old Orchard',
  'site.dustwell': 'Dustwell',
  'site.granary': 'The Granary',
  'site.burnt-convoy': 'Burnt Convoy',
  'site.podfield': 'Podfield',
  'site.canyon-bridge': 'Canyon Bridge',
  'site.glass-flats': 'Glass Flats',
  'site.green-pit': 'Green Pit',
  'site.south-lock': 'South Lock',
  'site.ridge-wrecks': 'Ridge Wrecks',
  'site.pump-station': 'Pump Station',
  'site.fallen-sun': 'Fallen Sun',
  'site.salvage-yard': 'Salvage Yard',
  'site.broken-wing': 'Broken Wing',
  'site.scrapjaw': 'Scrapjaw Camp',
  'site.kiln': 'Kiln Camp',
  // Ground types by terrain id.
  'terrain.road': 'Road',
  'terrain.hardpan': 'Hardpan',
  'terrain.sand': 'Loose sand',
  'terrain.scrub': 'Scrub',
  'terrain.scree': 'Scree',
  'terrain.mud': 'Mud',
  'terrain.gravel': 'Gravel',
  'terrain.saltCrust': 'Salt crust',
  'terrain.asphalt': 'Cracked asphalt',
  'terrain.ash': 'Ash',
  'terrain.field': 'Dead field',
  'terrain.dirtyWater': 'Dirty water',
  'terrain.toxic': 'Toxic pool',
  'terrain.track': 'Dirt track',
  'terrain.canal': 'Irrigation canal',
  'terrain.concrete': 'Cracked concrete',
  'terrain.glass': 'Fused glass',
  // NPC templates by template id, and the profession texts put before a driver's name.
  'npc.buggy': 'Raider outrider',
  'npc.buggy.profession': 'Raider',
  'npc.gunwagon': 'Gunwagon',
  'npc.gunwagon.profession': 'Raider',
  'npc.trader': 'Trader caravan',
  'npc.trader.profession': 'Trader',
  'npc.scavenger': 'Scavenger',
  'npc.scavenger.profession': 'Scavenger',
  'npc.bowlFarmer': 'Bowl Farmers patrol',
  'npc.bowlFarmer.profession': 'Bowl Farmer',
  'npc.noseArmy': 'Nose Army patrol',
  'npc.noseArmy.profession': 'Nose soldier',
  'npc.courier': 'Courier',
  'npc.courier.profession': 'Courier',
  'npc.roamer': 'Roamer',
  'npc.roamer.profession': 'Roamer',
  'npc.vulture': 'Vulture',
  'npc.vulture.profession': 'Vulture',
  'npc.convoy': 'Supply convoy',
  'npc.convoy.profession': 'Convoy driver',
  'npc.convoyGuard': 'Convoy guard',
  'npc.convoyGuard.profession': 'Convoy guard',
  'npc.merc': 'Merc',
  'npc.merc.profession': 'Merc',
  // Traits and factions by id.
  'trait.trader': 'trader',
  'trait.scavenger': 'scavenger',
  'trait.raider': 'raider',
  'trait.scumbag': 'scumbag',
  'trait.coward': 'coward',
  'trait.lawman': 'lawman',
  'trait.courier': 'courier',
  'trait.roamer': 'roamer',
  'trait.vulture': 'vulture',
  'trait.supplier': 'supplier',
  'trait.guard': 'guard',
  'trait.merc': 'merc',
  'trait.brave': 'brave',
  'faction.player': 'player',
  'faction.raiders': 'raiders',
  'faction.traders': 'traders',
  'faction.scavengers': 'scavengers',
  'faction.bowl': 'bowl',
  'faction.nose': 'nose',
  'faction.couriers': 'couriers',
  'faction.roamers': 'roamers',
  'faction.vultures': 'vultures',
  'faction.convoys': 'convoys',
  'faction.mercs': 'mercs',
  // Skills and perks by id. grows lists what practices a skill.
  'skill.driving': 'Driving',
  'skill.driving.grows': 'rough ground, rams, escapes',
  'skill.perception': 'Perception',
  'skill.perception.grows': 'hits, contacts, discoveries',
  'skill.machining': 'Machining',
  'skill.machining.grows': 'field jobs, patches, searches',
  'skill.toughness': 'Toughness',
  'skill.toughness.grows': 'heat, damage taken, knockouts',
  'skill.social': 'Social',
  'skill.social.grows': 'trade profit, deals, contracts, radio',
  'perk.rammer': 'Rammer',
  'perk.rammer.rule': 'A ram on a hostile truck stalls its engine for one turn.',
  'perk.coldRunning': 'Cold running',
  'perk.coldRunning.rule': 'Below half speed, your engine is heard only inside sight.',
  'perk.steadyAim': 'Steady aim',
  'perk.steadyAim.rule': 'Your own speed adds no scatter to your shots.',
  'perk.dustScreen': 'Dust screen',
  'perk.dustScreen.rule': 'At top speed on dusty ground, your dust blocks sight like a hill.',
  'perk.readDriver': 'Read the driver',
  'perk.readDriver.rule': 'You see the traits of other drivers.',
  'perk.spotter': 'Spotter',
  'perk.spotter.rule': 'Mark a seen truck, and it stays tracked for a day.',
  'perk.cargoEye': 'Cargo eye',
  'perk.cargoEye.rule': 'You see the goods and spare parts in any seen truck.',
  'perk.nightEyes': 'Night eyes',
  'perk.nightEyes.rule': 'Night does not halve your sight.',
  'perk.welder': 'Welder',
  'perk.welder.rule': 'A field job turns 3 scrap metal into a scrap armor sheet.',
  'perk.cannibal': 'Cannibal',
  'perk.cannibal.rule': 'Taking a part from a wreck or a knocked-out truck takes one turn.',
  'perk.rebuild': 'Rebuild',
  'perk.rebuild.rule': 'A town garage can repair a junk part to its last wear step, once per part.',
  'perk.roadMechanic': 'Road mechanic',
  'perk.roadMechanic.rule': 'Drivers pay double for the patches you do.',
  'perk.desertRat': 'Desert rat',
  'perk.desertRat.rule': 'Noon sun heats your engine like morning sun.',
  'perk.stormRider': 'Storm rider',
  'perk.stormRider.rule': 'Dust storms do not cut your sight or aim.',
  'perk.fightThrough': 'Fight through',
  'perk.fightThrough.rule': 'A broken cab, or a hit on a cab below half, does not knock you out while health is above half.',
  'perk.longHaul': 'Long haul',
  'perk.longHaul.rule': 'You heal while driving, not only while parked.',
  'perk.marketEars': 'Market ears',
  'perk.marketEars.rule': 'A trader you call tells you the prices of the last town it left, as they were then.',
  'perk.rumorMill': 'Rumor mill',
  'perk.rumorMill.rule': 'A driver you call marks a wreck or site it passed.',
  'perk.paidTruce': 'Paid truce',
  'perk.paidTruce.rule': 'You can pay a hostile driver to end its feud with you.',
  'perk.bountyTalk': 'Bounty talk',
  'perk.bountyTalk.rule': 'A raider that gives up to you counts for bounty contracts.',
};
