// The screens and panels: menu, saves, HUD, weapons, item cards, inventory, garage and trade.
import { m } from '../msg';

export const SCREENS = {
  // The game menu.
  'menu.save': 'Save',
  'menu.load': 'Load',
  'menu.newGame': 'New game',
  'menu.loadSave': 'Load save',
  'menu.close': 'Close',
  'boot.loading': 'Loading',
  'boot.code': 'Loading the game',
  'boot.map': 'Reading the map',
  'boot.physics': 'Starting physics',
  'boot.models': 'Loading models',
  'boot.sounds': 'Loading sounds',
  'boot.loadSave': 'Loading your save',
  'boot.newGame': 'Starting a new game',
  'boot.ground': 'Painting the ground',
  'boot.scene': 'Building the scene',
  'boot.frame': 'Drawing the first frame',
  'boot.waiting': 'waiting',
  'boot.running': '...',
  'boot.done': 'done',
  'boot.failed': 'failed',
  'boot.counted': m('{label} {done} of {total}', { label: 'text', done: 'int', total: 'int' }),
  'boot.stepFailed': m('{label} failed', { label: 'text' }),
  'boot.failedToLoad': 'The game failed to load. Check your connection and reload the page.',
  // Saves and the boot screens.
  'save.slot.auto': 'Autosave',
  'save.slot.day': 'Day start',
  'save.slot.manual': m('Slot {n}', { n: 'int' }),
  'save.damaged': 'Old or damaged save',
  'save.savedAt': m('{when} ({real})', { when: 'text', real: 'text' }),
  'save.none': 'No saves yet',
  'save.empty': 'Empty',
  'save.confirmLoad': 'Load this save? Progress since your last save is lost.',
  'save.confirmNew': 'Start a new game? The autosaves are deleted. Your save slots stay.',
  'save.needsMigrating': 'Your save needs migrating',
  'save.migrateExplain': 'This update changed the world. Migrate keeps your skills, perks, money, truck, parts and cargo, and moves you to a town. The rest of the world starts fresh.',
  'save.migrate': 'Migrate save',
  'save.unreadable': 'The save is unreadable',
  'save.migrated': 'Save migrated',
  'save.allCarried': 'Everything carried over',
  'save.driveOn': 'Drive on',
  'save.sold': m('{n} {good} sold for {money}', { n: 'int', good: 'text', money: 'text' }),
  'save.toGarage': m('Moved to the garage: {parts}', { parts: 'text' }),
  'save.lost': m('Lost, no longer in the game: {ids}', { ids: 'text' }),
  'save.held': 'Not saved: an error happened since the last good turn.',
  'save.turnFailed': 'The turn failed and did not play. The game was not saved.',
  'save.error.unreadable': 'Game save is unreadable',
  'save.error.otherMap': 'Game save was made on another map',
  'save.error.bakedProps': 'Game save holds baked map props, which come from the map file',
  'save.error.brokenProp': 'Game save holds a broken prop that is no breakable prop of the map',
  'save.error.invalidWorld': 'Invalid saved world',
  'save.error.invalidSave': 'Invalid game save',
  'save.error.incompatible': m('Game save format {major}.{minor} is from an incompatible game version. Start a new game.', { major: 'int', minor: 'int' }),
  'save.error.newer': m('Game save format {major}.{minor} is from a newer game version', { major: 'int', minor: 'int' }),
  'save.error.notMigrated': m('Game save format {major}.{minor} could not be migrated', { major: 'int', minor: 'int' }),
  'save.error.noFormat': 'Game save has no valid format version',
  'save.error.badExplored': 'Invalid saved explored tiles',
  'save.error.badSetup': 'Game save holds invalid world settings',
  'save.failed': 'The game could not save.',
  // The death screen.
  'death.title': 'You died',
  'death.epitaph': 'The life of a great machiner has ended',
  // The character screen.
  'character.close': 'Close [C]',
  'character.title': 'Character',
  'character.health': 'Health',
  'character.knockoutsTitle': 'Knockouts',
  'character.knockouts': m('{n} knockouts', { n: 'count' }),
  'character.xpTitle': 'XP earned by doing things, to spend on skill ranks',
  'character.xp': m('XP to spend: {n}', { n: 'int' }),
  'character.grows': m('Earns XP from {what}', { what: 'text' }),
  'character.rankOf': m('Rank {rank} of {max}', { rank: 'int', max: 'int' }),
  'character.rank': m('Rank {rank}', { rank: 'int' }),
  'character.today': 'Earned today',
  'character.todayXp': m('{n} / {cap} XP', { n: 'int', cap: 'int' }),
  'character.max': 'max',
  'character.spendTitle': m('Spend {cost} XP on {skill} rank {rank}', { cost: 'int', skill: 'text', rank: 'int' }),
  'character.buy': m('Buy rank {rank} — {cost} XP', { rank: 'int', cost: 'int' }),
  'character.locked': m('Rank {rank}: {a} or {b}', { rank: 'int', a: 'text', b: 'text' }),
  'character.pick': m('Rank {rank} perk: pick one', { rank: 'int' }),
  // Sound settings on the radio.
  'sound.music': 'Music',
  'sound.sfx': 'Effects',
  'sound.ambient': 'Wind',
  'sound.ui': 'Interface',
  'sound.next': 'Next track',
  'sound.volume': m('{bus} volume', { bus: 'text' }),
  'sound.percent': m('{n}%', { n: 'int' }),
  'sound.on': 'Sound',
  'sound.mute': 'Mute',
  'sound.unmuteTitle': 'Unmute [M]',
  'sound.muteTitle': 'Mute [M]',
  // The crash screen.
  'crash.title': 'The game crashed',
  'crash.hint': 'Reload the page to start again.',
  // The language control. Each language is named in its own words, so these stay the same in every language.
  'language.label': 'Language',
  'language.en': 'English',
  'language.ru': 'Русский',
  // The instruments panel and the HUD.
  'hud.stopToUse': 'Stop to use',
  'hud.combatBlocked': m('Can\'t do this while in combat, {n, plural, one {# turn left} other {# turns left}}', { n: 'count' }),
  'hud.maxSpeed': m('max {n}', { n: 'int' }),
  'hud.clockTitle': 'Day and time',
  'hud.clockLabel': m('Time: {when}', { when: 'text' }),
  'hud.recenter': 'Center on truck (F)',
  'hud.guideTitle': 'Driving and combat controls',
  'hud.guideMark': '?',
  'hud.guide.drive': 'Click the ground: drive there by road. Shift-click: stop there.',
  'hud.guide.space': 'Space: drive on or pause. Hold Space: fast-forward. Click your truck: brake.',
  'hud.guide.manual': 'R: manual driving, straight at the point.',
  'hud.guide.pads': 'Click a town or site: stop at its pad. E on a pad: trade, repair or loot.',
  'hud.guide.radio': 'T: radio the inspected truck. 1-9: reply. H: honk.',
  'hud.guide.combat': 'Click a truck: inspect it, or aim a picked weapon at its body. 1-4: pick a weapon. 0: all. Q: auto fire. X: show weapons.',
  'hud.guide.keys': 'P: auto patch. C: character. I: inventory. Esc: close.',
  'hud.guide.camera': 'WASD or right-drag: pan. Wheel: zoom. F: center. V: camera. M: mute.',
  'hud.feedbackTitle': 'Report a bug or request a feature',
  'hud.feedbackMark': '!',
  'hud.reportBug': 'Report a bug',
  'hud.requestFeature': 'Request a feature',
  'hud.camAuto': 'Cam auto',
  'hud.camCentered': 'Centered',
  'hud.camTitle': 'Camera mode: lead toward the order point, or stay centered on the truck [V]',
  'hud.workLeft': m('{label}, {n, plural, one {# turn left} other {# turns left}}', { label: 'text', n: 'count' }),
  'hud.workProgress': m('{label} progress', { label: 'text' }),
  'hud.actionKey': m('[E] {label}', { label: 'text' }),
  'hud.count': m('{n}/{of}', { n: 'int', of: 'int' }),
  'hud.knockedOut': 'Knocked out',
  'hud.underTow': 'Under tow',
  'hud.towsYou': m('{who} tows you to {town}.', { who: 'text', town: 'text' }),
  'hud.towFee': m('Fee {fee} on arrival.', { fee: 'text' }),
  'hud.unhitch': 'Unhitch',
  'hud.stranded': 'Stranded',
  'hud.callingTow': 'Calling for a tow.',
  'hud.beaconOn': 'Beacon on',
  'hud.beaconOff': 'Beacon off',
  'hud.beaconTitle': 'Call for a tow by radio.',
  'hud.contracts': 'Contracts',
  'hud.contractLine': m('{what} — {due}', { what: 'text', due: 'text' }),
  'hud.lightsOn': 'Lights on',
  'hud.lightsOff': 'Lights off',
  'hud.lightsTitle': 'Headlights [L]',
  'hud.overdrive': 'Overdrive',
  'hud.normal': 'Normal',
  'hud.overdriveTitle': 'Engine overdrive: faster, but the engine heats fast [O]',
  'hud.douseTitle': m('Pour {n, plural, one {# supply} other {# supplies}} of water over the engine to cool it [G]', { n: 'count' }),
  'hud.douse': 'Cool engine [G]',
  'hud.characterMarked': 'Driver and skills: XP to spend or a perk to pick [C]',
  'hud.character': 'Driver and skills [C]',
  'hud.characterKeyMarked': '! [C]',
  'hud.characterKey': '[C]',
  'hud.inventoryTitle': 'Truck inventory [I]',
  'hud.inventoryLabel': 'Open truck inventory',
  'hud.readout': m('{label}: {value}', { label: 'text', value: 'text' }),
  'hud.readoutWarning': m('{label}: {value}, warning', { label: 'text', value: 'text' }),
  'hud.warned': m('! {value}', { value: 'text' }),
  'hud.manual': 'Manual',
  'hud.route': 'Route',
  'hud.manualTitle': 'Manual driving: straight at the point, or follow the roads [R]',
  'hud.autoPatch': 'Auto patch',
  'hud.noPatch': 'No patch',
  'hud.autoPatchTitle': 'Patch damaged parts while parked [P]',
  'hud.hostile': m('{faction} hostile', { faction: 'text' }),
  'hud.neutral': m('{faction} neutral', { faction: 'text' }),
  'hud.speed': m('Speed {n} km/h', { n: 'int' }),
  'hud.aimHint': 'Click a part to aim the selected gun at it',
  // The E key actions.
  'action.giveAid': m('Give {goods} to {truck}', { goods: 'text', truck: 'text' }),
  'action.takeAid': m('Take {goods} from {truck}', { goods: 'text', truck: 'text' }),
  'action.trade': m('Trade with {truck}', { truck: 'text' }),
  'action.enter': m('Enter {site}', { site: 'text' }),
  'action.lootTruck': m('Loot {truck}', { truck: 'text' }),
  'action.refill': m('Refill supplies at {site}', { site: 'text' }),
  'action.noLoot': 'No loot left',
  'action.lootingIt': m('{truck} is looting it', { truck: 'text' }),
  'stock.search.pile': 'Search the pile',
  'stock.search.wreck': 'Search the wreck',
  'stock.search.spot': 'Search',
  'stock.search.site': m('Search {site}', { site: 'text' }),
  'stock.loot.pile': 'Loot the pile',
  'stock.loot.wreck': 'Loot the wreck',
  'stock.loot.spot': 'Loot',
  'stock.loot.site': m('Loot {site}', { site: 'text' }),
  'stock.empty.pile': 'The pile is picked clean',
  'stock.empty.wreck': 'The wreck is picked clean',
  'stock.empty.spot': 'Picked clean',
  'stock.empty.site': m('{site} is picked clean', { site: 'text' }),
  // Part condition tiles.
  'condition.broken': m('{part}: broken', { part: 'text' }),
  'condition.percent': m('{part}: {pct}%', { part: 'text', pct: 'int' }),
  // Weather.
  'weather.heatwave': 'Heat wave',
  'weather.overcast': 'Overcast',
  'weather.storm': 'Dust storm',
  'weather.stormNear': 'Storm near',
  'weather.clear': 'Clear',
  'money.debt': m('Debt {n}', { n: 'int' }),
  'money.amount': m('{n}', { n: 'int' }),
  // Why the truck is stranded.
  'stranded.spareEngine': 'No working engine. Install the spare [I].',
  'stranded.noEngine': 'No working engine.',
  'stranded.transmission': 'The transmission is broken.',
  'stranded.noFuel': 'Out of fuel.',
  // The max speed breakdown and the power chip.
  'speed.pctZero': '0%',
  'speed.pctUp': m('+{n}%', { n: 'int' }),
  'speed.pctDown': m('−{n}%', { n: 'int' }),
  'speed.kphUp': m('+{n} km/h', { n: 'int' }),
  'speed.kphDown': m('−{n} km/h', { n: 'int' }),
  'speed.chassis': 'Chassis',
  'speed.engineWorn': 'Engine worn',
  'speed.engine': 'Engine',
  'speed.load': 'Load',
  'speed.wheels': m('{n, plural, one {# broken wheel} other {# broken wheels}}', { n: 'count' }),
  'speed.guns': 'Guns power',
  'speed.floor': 'Minimum speed',
  'speed.overdrive': 'Overdrive',
  'speed.transmission': 'Broken transmission',
  'speed.limp.noEngine': 'No engine',
  'speed.limp.brokenEngine': 'Engine broken',
  'speed.limp.stalled': 'Engine stalled',
  'speed.towing': 'Towing',
  'speed.line': m('{label}: {effect}', { label: 'text', effect: 'text' }),
  'speed.crawlLine': m('{label}: crawl {n} km/h', { label: 'text', n: 'int' }),
  'speed.lowFuel': m('Low fuel: max {n} km/h', { n: 'int' }),
  'speed.emptyTank': 'Empty tank: crawl',
  'speed.noPenalties': 'No speed penalties',
  'power.noCostStalled': 'no speed cost while stalled',
  'power.noneStalled': 'none while stalled',
  'power.noCost': 'no speed cost',
  'power.none': 'none',
  'power.cost': m('{pct} speed', { pct: 'text' }),
  'power.costLong': m('{pct} speed, −{n} km/h', { pct: 'text', n: 'int' }),
  'power.noEngine': 'No working engine',
  'power.noEngineDetail': 'No working engine: guns cost no speed.',
  'power.over': m('over by {n}', { n: 'dec' }),
  'power.spare': m('{n} spare', { n: 'dec' }),
  'power.detail': m('Guns draw {draw} of {capacity} power, {balance}. Cost: {cost}.', { draw: 'dec', capacity: 'dec', balance: 'text', cost: 'text' }),
  'power.chip': m('{draw} / {capacity} power, {cost}', { draw: 'dec', capacity: 'dec', cost: 'text' }),
  'power.chipOver': m('{draw} / {capacity} power, {balance}, {cost}', { draw: 'dec', capacity: 'dec', balance: 'text', cost: 'text' }),
  // Resource readouts.
  'readout.money': 'Money',
  'readout.fuel': 'Fuel',
  'readout.supplies': 'Supplies',
  'readout.driver': 'Driver',
  'readout.heat': 'Heat',
  'readout.engine': 'Engine',
  'readout.weather': 'Weather',
  'readout.liters': m('{n} / {max} L', { n: 'int', max: 'int' }),
  'readout.ofMax': m('{n} / {max}', { n: 'int', max: 'int' }),
  'readout.celsius': m('{n} °C', { n: 'int' }),
  'units.kg': m('{n} kg', { n: 'int' }),
  'ui.key': m('[{key}]', { key: 'name' }),
  // Map labels.
  'map.unknownSite': '???',
  'map.rumor': 'Wreck (rumor)',
  'map.radio': '[T] Radio',
  // First-time tips, by tip id.
  'hint.waypoint': 'Click the ground to set a waypoint.',
  'hint.drive': '[Space] to drive to the waypoint.',
  'hint.autoStop': '[Space] to stop automatic travel.',
  'hint.stop': 'Click your truck to stop.',
  'hint.stopAt': '[Shift]-click to set a waypoint your truck stops at. Click a waypoint to switch it.',
  'hint.manual': '[R] to drive in manual mode.',
  'hint.zones': 'Manual mode: click a zone to drive. Green speeds up. Yellow holds speed. Red slows down.',
  'hint.aim': 'Click a truck to inspect it. Pick a weapon first to aim it at the body, or click a part in the card.',
  'hint.honk': '[H] to honk.',
  'hint.farewell': 'That\'s it, good luck.',
  'hint.closeMark': '×',
  'hud.cycleKey': m('[{key}]', { key: 'name' }),
  'log.expandMark': '⤢',
  'radio.ghost': m('{blocks}', { blocks: 'name' }),
  'hud.prevMark': '‹',
  'hud.nextMark': '›',
  // Why a gun cannot fire.
  'block.disabled': 'disabled',
  'block.cooldown': 'cooling down',
  'block.empty': 'reloading',
  'block.range': 'out of range',
  'block.arc': 'out of arc',
  'block.blocked': 'view blocked on truck',
  'block.noTarget': 'hold fire',
  'block.unseen': 'not in sight',
  'block.covered': 'behind cover',
  'block.talking': 'on the radio',
  'block.out': 'driver knocked out',
  // The same reasons in one short word.
  'blockShort.disabled': 'broken',
  'blockShort.cooldown': 'wait',
  'blockShort.cooldownIn': m('wait {n}', { n: 'int' }),
  'blockShort.empty': 'load',
  'blockShort.emptyIn': m('load {n}', { n: 'int' }),
  'blockShort.range': 'range',
  'blockShort.arc': 'arc',
  'blockShort.blocked': 'blocked',
  'blockShort.unseen': 'unseen',
  'blockShort.covered': 'cover',
  'blockShort.talking': 'radio',
  'blockShort.out': 'out',
  // The weapons panel.
  'weapon.bodyShot': 'body shot',
  'weapon.readyIn': m('ready in {n, plural, one {# turn} other {# turns}}', { n: 'count' }),
  'weapon.reloadingFor': m('reloading {n, plural, one {# turn} other {# turns}}', { n: 'count' }),
  'weapon.ammo': m('{n}/{of}', { n: 'int', of: 'int' }),
  'weapon.reloadingLeft': m('reloading, {n, plural, one {# turn} other {# turns}} left', { n: 'count' }),
  'weapon.rounds': m('{n}/{of} rounds', { n: 'int', of: 'int' }),
  'weapon.ready': 'ready',
  'weapon.title': 'Weapons',
  'weapon.toggleTitle': 'Show or hide weapons [X]',
  'weapon.hide': 'Hide [X]',
  'weapon.show': 'Show [X]',
  'weapon.autoTitle': 'Auto fire: guns shoot at hostiles on their own [Q]',
  'weapon.auto': 'Auto fire [Q]',
  'weapon.allTitle': 'Aim all weapons with the next click [0]',
  'weapon.all': 'All [0]',
  'weapon.none': 'No weapons installed',
  'weapon.targetGone': 'target unavailable',
  'weapon.noTarget': 'no target',
  'weapon.slotLabel': m('{name}: {status}, {target}', { name: 'text', status: 'text', target: 'text' }),
  'weapon.slotTitle': m('{name}: {rounds} × {damage} damage, pen {pen}, range {range} m, arc {arc}°, fires every {cooldown, plural, one {# turn} other {# turns}}, {magazine} shots, reloads in {reload, plural, one {# turn} other {# turns}}. {status}, {target}', { name: 'text', rounds: 'int', damage: 'dec', pen: 'dec', range: 'int', arc: 'int', cooldown: 'count', magazine: 'int', reload: 'count', status: 'text', target: 'text' }),
  'weapon.holdTitle': 'Hold fire: stop auto fire and clear this gun\'s target',
  'weapon.hold': 'Hold',
  'weapon.reloadTitle': m('Reload: drop the magazine and refill it in {n, plural, one {# turn} other {# turns}}', { n: 'count' }),
  'weapon.reloadLabel': m('Reload {name}', { name: 'text' }),
  // The turn button.
  'turn.autoTitle': 'Automatic travel. Space or click to stop.',
  'turn.stopAuto': 'Stop automatic travel',
  'turn.auto': 'Auto',
  'turn.endTitle': 'End turn [Space]. Hold to fast-forward.',
  'turn.inProgress': m('{phase} in progress', { phase: 'text' }),
  'turn.end': 'End turn',
  'turn.running': m('{phase}…', { phase: 'text' }),
  'turn.space': 'Space',
  'phase.moving': 'Moving',
  'phase.firing': 'Firing',
  'phase.results': 'Results',
  // The hit card over a hovered truck.
  'hit.detail': m('{pct}% land on aim, {m} m, shows {wide} m wide, scatter {deg}° weapon', { pct: 'int', m: 'int', wide: 'dec1', deg: 'dec1' }),
  'hit.causeMore': m(' +{deg}° {cause}', { deg: 'dec1', cause: 'text' }),
  'hit.causeLess': m(' −{deg}° {cause}', { deg: 'dec1', cause: 'text' }),
  'hit.cause.range': 'range',
  'hit.cause.crossing': 'crossing',
  'hit.cause.own': 'own speed',
  'hit.cause.recoil': 'recoil',
  'hit.cause.skill': 'perception',
  'hit.cause.weather': 'weather',
  'hit.cause.still': 'still target',
  'hit.reason.far': 'far',
  'hit.reason.crossing': 'target crossing fast',
  'hit.reason.moving': 'you are moving',
  'hit.reason.kick': 'gun kick',
  'hit.reason.weather': 'bad weather',
  'hit.reason.loose': 'loose gun',
  'hit.reason.covered': 'parts in the way',
  'hit.reason.parked': 'target is parked: easy',
  'hit.reason.clear': 'clear shot',
  'hit.label': m('{name} {ammo}', { name: 'text', ammo: 'text' }),
  'hit.chance': m('{pct}%', { pct: 'int' }),
  'hit.slot': m('[{n}] {gun}', { n: 'int', gun: 'text' }),
  'hit.noWeapons': 'No weapons',
  'hit.mine': 'You → it',
  'hit.theirs': 'It → you',
  // The part condition panel.
  'condition.panel': 'Truck part condition, nose up',
  'condition.aimedBy': m('Aimed by gun {guns}', { guns: 'text' }),
  // Icon names.
  'icon.star': 'Pristine',
  'icon.money': 'Money',
  'icon.fuel': 'Fuel',
  'icon.supplies': 'Supplies',
  'icon.driver': 'Driver',
  'icon.truck': 'Truck inventory',
  'icon.cannon': 'Forward cannon',
  'icon.mg': 'MG turret',
  'icon.engine': 'Engine',
  'icon.armor': 'Armor',
  'icon.cargo': 'Cargo',
  'icon.wheel': 'Wheel',
  'icon.transmission': 'Transmission',
  'icon.cab': 'Cab',
  'icon.salt': 'Salt',
  'icon.turn': 'End turn',
  'icon.tools': 'Machine tools',
  'icon.parts': 'Parts',
  'icon.scanner': 'Radio scanner',
  'icon.damage': 'Damage',
  'icon.pen': 'Penetration',
  'icon.range': 'Range',
  'icon.reload': 'Reload',
  'icon.cooldown': 'Cooldown',
  'icon.magazine': 'Magazine',
  'icon.spread': 'Spread',
  'icon.arc': 'Firing arc',
  'icon.speed': 'Speed',
  'icon.accel': 'Acceleration',
  'icon.noise': 'Noise',
  'icon.ram': 'Ram',
  'icon.rows': 'Cargo rows',
  'icon.hp': 'HP',
  'icon.mass': 'Mass',
  'icon.turning': 'Turning',
  'icon.cells': 'Cargo cells',
  'icon.load': 'Rated load',
  'icon.recoil': 'Recoil',
  'icon.power': 'Power',
  'icon.blast': 'Blast armor',
  'icon.heat': 'Heat',
  'icon.patch': 'Field repair',
  'icon.tall': 'Tall',
  'icon.clock': 'Time left',
  // Item cards and their stats.
  'stat.same': '=',
  'stat.footprint': m('{w}×{h} cells', { w: 'int', h: 'int' }),
  'stat.condition': m('Condition: {hp} of {max} HP', { hp: 'int', max: 'int' }),
  'stat.compared': m('Compared with {part} ', { part: 'text' }),
  'stat.layout': m('{chassis} layout', { chassis: 'text' }),
  'stat.plus0': m('+{n}', { n: 'int' }),
  'stat.minus0': m('−{n}', { n: 'int' }),
  'stat.plus1': m('+{n}', { n: 'dec1' }),
  'stat.minus1': m('−{n}', { n: 'dec1' }),
  'stat.roundsTimes': m('{n}×{damage}', { n: 'int', damage: 'dec1' }),
  'stat.span': m('{a}–{b}', { a: 'int', b: 'int' }),
  'stat.rowsUnit': m('{n, plural, one {row} other {rows}}', { n: 'count' }),
  'stat.mass': 'Mass',
  'stat.detection': 'Detection range',
  'stat.extraFuel': 'Extra fuel',
  'stat.extraSupplies': 'Extra supplies',
  'stat.extraRows': 'Extra cargo rows',
  'stat.pen': 'Penetration',
  'stat.height': 'Height',
  'stat.tall': 'tall',
  'stat.low': 'low',
  'stat.damage': 'Damage per shot',
  'stat.range': 'Range',
  'stat.cooldown': 'Turns between shots',
  'stat.magazine': 'Shots per magazine',
  'stat.reload': 'Turns to reload',
  'stat.arc': 'Firing arc',
  'stat.recoil': 'Recoil',
  'stat.draw': 'Power draw',
  'stat.topSpeed': 'Top speed',
  'stat.accel': 'Acceleration',
  'stat.gunPower': 'Gun power',
  'stat.fuelUse': 'Fuel use',
  'stat.heat': 'Heat',
  'stat.armor': 'Armor',
  'stat.blastArmor': 'Blast armor',
  'stat.ram': 'Ram damage',
  'stat.repair.none': 'Repair: shop only',
  'stat.repair.capped': 'Field repair: partial',
  'stat.repair.full': 'Field repair: full',
  'stat.repairShort.none': 'shop',
  'stat.repairShort.capped': 'cap',
  'stat.repairShort.full': 'full',
  'stat.turning': 'Turning',
  'stat.baseSpeed': 'Base top speed',
  'stat.cells': 'Cargo cells',
  'stat.ratedLoad': 'Rated load',
  'stat.emptyMass': 'Empty mass',
  'stat.fuelTank': 'Fuel tank',
  // Stat units.
  'unit.kg': 'kg',
  'unit.m': 'm',
  'unit.t': 't',
  'unit.deg': '°',
  'unit.kph': 'km/h',
  'unit.mps2': 'm/s²',
  'unit.times': '×',
  'unit.liters': 'L',
  'unit.blast': 'blast',
  // The inventory grid and garage.
  'inv.parkForStorage': 'Park at a shop to use garage storage. Drag onto a mount to start a refit.',
  'inv.dump': 'Drop here to dump',
  'inv.legend': 'Mounts & controls',
  'inv.legendMounts': 'Top view, nose up. Brown cells are deck mounts for weapons, scanners and cargo frames. Blue-grey cells are the engine mount. The cells around the truck are armor mounts. Hover a cell to see what it mounts.',
  'inv.legendWorks': 'A part works only when it lies fully on one kind of mount. The marks on a gun show its blocked sides.',
  'inv.legendDrag': 'Drag to move or swap. R or right click turns an item.',
  'inv.refitLeft': m('Refit: {n, plural, one {# turn} other {# turns}} left', { n: 'count' }),
  'inv.equipment': 'Equipment',
  'inv.selectHint': 'Select a part or cargo to inspect it.',
  'inv.cancelRefitTitle': 'Stop the refit and leave every part where it was',
  'inv.cancelRefit': 'Cancel refit',
  'inv.refitHint': 'Drag onto a mount or off it to start a refit.',
  'inv.patchTitle': m('Patch: {turns, plural, one {# turn} other {# turns}}, {parts} of {needed} parts, +{hp} HP', { turns: 'count', parts: 'int', needed: 'int', hp: 'int' }),
  'inv.patchBlocked': m('Patch ({reason})', { reason: 'text' }),
  'inv.patch': m('Patch {turns}t/{parts}p', { turns: 'int', parts: 'int' }),
  'inv.repairTitle': m('Restore to {hp} HP', { hp: 'int' }),
  'inv.rebuildTitle': 'Rebuild to the last wear step, once per part',
  'inv.repair': m('Repair {cost}', { cost: 'text' }),
  'inv.rebuild': m('Rebuild {cost}', { cost: 'text' }),
  'inv.stripTitle': m('Strip: {turns, plural, one {# turn} other {# turns}} for {parts} parts', { turns: 'count', parts: 'int' }),
  'inv.stripBlocked': 'Strip',
  'inv.strip': m('Strip {turns}t/{parts}p', { turns: 'int', parts: 'int' }),
  'inv.weldTitle': m('Weld: {turns, plural, one {# turn} other {# turns}} for a {part}, spends {scrap} scrap metal', { turns: 'count', part: 'text', scrap: 'int' }),
  'inv.weldBlocked': m('Weld ({reason})', { reason: 'text' }),
  'inv.weld': m('Weld {turns}t', { turns: 'int' }),
  'inv.storage': 'Garage storage',
  'inv.storageEmpty': 'Drop parts here to store them.',
  'inv.goodCount': m('{good} x{n}', { good: 'text', n: 'int' }),
  'inv.takeStores': m('Take fuel {fuel} L, supplies {supplies}', { fuel: 'int', supplies: 'dec1' }),
  'inv.salvage': 'Salvage',
  'inv.salvageAt': m('Salvage: {site}', { site: 'text' }),
  'inv.nothingLeft': 'Nothing left here.',
  'inv.takeAll': 'Take all that fits',
  'inv.dragToGrid': 'Drag items onto the grid.',
  'inv.truckGone': 'The truck got away',
  'inv.truckGaveUp': m('{truck}, gave up', { truck: 'text' }),
  'inv.truckOut': m('{truck}, knocked out', { truck: 'text' }),
  'inv.dragToYours': 'Drag items onto your grid.',
  'inv.close': 'Close [I]',
  'inv.title': 'Inventory',
  'inv.freeCellsTitle': 'Free cargo cells',
  'inv.freeCells': m('{n} free', { n: 'int' }),
  'inv.loadTitle': 'Mass against rated load',
  'speed.loadChip': m('{mass} / {rated}', { mass: 'text', rated: 'text' }),
  'inv.stopToPatch': 'Stop to patch',
  'inv.noParts': 'No parts',
  'inv.stopToStrip': 'Stop to strip',
  'inv.busy': 'Busy',
  'inv.stopToWeld': 'Stop to weld',
  'inv.needsScrap': m('Needs {n} scrap', { n: 'int' }),
  'inv.patchShopOnly': 'Patch (shop only)',
  'inv.against': m('Against {part} ', { part: 'text' }),
  // Grid cells and items.
  'cell.deck': 'deck mount for a weapon, scanner, cargo frame or store',
  'cell.engine': 'engine mount',
  'cell.front': 'front armor mount',
  'cell.back': 'back armor mount',
  'cell.left': 'left armor mount',
  'cell.right': 'right armor mount',
  'cell.builtIn': 'built-in part',
  'item.title': m('{part}\n{state}', { part: 'text', state: 'text' }),
  'item.partTitle': m('{name} ({kind}) {wear}, {hp}/{max} HP, {w}x{h}', { name: 'text', kind: 'text', wear: 'text', hp: 'int', max: 'int', w: 'int', h: 'int' }),
  'item.cargo': m('Cargo, {mass}', { mass: 'text' }),
  'item.builtIn': 'Built in',
  'item.mounted': 'Mounted',
  'item.spare': 'Spare',
  'kind.weapon': 'weapon',
  'kind.engine': 'engine',
  'kind.armor': 'armor',
  'kind.cargo': 'cargo',
  'kind.scanner': 'scanner',
  'kind.store': 'store',
  'kind.core': 'core',
  // Shop and truck trade screens.
  'trade.leave': 'Leave [Esc]',
  'trade.tab.market': 'Market',
  'trade.tab.buyParts': 'Buy Parts',
  'trade.tab.sellParts': 'Sell Parts',
  'trade.tab.trucks': 'Trucks',
  'trade.tab.contracts': 'Contracts',
  'trade.tradeTab.goods': 'Goods',
  'trade.tradeTab.parts': 'Parts',
  'trade.tradeTab.supplies': 'Fuel & supplies',
  'trade.plus': m('+{n}', { n: 'int' }),
  'trade.minus': m('−{n}', { n: 'int' }),
  'trade.all': 'All',
  'trade.buyFor': m('Buy {price}', { price: 'text' }),
  'trade.sellFor': m('Sell {price}', { price: 'text' }),
  'trade.toStorage': 'No room: goes to storage',
  'trade.noneOfKind': 'No parts of this kind in stock.',
  'trade.noStock': 'No parts in stock.',
  'trade.filter.all': 'All',
  'trade.filter.weapon': 'Weapons',
  'trade.filter.engine': 'Engines',
  'trade.filter.armor': 'Armor',
  'trade.filter.cargo': 'Cargo',
  'trade.filter.scanner': 'Scanners',
  'trade.filter.store': 'Stores',
  'trade.sellTitle': 'Sell spare and stored parts',
  'trade.noSpares': 'No spare or stored parts.',
  'trade.liters': m('{n} L', { n: 'int' }),
  'trade.ofCap': m('{have} / {cap}', { have: 'text', cap: 'text' }),
  'trade.per': m('{price} per {unit}', { price: 'int', unit: 'text' }),
  'trade.each': m('{price} each', { price: 'int' }),
  'trade.plusAmount': m('+{amount}', { amount: 'text' }),
  'trade.fill': m('Fill {amount}', { amount: 'text' }),
  'trade.onOffer': m('{pricing}, {amount} on offer', { pricing: 'text', amount: 'text' }),
  'trade.broken': m('{n} broken', { n: 'int' }),
  'trade.basicsFine': 'Basics fine',
  'trade.repairBasics': m('Repair basics {cost}', { cost: 'text' }),
  'trade.noRepairs': 'No repairs',
  'trade.repairAll': m('Repair all {cost}', { cost: 'text' }),
  'trade.versus': m('vs {chassis}', { chassis: 'text' }),
  'trade.swap': m('Swap {cost}', { cost: 'text' }),
  'trade.swapBack': m('Swap, get {back} back', { back: 'text' }),
  'trade.tradeIn': m('Your truck trades in for {price}.', { price: 'text' }),
  'trade.hint.short': 'short',
  'trade.hint.flooded': 'flooded',
  'trade.hint.cheap': 'cheap here',
  'trade.hint.dear': 'dear here',
  'trade.noGoods': 'Neither truck carries goods to trade.',
  'trade.theirSpares': 'Their spare parts',
  'trade.yourSpares': 'Your spare parts',
  'trade.nothingSpare': 'Nothing spare.',
  'trade.them': 'Them',
  'trade.theirMoney': 'Their money',
  'trade.theirCells': 'Their free cargo cells',
  // The contract board.
  'contract.accept': 'Accept',
  'contract.full': m('You already hold {n} contracts', { n: 'count' }),
  'contract.board': 'Contract board',
  'contract.noOffers': 'No offers.',
  'contract.yours': m('Your contracts {n} / {max}', { n: 'int', max: 'int' }),
  'contract.none': 'You hold no contracts.',
  'contract.deliverAt': m('Deliver at {site}', { site: 'text' }),
  'contract.notEnoughCargo': 'Not enough cargo yet',
  'contract.needsPart': 'Needs the part',
  'contract.deliver': 'Deliver',
  'contract.paysGiveUp': 'Pays on knockout, wreck or give-up',
  'contract.pays': 'Pays on knockout or wreck',
  'contract.windowTitle': m('{n, plural, one {# turn} other {# turns}} from acceptance', { n: 'count' }),
  'contract.dueTitle': m('{n, plural, one {# turn} other {# turns}} left', { n: 'count' }),
};
