// Radio talk and broadcasts: every line a driver or the player says, the call values filled into them, and J.J.'s
// lines on Waste Of Time Radio. Drivers and J.J. talk about roads, cargo, money and wrecks, never about the game.
import { m } from '../msg';

export const TALK = {
  'line.warnTerms': m('{warnLine}', { warnLine: 'text' }),
  'line.thisOneIsSpokenFor': 'This one\'s spoken for, friend. Move along.',
  'line.thatsMyPick': 'That\'s my pick. Roll on.',
  'line.offMyLootNow': 'Off my loot. Now.',
  'line.leaveThatSalvageBe': 'Leave that salvage be and move on.',
  'line.imTakingThatOne': 'I\'m taking that one. Clear off.',
  'line.sawThisOneFirst': 'Saw this one first. Find another.',
  'line.mineGoPickAnother': 'Mine. Go pick another carcass.',
  'line.weAreTakingThisOne': 'We\'re taking this one. Keep moving.',
  'line.backAwayFromThat': 'Back away from that salvage.',
  'line.thatsMineWalkAway': 'That\'s mine. Walk away.',
  'line.findYourOwn': 'Find your own.',
  'line.makeMe': 'Make me.',
  'line.keepYourScrapsThen': 'Keep your scraps, then.',
  'line.thoughtSo': 'Thought so.',
  'line.thenWeSettleIt': 'Then we settle it the hard way.',
  'line.bringIt': 'Bring it.',
  'line.seenADeadArmy': 'Seen a dead Army wagon out here?',
  'line.armyWagonTold': 'Army wagon? Yeah, I passed one. It lies in a hollow, closer to the Bowl north road than to the Pump Station track, south of an old farm with a water tower. Nobody was at it that I saw.',
  'line.whatElseDidYouSee': 'What else did you see out there?',
  'line.aWreckNobodyPicked': m('A wreck nobody picked clean, {bearing} of you, about {distance} out.', { bearing: 'text', distance: 'text' }),
  'line.agreedGunsDown': 'Agreed. Guns down.',
  'line.allRightIAm': 'All right. I am done. Take what you want.',
  'line.allRightItIs': 'All right! It is on the ground. Now leave us alone.',
  'line.alreadySaid': 'Already said.',
  'line.anythingInteresting': 'Anything interesting?',
  'line.busy': 'Busy here! Off the channel.',
  'line.canYouDoAnything': 'Engine, gearbox or tank. Can you do anything?',
  'line.clearTheChannel': 'Clear the channel.',
  'line.comeAndGetIt': 'Come and get it.',
  'line.comeAndTakeIt': 'Come and take it.',
  'line.dealHitchMeUp': 'Deal. Hitch me up.',
  'line.dealHitchUp': 'Deal. Hitch up.',
  'line.dealIWillStay': 'Deal. I will stay put.',
  'line.dealPlain': 'Deal.',
  'line.dealPullOverAnd': 'Deal. Pull over and wait.',
  'line.dealSendingIt': 'Deal. Sending it.',
  'line.dealStayWhereYou': 'Deal. Stay where you are.',
  'line.dealTerms': m('{deal}', { deal: 'text' }),
  'line.demandCargo': 'Dump your cargo and roll on. Or we take it off your wreck.',
  'line.dropYourCargoOr': 'Drop your cargo, or we open fire.',
  'line.dumpAndDrive': 'Dump your cargo and drive off.',
  'line.enoughOfThisWe': 'Enough of this. We both drive away.',
  'line.enoughShootingCanWe': 'Enough shooting. Can we call a truce?',
  'line.findYourOwnWreck': 'Find your own wreck.',
  'line.findersKeepers': 'Finders keepers.',
  'line.fineItsYours': 'Fine. It\'s yours.',
  'line.fineKeepYourGuns': 'Fine. Keep your guns down.',
  'line.fineTakeIt': 'Fine. Take it.',
  'line.fineThanksForThe': 'Fine. Thanks for the pull.',
  'line.getLost': 'Get lost.',
  'line.getOffMyChannel': 'Get off my channel.',
  'line.giveUpOffer': 'Your truck is dead in the road. Stand down and we both drive on.',
  'line.goAhead': 'Go ahead.',
  'line.going': 'Going.',
  'line.good': 'Good.',
  'line.hangUp': 'Hang up.',
  'line.haveItYourWay': 'Have it your way.',
  'line.heardYou': 'Heard you.',
  'line.heardYouTheFirst': 'Heard you the first time.',
  'line.hehNo': 'Heh. No.',
  'line.holdOnIAm': 'Hold on. I am coming over.',
  'line.howArePricesIn': 'How are prices in town?',
  'line.iAmLettingYou': 'I am letting you off the rope here.',
  'line.iAmListening': 'I am listening.',
  'line.iAmRunningDry': 'I am running dry. Can you spare some?',
  'line.iAmStrandedCan': 'I am stranded. Can you tow me?',
  'line.iCanSpareAid': m('I can spare {aid}. Stay put, I am coming.', { aid: 'text' }),
  'line.iCannotHelpSorry': 'I cannot help, sorry.',
  'line.iCouldUseAid': m('I could use {aid}. I can pay {price}.', { aid: 'text', price: 'text' }),
  'line.iGiveUpLet': 'I give up. Let me go.',
  'line.itIsYours': 'It is yours.',
  'line.iToldYouAlready': 'I told you already.',
  'line.keepItShort': 'Keep it short.',
  'line.keepOffThisChannel': 'Keep off this channel.',
  'line.lastIWasIn': m('Last I was in {town}: {prices}.', { town: 'text', prices: 'text' }),
  'line.leaveItOnThe': 'Leave it on the ground and go.',
  'line.letMeCheckMy': 'Let me check my tanks.',
  'line.letMeHearWhat': 'Let me hear what broke.',
  'line.listening': 'Listening.',
  'line.makeItShort': 'Make it short.',
  'line.maybeIPassedSomething': 'Maybe. I passed something on my way.',
  'line.moneyIsInGuns': "The M's are in. Guns down.",
  'line.moveAlong': 'Move along.',
  'line.myTruckIsBroken': 'My truck is broken down. Can you patch it?',
  'line.myTruckIsDead': 'My truck is dead out here. Can you patch me up?',
  'line.needATowTo': 'Need a tow to town?',
  'line.neverMind': 'Never mind.',
  'line.noCharge': 'No charge.',
  'line.noChargeHitchUp': 'No charge. Hitch up.',
  'line.noDeals': 'No deals.',
  'line.noFreeRideDump': 'No free ride. Dump your cargo and roll on, and we call it square.',
  'line.noMercy': 'No mercy.',
  'line.noThanks': 'No thanks.',
  'line.noTimeOut': 'No time. Out.',
  'line.noWeFinishThis': 'No. We finish this.',
  'line.notInterested': 'Not interested.',
  'line.notNowSomethingElse': 'Not now. Something else.',
  'line.notTalking': 'Not talking.',
  'line.notToday': 'Not today.',
  'line.notTodayRun': 'Not today!',
  'line.notWhileICan': 'Not while I can still pull a trigger.',
  'line.notWithWhatI': 'Not with what I have. Sorry.',
  'line.nothingForYou': 'Nothing for you.',
  'line.nothingToSayTo': 'Nothing to say to you.',
  'line.oldNewsFriend': 'Old news, friend.',
  'line.onSecondThoughtI': 'On second thought, I cannot.',
  'line.overAndOut': 'Over and out.',
  'line.overMyWreck': 'Over my wreck.',
  'line.overMyDeadBody': 'Over my dead body.',
  'line.pullFree': m('I can pull you to {town}. No charge.', { town: 'text' }),
  'line.pullPaid': m('I can pull you to {town}. {fee} when we get there.', { town: 'text', fee: 'text' }),
  'line.pullingOver': 'Pulling over.',
  'line.rollingOn': 'Rolling on.',
  'line.runThen': 'Run, then.',
  'line.runningLowICan': 'Running low? I can spare some.',
  'line.saidThatAlready': 'Said that already.',
  'line.sayThatAgain': 'Say that again?',
  'line.saysWho': 'Says who?',
  'line.seenAnythingWorthA': 'Seen anything worth a look out there?',
  'line.sitTight': 'Sit tight.',
  'line.siteBearing': m('{site} lies {bearing} of you, about {distance} out.', { site: 'text', bearing: 'text', distance: 'text' }),
  'line.smartChoice': 'Smart choice.',
  'line.sorryCannotSpareAny': 'Sorry. Cannot spare any.',
  'line.spare': 'You are not worth the trouble.',
  'line.speakUp': 'Speak up.',
  'line.standDownAndLet': 'Stand down and let me strip your truck.',
  'line.standingDown': 'Standing down.',
  'line.stateYourBusiness': 'State your business.',
  'line.stopShootingIGive': 'Stop shooting! I give up. Take what I carry and let me go.',
  'line.surePullOverAnd': 'Sure. Pull over and I will come alongside.',
  'line.surrenderOffer': 'Your truck is dead. Hand over the cargo and your best parts, and you keep the truck. Refuse, and I take it off your wreck.',
  'line.takeMeToSite': m('Take me to {site}. I can pay {fee} when we get there.', { site: 'text', fee: 'text' }),
  'line.takeWhatICarry': 'Take what I carry. Just let me drive away.',
  'line.talk': 'Talk.',
  'line.talkFast': 'Talk fast.',
  'line.thanksIWillWait': 'Thanks. I will wait.',
  'line.thanksOverAndOut': 'Thanks. Over and out.',
  'line.thanksSomethingElse': 'Thanks. Something else.',
  'line.thenComeAndGet': 'Then come and get me.',
  'line.thenWeFinishThis': 'Then we finish this.',
  'line.thisIsMine': 'This is mine.',
  'line.thisWreckIsMine': 'This wreck is mine. Back off.',
  'line.tipTold': m('{tip}', { tip: 'text' }),
  'line.tooLateForTalk': 'Too late for talk.',
  'line.tooMuch': 'Too much.',
  'line.townBearing': m('{town} lies {bearing} of you, about {distance} out.', { town: 'text', bearing: 'text', distance: 'text' }),
  'line.truceCost': m('{price}, and we forget it.', { price: 'text' }),
  'line.understood': 'Understood.',
  'line.wantToTrade': 'Want to trade?',
  'line.weAlreadyTalkedAbout': 'We already talked about that.',
  'line.weBothDriveAway': 'We both drive away.',
  'line.weCoveredThat': 'We covered that.',
  'line.weWillSee': 'We will see.',
  'line.whatAreYouOffering': 'What are you offering?',
  'line.whatCanYouOffer': 'What can you offer?',
  'line.whatDoYouWant': 'What do you want?',
  'line.whatWouldItCost': 'What would it cost to call this off?',
  'line.whatWouldItTake': 'Engine, gearbox or tank. What would it take?',
  'line.whateverYouCanSpare': 'Whatever you can spare.',
  'line.where': 'Where?',
  'line.whereIsTheNearest': 'Where is the nearest town?',
  'line.yeahMakeItQuick': 'Yeah? Make it quick.',
  'line.youHeardMeCargo': 'You heard me. Cargo on the ground, now.',
  'line.youHeardMeLeave': 'You heard me. Leave it.',
  'line.youKnowHowThen': 'You know how? Then name it.',
  'line.youLookDryI': m('You look dry. I can spare {aid}, no charge.', { aid: 'text' }),
  'line.youSaidThat': 'You said that.',
  'line.youWantToPick': 'You want to pick my truck clean?',
  'line.yourLoadIsInThe': 'Your load is in the dirt. Roll on and it is ours, and we are square.',
  'line.yourCallLastChance': 'Your call. Last chance.',
  'line.yourEngineSoundsRough': 'Your engine sounds rough. Want me to patch it before it quits?',
  'line.yourFuneral': 'Your funeral.',
  'line.yourTruckIsFinished': 'Your truck is finished. Stand down and let me strip it, and you live.',
  'line.yourTruckLooksDead': 'Your truck looks dead. Want me to patch it?',
  // Patch terms in the driver's words, shown for {deal}. Lines never name turns.
  'deal.paid.npc': m('I have the parts. {parts} and the work, {price} all in.', { parts: 'text', price: 'text' }),
  'deal.paid.player': m('I pay {price} if you use {parts} of yours.', { price: 'text', parts: 'text' }),
  'deal.ownParts.npc': m('It takes {parts} of yours. I charge {price} for the work.', { parts: 'text', price: 'text' }),
  'deal.ownParts.player': m('I have {parts} here. {price} for your work.', { parts: 'text', price: 'text' }),
  'deal.free.npc': m('I will do it for nothing. {parts} of mine.', { parts: 'text' }),
  'deal.free.player': m('I cannot pay. Could you spare {parts}?', { parts: 'text' }),
  // A trading tip, shown for {tip}. It never names a number.
  'tip.dear': m('Last time I was at {site}, {subject} very overpriced.', { site: 'text', subject: 'text' }),
  'tip.cheap': m('Last time I was at {site}, {subject} going cheap.', { site: 'text', subject: 'text' }),
  'tip.none': 'Nothing worth telling.',
  // Call values in words.
  'compass.east': 'east',
  'compass.southEast': 'south-east',
  'compass.south': 'south',
  'compass.southWest': 'south-west',
  'compass.west': 'west',
  'compass.northWest': 'north-west',
  'compass.north': 'north',
  'compass.northEast': 'north-east',
  'call.km': m('{km} km', { km: 'dec1' }),
  'call.m': m('{m} m', { m: 'int' }),
  'call.money': m('{amount} M', { amount: 'int' }),
  'call.price': m('{good} buy {buy} sell {sell}', { good: 'text', buy: 'text', sell: 'text' }),
  'call.fuel': m('{liters} L of fuel', { liters: 'int' }),
  'call.supplies': m('{n, plural, one {# supply} other {# supplies}}', { n: 'count' }),
  'call.aid': m('{fuel} and {supplies}', { fuel: 'text', supplies: 'text' }),
  'call.speaker': m('Radio: {who}', { who: 'text' }),
  'call.said': m('“{line}”', { line: 'text' }),
  'call.option': m('{n}. {line}', { n: 'int', line: 'text' }),
  // J.J.'s broadcasts on Waste Of Time Radio, radio.<topic>.<variant>. She talks about the basin, never the game. Slots:
  // {place} is near a found site or a basin direction, {heading} a compass word, {shop} and {to} found sites, {good} a good,
  // {part} a part and {target} an NPC template.
  'radio.ident.0': 'This is J.J. on Waste Of Time Radio, wasting your time since the sky fell.',
  'radio.ident.1': 'Waste Of Time Radio, J.J. at the mic. Nobody asked, and here I am anyway.',
  'radio.dawn.0': 'Sun\'s up over the basin. The water sellers have beaten it to market.',
  'radio.dawn.1': 'Morning, boys. Dew on the glass, sand in the gears. Same as yesterday.',
  'radio.dawn.2': 'Dawn report: sky clear of anything worth eating. Rise and roll.',
  'radio.noon.0': 'High noon. The engines are singing a song I never learned to like.',
  'radio.noon.1': 'Noon on the basin. Even the lizards have the sense to stop.',
  'radio.dusk.0': 'Sun going down. Somewhere, somebody just became a landmark.',
  'radio.dusk.1': 'Dusk report: the day crop came in dry again. Bring it home, boys.',
  'radio.midnight.0': 'Midnight. Only the engines know whose road this is.',
  'radio.midnight.1': 'Midnight on Waste Of Time Radio. Still here. Still wasting it.',
  'radio.heatwaveStart.0': 'Heat wave coming. The radiator choir has begun its warm-up.',
  'radio.heatwaveStart.1': 'Heat wave over the basin. Radiators will boil before the kettles do.',
  'radio.heatwaveEnd.0': 'Heat wave broke. The engine choir is mercifully quiet.',
  'radio.heatwaveEnd.1': 'That heat finally let go. Thank whoever you thank.',
  'radio.overcastStart.0': 'Clouds over the basin. The sun\'s taking the day off.',
  'radio.overcastStart.1': 'Overcast and cool. The sky remembered how to be kind.',
  'radio.stormStart.0': m('Dust storm rolling {place}, heading {heading}.', { place: 'text', heading: 'text' }),
  'radio.stormStart.1': m('Dust wall {place}, drifting {heading}. The horizon just resigned.', { place: 'text', heading: 'text' }),
  'radio.stormEnd.0': m('That dust storm {place} has blown itself out.', { place: 'text' }),
  'radio.stormEnd.1': m('Storm {place} settled. Somebody go dig out the road.', { place: 'text' }),
  'radio.haul.0': m('New haul posted at {shop}: {good} out to {to}.', { shop: 'text', good: 'text', to: 'text' }),
  'radio.haul.1': m('{shop} needs {good} carried to {to}. Honest work, for once.', { shop: 'text', good: 'text', to: 'text' }),
  'radio.fetch.0': m('{shop} is asking after a working {part}.', { shop: 'text', part: 'text' }),
  'radio.fetch.1': m('Wanted at {shop}: one {part}, still breathing.', { shop: 'text', part: 'text' }),
  'radio.bounty.0': m('{shop} put a price on {target}. Business, not murder, they say.', { shop: 'text', target: 'text' }),
  'radio.bounty.1': m('Paper up at {shop} for {target}. I just read the board, boys.', { shop: 'text', target: 'text' }),
  'radio.raid.0': m('Raider business {place}. Another busy day for the accountants.', { place: 'text' }),
  'radio.raid.1': m('Raiders working the road {place}. Cargo changes hands out there.', { place: 'text' }),
  'radio.raid.2': m('Word of a stickup {place}. Raiders, keeping regular hours.', { place: 'text' }),
  'radio.raidKnockout.0': m('Another rig went quiet {place}. Raiders, by the sound of it.', { place: 'text' }),
  'radio.raidKnockout.1': m('A rig sits dead {place}. Raiders took their cut. Nobody take more.', { place: 'text' }),
  'radio.wisdom.0': 'The noon sun has opinions about engines. The shade keeps its own counsel.',
  'radio.wisdom.1': 'Town guns have a longer memory than the town clerk.',
  'radio.wisdom.2': 'After dark, you hear a neighbor long before you see one.',
  'radio.wisdom.3': 'A silent rig at the roadside has either good brakes or bad luck.',
  'radio.wisdom.4': 'Road dust has a way of introducing a driver before their name does.',
  'radio.wisdom.5': 'A heavy rig always gets the last word in an argument with a light one.',
  'radio.wisdom.6': 'Off-road miles have a habit of becoming repair bills.',
  'radio.wisdom.7': 'A stranded trader gets visitors. A stranded raider gets stories.',
  'radio.wisdom.8': 'The dust swallowed the horizon again. I never trusted it anyway.',
  'radio.wisdom.9': 'A fuel needle at the bottom tells the longest stories.',
  'radio.wisdom.10': 'Town beds are dear. A night without a wrench is dearer.',
  'radio.wisdom.11': 'Somebody honked at a trader. The trader honked back. Society survives.',
  'radio.wisdom.12': 'My producer says we need a sponsor. I told him we need a producer.',
  'radio.wisdom.13': 'Found an Old World weather report. It ended with “chance of rain.” Lovely fiction.',
  'radio.wisdom.14': 'The mast is still here. The coffee is not. One of us has priorities.',
  'radio.wisdom.15': 'Tonight the road has company. Tomorrow it will deny knowing any of them.',
  'radio.wisdom.16': 'A listener sent me a map. It had one mark: “not here.” Sensible cartography.',
  'radio.wisdom.17': 'I have been accused of talking to myself. You are the evidence against me.',
  'radio.wisdom.18': 'The static just requested a song. I said it was already playing one.',
  'radio.wisdom.19': 'Somewhere an honest mechanic has retired. The rest have raised their prices.',
  // The station name on the band. A brand, the same in every language.
  'radio.band': 'WOT RADIO',
  'radio.frequency': 'FM 66.6',
  // Places and directions.
  'radio.near': m('near {site}', { site: 'text' }),
  'radio.basin.east': 'out east',
  'radio.basin.southEast': 'in the southeast basin',
  'radio.basin.south': 'down south',
  'radio.basin.southWest': 'in the southwest basin',
  'radio.basin.west': 'out west',
  'radio.basin.northWest': 'in the northwest basin',
  'radio.basin.north': 'up north',
  'radio.basin.northEast': 'in the northeast basin',
  'radio.heading.east': 'east',
  'radio.heading.southEast': 'southeast',
  'radio.heading.south': 'south',
  'radio.heading.southWest': 'southwest',
  'radio.heading.west': 'west',
  'radio.heading.northWest': 'northwest',
  'radio.heading.north': 'north',
  'radio.heading.northEast': 'northeast',
};
