// Entries added while merging dev's UI changes. Fold into screens.ts.
import { m } from '../msg';

export const UI = {
  'money.m': m('{n} M', { n: 'int' }),
  'menu.menu': 'Menu',
  'menu.help': 'Help',
  'menu.options': 'Options',
  'options.title': 'Options',
  'help.title': 'Controls',
  'help.errorsSent': 'Game errors are sent to the developers with your save.',
  'hud.overdriveWorn': m('Engine too worn for overdrive: repair it above {pct}% [O]', { pct: 'int' }),
  'hit.cause.smoke': 'smoke',
  'hit.reason.smoke': 'smoke',
  'hit.shutDown': m('Shut down: {n, plural, one {# turn} other {# turns}} left', { n: 'count' }),
  'save.exportSave': 'Export save',
  'save.exportSaveTitle': 'Download the game as it is now',
  'save.exportLog': 'Export run log',
  'save.exportLogTitle': 'Download what happened this run, one event per line',
  'stat.lineHolds': 'Turns the line holds',
  'hint.wreck': 'Your engine is nearly dead. [Shift]-click the ground by the wreck to set a stop point, then [Space] to drive there.',
  'hint.search': 'Click Search the wreck, then [Space] to run the search.',
  'hint.loot': 'Drag the parts and the Rebar cage onto your truck, or click Take all that fits.',
  'hint.patch': '[I] opens your truck. Click the engine, then Patch. Close your truck and [Space] runs the patch.',
  'hint.install': '[I] opens your truck. Drag the Rebar cage onto a free cell at its edge, then close it and [Space] mounts the cage.',
  'mode.roaming': 'Roaming',
  'mode.roaming.description': 'The open wasteland. Drive, trade, scavenge and fight as you like.',
  'setting.damage': 'Damage',
  'setting.damage.description': 'Damage of every gun and crash, for every truck.',
  'setting.fuelUse': 'Fuel use',
  'setting.fuelUse.description': 'Fuel every truck burns per tile driven.',
  'setting.supplyUse': 'Supply use',
  'setting.supplyUse.description': 'Supplies every crew eats per turn.',
  'save.download': 'Download save',
  'save.reportBug': 'If this looks like a bug, download the save and attach it to a GitHub issue.',
  'save.settingReset': m('{setting} was reset to {pct}%', { setting: 'text', pct: 'int' }),
  'inv.nothingFound': 'Nothing found yet.',
  'inv.instantHint': 'Parts fit at once: drag them onto a mount or off it.',
  'block.unmounted': 'not mounted',
  'block.shutDown': 'shut down',
  'block.lineOut': 'line out',
  'block.armed': 'already armed',
  'block.fuel': 'not enough fuel',
  'blockShort.unmounted': 'stowed',
  'blockShort.shutDown': 'off',
  'blockShort.lineOut': 'line',
  'utility.pick': 'aim: click the ground',
  'utility.fires': 'fires this turn',
  'utility.armed': 'armed',
  'utility.noFuel': 'no fuel',
  'utility.recharging': m('recharging {n, plural, one {# turn} other {# turns}}', { n: 'count' }),
  'utility.slotLabel': m('{name}: {status}', { name: 'text', status: 'text' }),
  'utility.keyTitle': m('{name} [{key}]', { name: 'text', key: 'int' }),
  'weapon.allGuns': 'all guns',
  'weapon.gunN': m('gun {n}', { n: 'int' }),
  'weapon.body': 'Body',
  'weapon.bodyTitle': m('Body shot with {guns}: rounds hit whatever part they reach. Click again to stop.', { guns: 'text' }),
  'icon.utility': 'Utility',
  'stat.recharge': 'Turns to recharge',
  'stat.lasts': 'Turns it lasts',
  'stat.slick': 'Slick length',
  'stat.radius': 'Radius',
  'trade.filter.utility': 'Utilities',
  'trade.theyCantPay': 'They can\'t pay that',
  'contract.claim': 'Claim',
  'contract.claimAt': m('Claim at {site}', { site: 'text' }),
  'contract.notMet': 'Not met yet',
  'contract.ready': 'Ready',
  'short.util': 'Util',
  'log.found': m('Found {items}.', { items: 'text' }),
  'log.caltropsYou': 'You drive into caltrops',
  'log.caltropsThem': m('{who} drives into caltrops', { who: 'text' }),
  'log.pulseNone': 'Your emitter pulse catches nobody',
  'log.pulseYours': m('Your emitter pulse shuts down {who}', { who: 'text' }),
  'log.pulseTheirs': m('{who}\'s emitter pulse shuts your truck down for {n, plural, one {# turn} other {# turns}}', { who: 'text', n: 'count' }),
  'log.cookOffYours': 'Your claymore ram breaks and blows up',
  'log.cookOffTheirs': m('{who}\'s claymore ram breaks and blows up', { who: 'text' }),
  'log.obstacle.rock': 'a rock',
  'log.obstacle.wreck': 'a wreck',
  'log.obstacle.building': 'a building',
  'log.obstacle.water': 'the water',
  'log.obstacle.site': 'a structure',
  'log.obstacle.landmark': 'a landmark',
  'log.claymoreWallYours': m('Your claymore ram blows up against {what}', { what: 'text' }),
  'log.claymoreWallTheirs': m('{who}\'s claymore ram blows up against {what}', { who: 'text', what: 'text' }),
  'log.claymoreYours': m('Your claymore ram blasts {whom}', { whom: 'text' }),
  'log.claymoreYou': m('{who}\'s claymore ram blasts your truck', { who: 'text' }),
  'log.claymoreTheirs': m('{who}\'s claymore ram blasts {whom}', { who: 'text', whom: 'text' }),
  'log.cargoSpilledOther': m('{who}: cargo spilled on the ground', { who: 'text' }),
  'log.cargoSpilledYours': m('{part} broke. {n, plural, one {# item} other {# items}} fell out.', { part: 'text', n: 'count' }),
  'log.harpoon': m('{gun} → {target}: {what}', { gun: 'text', target: 'text', what: 'text' }),
  'log.harpoonLine': m('line on {part}', { part: 'text' }),
  'log.harpoonMissed': 'missed',
  'log.lineTornYou': 'You tear free of a harpoon line',
  'log.lineTornThem': m('{who} tears free of a harpoon line', { who: 'text' }),
  'newGame.mode': 'Game mode',
  'newGame.settings': 'World Settings',
  'newGame.start': 'Start',
  'newGame.back': 'Back',
  'newGame.reset': 'Reset to defaults',
  'newGame.default': m('default {pct}', { pct: 'text' }),
  'setup.part': m('{setting} {pct}', { setting: 'text', pct: 'text' }),
  'setting.percent': m('{n}%', { n: 'int' }),
  'cell.deadRows': 'Broken cargo rows. Repair the cargo part to use them.',
  'kind.utility': 'utility',
};
