// Entries added while merging dev's UI changes. Fold into screens.ts.
import { m } from '../msg';

export const UI = {
  'money.minus': m("−{n, plural, one {# M} other {# M's}}", { n: 'count' }),
  'money.m': m("{n, plural, one {# M} other {# M's}}", { n: 'count' }),
  'menu.menu': 'Menu',
  'menu.help': 'Help',
  'menu.options': 'Options',
  'options.title': 'Options',
  'help.title': 'Controls',
  'help.errorsSent': 'Game errors are sent to the developers with your save.',
  'hud.overdriveNoEngine': 'No engine',
  'hud.overdriveWorn': m('Engine too worn for overdrive: repair it above {pct}% [O]', { pct: 'int' }),
  'hit.cause.smoke': 'smoke',
  'hit.reason.smoke': 'smoke',
  'hit.shutDown': m('Shut down: {n, plural, one {# turn} other {# turns}} left', { n: 'count' }),
  'save.exportSave': 'Export save',
  'save.exportSaveTitle': 'Download the game as it is now',
  'save.exportLog': 'Export run log',
  'save.exportLogTitle': 'Download what happened this run, one event per line',
  'stat.lineHolds': 'Turns the line holds',
  'hint.wreck': '[Shift]-click the ground by the wreck, then [Space] to drive there.',
  'hint.search': 'Click Search the wreck, then [Space].',
  'hint.loot': 'Click Take all that fits.',
  'hint.patch': '[I], click the engine, click Patch, then [Space].',
  'hint.install': '[I], drag the Rebar cage to a free cell at the truck\'s edge, then [Space].',
  'mode.roaming': 'Roaming',
  'mode.roaming.description': 'The open wasteland. Drive, trade, scavenge and fight as you like.',
  'setting.damage': 'Damage',
  'setting.damage.description': 'Damage of every gun and crash, for every truck.',
  'setting.fuelUse': 'Fuel use',
  'setting.fuelUse.description': 'Fuel every truck burns per tile driven.',
  'setting.supplyUse': 'Supply use',
  'setting.supplyUse.description': 'Supplies every crew eats per turn.',
  'save.download': 'Download save',
  'save.reportBug': 'If this looks like a bug, download the save and attach it to a GitHub issue.',
  'save.settingReset': m('{setting} was reset to {pct}%', { setting: 'text', pct: 'int' }),
  'inv.nothingFound': 'Nothing found yet.',
  'inv.instantHint': 'Parts fit at once: drag them onto a mount or off it.',
  'block.unmounted': 'not mounted',
  'block.shutDown': 'shut down',
  'block.lineOut': 'line out',
  'block.armed': 'already armed',
  'block.fuel': 'not enough fuel',
  'blockShort.unmounted': 'stowed',
  'blockShort.shutDown': 'off',
  'blockShort.lineOut': 'line',
  'utility.pick': 'aim: click the ground',
  'utility.fires': 'fires this turn',
  'utility.armed': 'armed',
  'utility.noFuel': 'no fuel',
  'utility.recharging': m('recharging {n, plural, one {# turn} other {# turns}}', { n: 'count' }),
  'utility.slotLabel': m('{name}: {status}', { name: 'text', status: 'text' }),
  'utility.keyTitle': m('{name} [{key}]', { name: 'text', key: 'int' }),
  'weapon.allGuns': 'all guns',
  'weapon.gunN': m('gun {n}', { n: 'int' }),
  'weapon.body': 'Body',
  'weapon.bodyTitle': m('Body shot with {guns}: rounds hit whatever part they reach. Click again to stop.', { guns: 'text' }),
  'icon.utility': 'Utility',
  'stat.recharge': 'Turns to recharge',
  'stat.lasts': 'Turns it lasts',
  'stat.slick': 'Slick length',
  'stat.radius': 'Radius',
  'trade.filter.utility': 'Utilities',
  'trade.theyCantPay': 'They can\'t pay that',
  'contract.claim': 'Claim',
  'contract.claimAt': m('Claim at {site}', { site: 'text' }),
  'contract.notMet': 'Not met yet',
  'contract.ready': 'Ready',
  'short.util': 'Util',
  'log.found': m('Found {items}.', { items: 'text' }),
  'log.caltropsYou': 'You drive into caltrops',
  'log.caltropsThem': m('{who} drives into caltrops', { who: 'text' }),
  'log.pulseNone': 'Your emitter pulse catches nobody',
  'log.pulseYours': m('Your emitter pulse shuts down {who}', { who: 'text' }),
  'log.pulseTheirs': m('{who}\'s emitter pulse shuts your truck down for {n, plural, one {# turn} other {# turns}}', { who: 'text', n: 'count' }),
  'log.cookOffYours': 'Your claymore ram breaks and blows up',
  'log.cookOffTheirs': m('{who}\'s claymore ram breaks and blows up', { who: 'text' }),
  'log.obstacle.rock': 'a rock',
  'log.obstacle.wreck': 'a wreck',
  'log.obstacle.building': 'a building',
  'log.obstacle.water': 'the water',
  'log.obstacle.site': 'a structure',
  'log.obstacle.landmark': 'a landmark',
  'log.claymoreWallYours': m('Your claymore ram blows up against {what}', { what: 'text' }),
  'log.claymoreWallTheirs': m('{who}\'s claymore ram blows up against {what}', { who: 'text', what: 'text' }),
  'log.claymoreYours': m('Your claymore ram blasts {whom}', { whom: 'text' }),
  'log.claymoreYou': m('{who}\'s claymore ram blasts your truck', { who: 'text' }),
  'log.claymoreTheirs': m('{who}\'s claymore ram blasts {whom}', { who: 'text', whom: 'text' }),
  'log.cargoSpilledOther': m('{who}: cargo spilled on the ground', { who: 'text' }),
  'log.cargoSpilledYours': m('{part} broke. {n, plural, one {# item} other {# items}} fell out.', { part: 'text', n: 'count' }),
  'log.harpoon': m('{gun} → {target}: {what}', { gun: 'text', target: 'text', what: 'text' }),
  'log.harpoonLine': m('line on {part}', { part: 'text' }),
  'log.harpoonMissed': 'missed',
  'log.lineTornYou': 'You tear free of a harpoon line',
  'log.lineTornThem': m('{who} tears free of a harpoon line', { who: 'text' }),
  'newGame.mode': 'Game mode',
  'newGame.settings': 'World Settings',
  'newGame.start': 'Start',
  'newGame.back': 'Back',
  'newGame.reset': 'Reset to defaults',
  'newGame.default': m('default {pct}', { pct: 'text' }),
  'setup.part': m('{setting} {pct}', { setting: 'text', pct: 'text' }),
  'setting.percent': m('{n}%', { n: 'int' }),
  'cell.deadRows': 'Broken cargo rows. Repair the cargo part to use them.',
  'kind.utility': 'utility',
  'menu.showTips': 'Show tips',
  'menu.showTipsOn': '✓ Show tips',
  'menu.closeEsc': 'Close [Esc]',
  'menu.waitForTurn': 'Wait for the turn',
  'help.group.drive': 'Drive',
  'help.group.places': 'Places and talk',
  'help.group.fight': 'Fight',
  'help.group.view': 'View',
  'help.key.click': 'Click',
  'help.key.shift': 'Shift',
  'help.key.space': 'Space',
  'help.key.holdSpace': 'Hold Space',
  'help.key.rightDrag': 'Right drag',
  'help.key.wheel': 'Wheel',
  'help.on.ground': 'ground',
  'help.on.yourTruck': 'your truck',
  'help.on.townOrSite': 'town or site',
  'help.on.pad': 'pad',
  'help.on.truck': 'truck',
  'help.to': 'to',
  'help.does.driveByRoad': 'Drive by road',
  'help.does.stopThere': 'Stop there',
  'help.does.driveOrPause': 'Drive or pause',
  'help.does.fastForward': 'Fast-forward',
  'help.does.brake': 'Brake',
  'help.does.manual': 'Manual driving',
  'help.does.autoPatch': 'Auto patch',
  'help.does.stopAtPad': 'Stop at its pad',
  'help.does.padWork': 'Trade, repair or loot',
  'help.does.radio': 'Radio the inspected truck',
  'help.does.reply': 'Reply',
  'help.does.honk': 'Honk',
  'help.does.inspectOrAim': 'Inspect or aim',
  'help.does.pickWeapon': 'Pick a weapon',
  'help.does.allWeapons': 'All weapons',
  'help.does.autoFire': 'Auto fire',
  'help.does.showWeapons': 'Show weapons',
  'help.does.pan': 'Pan',
  'help.does.zoom': 'Zoom',
  'help.does.center': 'Center',
  'help.does.camera': 'Camera',
  'help.does.mute': 'Mute',
  'help.does.inventory': 'Inventory',
  'help.does.character': 'Character',
  'help.does.journal': 'Journal',
  'hitTip.weapon': 'Loose gun',
  'hitTip.range': 'Far',
  'hitTip.recoil': 'Gun kick',
  'hitTip.skill': 'Driver perception',
  'hitTip.weather': 'Bad weather',
  'hitTip.smoke': 'Smoke',
  'hitTip.mine.crossing': 'Target crossing fast',
  'hitTip.mine.own': 'You are moving',
  'hitTip.mine.still': 'Target is parked',
  'hitTip.theirs.crossing': 'You are crossing fast',
  'hitTip.theirs.own': 'It is moving',
  'hitTip.theirs.still': 'You are parked',
  'hitTip.base': 'Base',
  'hit.wellYou': 'You',
  'hit.wellThem': 'Them',
  'weapon.turnPlaying': 'Turn playing',
  'weapon.reloadBroken': 'Broken',
  'weapon.reloadBusy': 'Reloading',
  'weapon.reloadFull': 'Magazine full',
  'weapon.noHoldTarget': 'No target set',
  'weapon.statusReady': 'Ready',
  'weapon.switchShow': 'Show',
  'weapon.switchHide': 'Hide',
  'weapon.autoFire': 'Auto fire',
  'weapon.autoOff': 'Off',
  'weapon.autoSwitchTitle': 'Guns shoot at hostiles on their own [Q]',
  'weapon.allOn': 'All',
  'weapon.allOff': 'One',
  'weapon.allSwitchTitle': 'Aim all weapons [0]',
  'weapon.holdHint': 'Stop auto fire and clear this gun\'s target',
  'utility.aiming': 'aiming',
  'character.xpPoolTitle': 'XP to spend on ranks',
  'character.maxRank': 'Max',
  'character.colSkill': 'Skill',
  'character.colRank': 'Rank',
  'hint.closeThis': 'Close this tip',
  'hint.turnOff': 'Turn off tips',
  'hit.deltaUp': m("+{n}%", { n: 'int' }),
  'hit.deltaDown': m("−{n}%", { n: 'int' }),
  'weapon.hitChanceOn': m("Hit chance on {target}", { target: 'text' }),
  'weapon.reloadHint': m("Drop the magazine and refill it in {n, plural, one {# turn} other {# turns}}", { n: 'count' }),
  'character.xpPool': m("{n} XP", { n: 'int' }),
  'character.buyShort': m("Buy {cost} XP", { cost: 'int' }),
  'character.colPerk': m("Rank {rank} perk", { rank: 'int' }),
  'character.colToday': m("Today, max {cap} XP", { cap: 'int' }),
  'stat.value': m("{text} {unit}", { text: 'text', unit: 'text' }),
  'stat.valueTight': m("{text}{unit}", { text: 'text', unit: 'text' }),
  'actBlock.knockedOut': 'Knocked out',
  'actBlock.towed': 'Under tow',
  'actBlock.onRadio': 'On the radio',
  'hud.tipsOff': 'Tips are off. Menu, Show tips turns them back on.',
  'hud.douseBlock.noSupplies': m('Need {n} supplies', { n: 'int' }),
  'hud.douseBlock.engineCool': 'Engine is cool',
  'mode.furyRoad': 'Fury Road',
  'mode.furyRoad.description': 'An endless highway north between forts. Every fight is to the wreck.',
  'boot.nextWindow': 'Opening the road north',
  'death.wrecked': 'Wrecked',
  'death.stranded': 'Stranded',
  'death.restartRun': 'Restart run',
  'death.runReached': m('{mode}. Reached {site}, {north} north', { mode: 'text', site: 'text', north: 'text' }),
  'death.runStart': m('{mode}. Stretch 1, {north} north', { mode: 'text', north: 'text' }),
  'hud.confirmEndRun': 'End the run here? It cannot be undone.',
  'hud.endRun': 'End run',
  'readout.run': 'Run',
  'readout.runValue': m('{stretch}: {left}', { stretch: 'int', left: 'text' }),
  'readout.runTip': m('Stretch {stretch}: {left} to {site}', { stretch: 'int', left: 'text', site: 'text' }),
  'log.outpostReached': m('{site}. Paid {pay} for the road.', { site: 'text', pay: 'text' }),
  'log.outpostReachedWrecks': m('{site}. Paid {pay} for the road and {n, plural, one {# wreck} other {# wrecks}}.', { site: 'text', pay: 'text', n: 'count' }),
  'log.runWrecked': m('Your truck is wrecked. The run ends on stretch {n}.', { n: 'int' }),
  'log.runEnded': m('You end the run on stretch {n}.', { n: 'int' }),
  'money.outpost': 'outpost pay',
  'outpost.name': m('{word} {n}', { word: 'text', n: 'int' }),
  'outpost.word': 'Outpost',
  'outpost.soldOut': 'Sold out',
  'action.enterOutpost': m('Enter {site}', { site: 'text' }),
  'units.km': m('{n} km', { n: 'dec1' }),
  'units.m': m('{n} m', { n: 'int' }),
};
